sxyazi/yazi

adaptor/src/image.rs
config/src/manager/manager.rs

Avoid hard coding `/tmp`, which makes cross-platform friendly.

refactor: avoid hard coding tmp dir

---

app/Cargo.toml

We can use `./target/{debug, release}/yazi` now.

chore: rename bin

---

Cargo.lock
app/Cargo.toml
app/src/header/tabs.rs
config/preset/theme.toml
config/src/theme/theme.rs
core/src/manager/tab.rs

This PR introduces a new option `max_width` in `[tab]` section for controlling the max width of current directory name in tab. Default value is `0` which means directory name won't be displayed in tab. This matches current behavior.
Here is an example for setting value to `10`:
The first tab's directory is "raffia" whose length is less than the threshold we set; the second tab's directory is "swc-plugin-react-remove-properties" whose length is greater than the threshold, so it's truncated and only the first 10 chars are displayed. (Should we add ellipses for this case?)

feat: show current dir name in tab

---

app/src/executor.rs
config/docs/keymap.md
core/src/manager/manager.rs
core/src/tasks/scheduler.rs

previous issues #37 
support style:
```
{ on = [ "l", "g" ], exec = "shell --block lazygit" },
{ on = [ "l", "g" ], exec = "shell --block 'lazygit -foo bar'" },
```

feat: add preset command to the `shell`

---

app/src/app.rs
config/src/boot/boot.rs
core/src/external/clipboard.rs
core/src/select/select.rs
core/src/which/mod.rs

This is a dummy pr to replicate the broken pull 68.
`yazi --file-chooser ./temp.txt ..`
You can now use my fork of [fm-nvim](https://github.com/Eric-Song-Nop/fm-nvim) with command Yazi.

feat: choose-file mode

---

app/src/executor.rs
core/src/manager/manager.rs
core/src/manager/tab.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/70
Now you can use variables like `$1`, `$@`, and `$*` just like the real shell does!
https://github.com/sxyazi/yazi/assets/17523360/52158059-d819-45c2-9851-5cf2098634e7

feat: allow references to the selected files during shell execution

---

app/src/manager/layout.rs
app/src/manager/preview.rs
config/docs/yazi.md
config/preset/keymap.toml
config/preset/yazi.toml
config/src/manager/layout.rs
config/src/manager/manager.rs
config/src/manager/mod.rs
core/src/manager/folder.rs
core/src/manager/mod.rs
core/src/manager/preview.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/71
There are some special cases:
- `layout = [ 1, 4, 0 ]`, no preview
- `layout = [ 0, 1, 0 ]`, single column

feat: custom manager layout

---

config/preset/keymap.toml

Organize keys for logical behavior

---

core/src/input/input.rs
shared/src/term/cursor.rs
shared/src/term/term.rs

I've noticed that after closing the input prompt from the insert mode, the cursor shape doesn't change back to block
How to reproduce:
1) open input prompt (e.g try to rename some file)
2) press enter to close it (from insert mode)
3) see that cursor shape is now bar (I guess it should be block as before opening `yazi`)
<details>
<summary>Before</summary>
<br>
https://github.com/sxyazi/yazi/assets/61150013/fb33b774-e1a9-4490-8ce8-be203a4c7b73
</details>
<details>
<summary>After</summary>
<br>
https://github.com/sxyazi/yazi/assets/61150013/22c7fa80-be8f-409d-93c0-b4164ec8ab51
</details>
(Not sure that I placed `Term::set_cursor_block()` to the right place)

fix: set cursor block after closing input prompt from insert mode

---

core/src/external/clipboard.rs

Close https://github.com/sxyazi/yazi/issues/118

fix: doesn't redirect the stderr of the clipboard command to null

---

core/src/files/file.rs
core/src/manager/manager.rs
core/src/manager/watcher.rs

Try to fix https://github.com/sxyazi/yazi/issues/108

fix: notification of file changes in linked directories

---

core/src/manager/watcher.rs

Try to fix https://github.com/sxyazi/yazi/issues/108

fix: recognize symlink directories as files

---

core/src/event.rs
core/src/input/input.rs
core/src/input/option.rs
core/src/manager/manager.rs
core/src/manager/tab.rs
core/src/tasks/tasks.rs
shared/src/errors/input.rs
shared/src/errors/mod.rs

Prepare for https://github.com/sxyazi/yazi/pull/104, finding in real-time.

feat: make `Input` streamable

---

Cargo.lock
app/src/app.rs
app/src/executor.rs
app/src/manager/folder.rs
app/src/manager/layout.rs
app/src/status/left.rs
app/src/status/right.rs
app/src/which/side.rs
config/preset/keymap.toml
config/src/keymap/control.rs
config/src/keymap/exec.rs
core/src/event.rs
core/src/files/files.rs
core/src/files/op.rs
core/src/manager/finder.rs
core/src/manager/folder.rs
core/src/manager/mod.rs
core/src/manager/preview/preview.rs
core/src/manager/preview/provider.rs
core/src/manager/tab.rs
core/src/which/which.rs
shared/src/debounce.rs
shared/src/lib.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/81
Close https://github.com/sxyazi/yazi/issues/81
---
https://github.com/sxyazi/yazi/assets/17523360/425aa023-cdb0-4d77-991d-c68472a5a7f4

feat: find

---

config/docs/yazi.md
config/src/open/mod.rs
config/src/open/open.rs
config/src/open/rule.rs
core/src/tasks/tasks.rs

feat: multiple openers for a single rule

---

core/src/manager/manager.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/168
Close https://github.com/sxyazi/yazi/issues/168

fix: leave upwards only if an IO error occurs in `current`

---

core/src/manager/tabs.rs

This allows tab switching to wrap back to the opposite extremity. E.g., if 5 tabs are open:
- `tab_switch 1` (<kbd>]</kbd> by default) from tab 5 will wrap to tab 1
- `tab_switch -1` (<kbd>[</kbd> by default) from tab 1 will wrap to tab 5

feat: tab switch wraparound

---

adaptor/src/adaptor.rs
shared/src/term/cursor.rs

Zellij only supports sixel, and can detect zellij env with `ZELLIJ_SESSION_NAME`.
Also I ran `cargo fmt`

Fix image preview broken on zellij with wezterm

---

.gitignore
flake.lock
flake.nix
nix/shell.nix
nix/yazi.nix

feat: add flake.nix

---

core/src/external/fd.rs
core/src/external/rg.rs

```
-I, --no-ignore
Show search results from files and directories that would otherwise be ignored by
'.gitignore', '.ignore', '.fdignore', or the global ignore file. The flag can be
overridden with --ignore.
```

feat: include ignored files on search when hidden files are shown

---

config/src/open/opener.rs
core/src/external/shell.rs
core/src/manager/manager.rs
core/src/manager/tab.rs
core/src/tasks/scheduler.rs
core/src/tasks/workers/process.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/194
Close https://github.com/sxyazi/yazi/issues/194
https://github.com/sxyazi/yazi/assets/17523360/bd18b74f-0c82-4fd2-bbe1-307d53837ee6

feat: new `orphan` option for opener rules, to keep the process running even when Yazi exited

---

app/src/executor.rs
config/preset/keymap.toml
core/src/lib.rs
core/src/manager/folder.rs
core/src/manager/tab.rs
core/src/step.rs

Now users can use command like `arrow 50%`, `arrow -50%` to move cursor in the distance calculated by percentage of page rows.
In a nutshell,
* `arrow -50%` to scroll up half page.
* `arrow 50%` to scroll down half page.
* `arrow 100%` to scroll down one page.
* `arrow 100%` to scroll up one page.
Users can customize the number, but I think the above is enough. See `config/preset/keymap.toml` in this PR.

feat: scroll half/full page with `arrow` percentage supported, and new Vi-like `<C-u>`, `<C-d>`, `<C-b>`, and `<C-f>` keybindings added

---

core/src/manager/folder.rs
core/src/step.rs

fix: a logic error in `Step`

---

Cargo.lock
core/Cargo.toml
core/src/external/shell.rs

fix: handle shell arguments on Windows

---

app/src/executor.rs
config/preset/keymap.toml
core/src/manager/finder.rs
core/src/manager/tab.rs

feat: added new options to the `find' command for smart-case/case-insensitive finding

---

core/src/manager/tab.rs
shared/src/url.rs

How to reproduce:
1. `g <space>`
2. enter ` C:\<some path>` (notice the prefix whitespace)
3. cannot cd

bugfix: cannot cd if there is whitespace prefix in path

---

shared/src/mime.rs

Some how `file -b --mime-type app/Cargo.toml` returns `application/x-wine-extension-ini` so I cannot preview as well as open `Cargo.toml` properly

Add x-wine-extension-ini to text mime

---

app/src/manager/layout.rs
config/preset/theme.toml
config/src/theme/theme.rs
plugin/preset/ui.lua
plugin/src/components.rs
plugin/src/layout/bar.rs
plugin/src/layout/layout.rs
plugin/src/layout/mod.rs
plugin/src/lib.rs
plugin/src/plugin.rs

```bash
[manager]
border_symbol = " "
```
```bash
[manager]
border_symbol = "|"
border_style  = { fg = "darkgray" }
```

feat: add a new `Bar` component, and make border styles customizable

---

app/src/executor.rs
config/preset/yazi.toml
config/src/open/open.rs
config/src/open/opener.rs
config/src/preview/preview.rs
core/src/manager/commands/open.rs
core/src/tab/commands/shell.rs
core/src/tab/tab.rs

Yazi now supports dividing opener rules by system type, this solves https://github.com/sxyazi/yazi/issues/110#issuecomment-1706538851
This PR also makes `display_name` as deprecated (to be fully removed in Yazi v1.0.6), using `desc` to maintain consistency with keymap.

feat: cross-system opener rule support

---

yazi-adaptor/Cargo.toml
yazi-adaptor/src/ueberzug.rs
yazi-config/preset/yazi.toml
yazi-config/src/preview/preview.rs

Fix https://github.com/sxyazi/yazi/issues/302
Example usage in yazi.toml for a 2.0 scale monitor on Hyprland:
```
[preview.ueberzug]
scale_down_factor = 2.0
x_offset = 0.5
y_offset = 0.5
width_offset = -0.5
height_offset = -0.5
```

Add config support for coordinate and size adjustment for ueberzugpp image preview

---

yazi-adaptor/src/sixel.rs

On BlackBox `\x2B[K` doesn't work for sixel characters. I thought this is a bug of gnome vte.

fix: clear sixel image with empty characters directly

---

flake.nix
nix/shell.nix

The rustfmt.toml rules are only supported by rust nightly. With the current stable rust tool chain in flake.nix, `cargo fmt` gives me warnings like
```
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `format_code_in_doc_comments = false`, unstable features are only available in n
```
The format result with those warnings is different from the current code base for almost all files. I guess the main contributors of the repo use nightly rust. If so, we should make it consistent in shell.nix to help other contributors onboard with the same env.

fix: change the rust tool chain in `shell.nix` from stable to nightly

---

yazi-adaptor/src/adaptor.rs

fix: use `WAYLAND_DISPLAY` and `DISPLAY` to detect Wayland/X11 when `XDG_SESSION_TYPE` is not set

---

yazi-core/src/external/jq.rs
yazi-core/src/preview/provider.rs

Fixes https://github.com/sxyazi/yazi/issues/318
This PR also adds the functionality of fallbacking to the built-in highlighter when the user provides an invalid JSON file to `jq`.

fix: `jq` previews empty when the user sets `tab_size=8`

---

.gitignore

Ignore `.vscode` and `.idea` to prevent contributor's personal configuration from polluting the project.

chore: add `.vscode` and `.idea` to .gitignore

---

yazi-shared/src/fns.rs

…ile and there is file with same name in folder

feat: add an identifier before the extension to prevent file conflicts rather than after

---

.github/workflows/release.yml

This PR adds `aarch64-unknown-linux-gnu` as Rust target in order to have binary releases for `linux/arm64` in the future.
See #325

ci: add Rust target "aarch64-unknown-linux-gnu" to release workflow

---

flake.nix

Having overlays makes it easier to install on NixOS systems.

feat: add overlays to flake.nix

---

yazi-plugin/preset/utils.lua

Right now Yazi only searches for the `$HOME` variable that is not present on windows. Either the user has to set `$env:HOME = "$env:USERPROFILE"` in his profile file or Yazi could also check for the `$USERPROFILE` variable.
My implementation of this functionality is pretty basic

feat(yazi-plugin): retrieve HOME also on windows

---

yazi-core/src/completion/commands/show.rs

Currently, the completion logic only use `contains` as the criteria. However, an ergonomic completion should prioritize candidates having the exact prefix with the input. This PR fixes this problem.

fix: prefix matching should have higher priority in completion

---

yazi-adaptor/src/image.rs
yazi-core/src/external/pdftoppm.rs
yazi-core/src/tasks/workers/precache.rs

Before this patch:
```bash
❯ yazi --clear-cache
❯ /usr/bin/time -l ./old
22.66 real        88.54 user         8.89 sys
2953068544  maximum resident set size
0  average shared memory size
0  average unshared data size
0  average unshared stack size
729991  page reclaims
544  page faults
0  swaps
0  block input operations
0  block output operations
27  messages sent
26  messages received
27  signals received
45566  voluntary context switches
355342  involuntary context switches
859110694754  instructions retired
249027752894  cycles elapsed
2104009664  peak memory footprint
```
After this patch:
```bash
❯ yazi --clear-cache
❯ /usr/bin/time -l ./new
20.98 real        89.38 user         8.32 sys
2618294272  maximum resident set size
0  average shared memory size
0  average unshared data size …
```

perf: reduce peak memory footprint during decoding large images

---

yazi-adaptor/src/image.rs
yazi-config/preset/yazi.toml
yazi-config/src/tasks/tasks.rs
yazi-core/src/external/pdftoppm.rs

Image decoding:
- image_alloc: Maximum memory allocation limit (in bytes) for decoding a single image, `0` for unlimited.
- image_bound(`[width, height]`): Maximum image size (in pixels) for decoding a single image, `0` for unlimited.
Close https://github.com/sxyazi/yazi/issues/373

feat: expose image max alloc and bound to allow for more control

---

yazi-config/preset/keymap.toml

This pull request adds additional keybindings for the cursor and page keys so that luddites such as myself 😉 can navigate `yazi` in much the same way as those who use Vim-style bindings.

feat: cursor and page key navigation parity with Vim bindings

---

yazi-config/preset/keymap.toml
yazi-config/src/manager/sorting.rs
yazi-core/src/files/sorter.rs

Now yazi can sort by file extension.
Keymap: ,+e and ,+E

feat: support sorting by file extension

---

yazi-plugin/Cargo.toml

... `LuaJIT` break some architecture (like: riscv64, loongarch64), make `mlua/luajit52` as default feature and add `mlua/lua52` feature to fix some architecture build.

fix: do not use `LuaJIT` in riscv64 and loongarch64 architecture

---

yazi-core/src/manager/commands/paste.rs
yazi-core/src/tasks/tasks.rs
yazi-scheduler/src/scheduler.rs
yazi-shared/src/fs/fns.rs

Instead of copying the file pointed to by the symlink , create a soft link to the original path under the pasted path
See #433

fix: add `--follow` option to `paste` command

---

yazi-config/preset/keymap.toml
yazi-config/src/popup/options.rs
yazi-core/src/input/commands/show.rs
yazi-core/src/input/snaps.rs
yazi-core/src/manager/commands/rename.rs

Closes #354
This is in my opinion a very important feature to have, and I'd have a further proposal:
use `--replace` as default behavior and add three different flags:
- `--append`: puts cursor between name and extension (e.g. `name|.ext`)
- `--append-ext`: puts cursor at the very end of the extension (current default behavior, e.g. `name.ext|`)
- `--prepend`: puts cursor at the very beginning of the file name (e.g. `|name.ext`)
This would be a little breaking, but I think it's worth it since we are moving to v0.2, and it would also be more consistent with ranger's behavior.
Please do let me know your thoughts on this :smiley:

feat: add `--empty` and `--cursor` options to the `rename` command

---

yazi-plugin/src/external/shell.rs

It can be useful for several purposes, such as detecting nested instances.
For example, I like to have an indicator on my shell prompt line when using a shell that has been launched from my terminal file manager.
For reference, other terminal file managers implementing the same feature:
- https://github.com/ranger/ranger/commit/23b7f16961a7b679dec16f6ee91401a6b8f6ca82
- https://github.com/gokcehan/lf/commit/e82cbb820f5c50e551ca8ac54f3ec87683859dfd
Sorry for anything that's unusual about the way I implemented it, I haven't yet contributed much to Rust projects, so I'm not that familiar with the conventions around the language. I'm happy to receive any reviews and make adjustments as required!
---
ps. As a bonus, here's an example configuration for `starship`, it might be worth adding this …

feat: add `YAZI_LEVEL` env variable for shells

---

.github/workflows/release.yml
snap/snapcraft.yaml

The `snapcraft.yaml` is quite straightforward. I'll explain a little bit, in case you may want to change it in the future.
On the top is various meta information, only things to be care are `grade` and `confinement`: 
- grade can be `devel` or `stable`, defines the quality grade of the snap. 
- confinement can be `strict` or `classic`, the latter means the snap have full system access just like traditionally applications.
The packing process is defined in `parts` section. 
- Building is take care by `rust` plugin, and carry out with `craftctl default`. You may replace it with any custom build commands. 
- `craftctl set version=...` is used to set the version info. 
- The rest is all for dependencies.
current only `fd-find`, `ripgrep`, `zoxide`, `fzf` are boundle with yazi, these may need …

feat: add support for snap packages

---

yazi-core/src/manager/commands/rename.rs
yazi-fm/src/components/header.rs
yazi-fm/src/components/manager.rs
yazi-fm/src/components/preview.rs
yazi-fm/src/help/bindings.rs
yazi-fm/src/help/layout.rs
yazi-fm/src/lives/tabs.rs
yazi-fm/src/which/layout.rs
yazi-fm/src/which/side.rs
yazi-plugin/src/bindings/window.rs
yazi-plugin/src/cast.rs
yazi-plugin/src/elements/list.rs
yazi-plugin/src/elements/span.rs
yazi-plugin/src/external/shell.rs
yazi-plugin/src/process/child.rs
yazi-plugin/src/process/command.rs
yazi-plugin/src/process/output.rs
yazi-plugin/src/process/status.rs
yazi-plugin/src/utils/call.rs
yazi-plugin/src/utils/text.rs
yazi-shared/src/fs/url.rs
yazi-shared/src/mime.rs

fix: can't display file name with invalid utf-8

---

yazi-core/src/input/commands/show.rs

Fixes https://github.com/sxyazi/yazi/issues/573

fix: input offset is not reset when renaming with `--cursor=start` and the filename is too long

---

yazi-adaptor/src/image.rs
yazi-adaptor/src/sixel.rs
yazi-config/preset/yazi.toml
yazi-config/src/preview/preview.rs

Closes https://github.com/sxyazi/yazi/issues/446 - @baitian752
Closes https://github.com/sxyazi/yazi/issues/562 - @AlexKurisu
> - image_quality: Quality on pre-caching images, range 50-90. The larger value, the better image quality, but slower with more CPU consumption, and generates larger cache files that occupy more storage space.
> - sixel_fraction: Sixel is a very old image format that only supports 256 colors. For better image preview, Yazi trains a neural network for each image to find the most representative colors. This value determines the number of samples used during the training, range 10-20. A smaller value produces better results but is also slower.
See the docs here: http://localhost:3000/docs/configuration/yazi#preview

feat: new `image_quality` and `sixel_fraction` options to allow users to configure the image preview quality

---

Cargo.lock
yazi-core/src/tasks/tasks.rs
yazi-fm/src/app/commands/plugin.rs
yazi-plugin/Cargo.toml
yazi-plugin/src/cast.rs
yazi-plugin/src/isolate/entry.rs
yazi-plugin/src/opt.rs
yazi-scheduler/src/plugin/op.rs
yazi-scheduler/src/plugin/plugin.rs
yazi-scheduler/src/scheduler.rs
yazi-shared/src/number.rs

You can now use the `plugin` command with `--args` for passing some arguments:
```bash
plugin your-plugin --args='foo bar'
```
Then receive them in your Lua code through `{ ... }`:
```lua
local args = { ... }
return {
entry = function()
ya.err(args[1]) -- "foo"
ya.err(args[2]) -- "bar"
end,
}
```

feat: support passing arguments to plugin

---

Cargo.lock
README.md
yazi-core/src/folder/files.rs
yazi-core/src/manager/commands/open.rs
yazi-core/src/manager/watcher.rs

Fixes https://github.com/sxyazi/yazi/issues/596
This PR optimizes the speed of reading large directories, leveraging the advantages of concurrency, it is ~2.5 times faster than before.
Here is a benchmark with a directory containing 500,000 files:
https://github.com/sxyazi/yazi/assets/17523360/21c2c70c-85dd-41f7-a5df-7add442d6997
https://github.com/sxyazi/yazi/assets/17523360/f05d7484-5dd5-4d2f-8b78-303d29423af0
https://github.com/sxyazi/yazi/assets/17523360/2a5f65be-c801-40ee-a52f-1d8ecd5f98fa

perf: read directory in bulk in the background at startup, make Yazi ~2.5 times faster than before

---

yazi-config/src/keymap/control.rs
yazi-config/src/keymap/key.rs
yazi-core/src/which/commands/callback.rs
yazi-core/src/which/commands/mod.rs
yazi-core/src/which/commands/show.rs
yazi-core/src/which/mod.rs
yazi-core/src/which/which.rs
yazi-fm/src/executor.rs
yazi-fm/src/help/layout.rs
yazi-fm/src/router.rs
yazi-fm/src/which/layout.rs
yazi-plugin/src/utils/layer.rs
yazi-plugin/src/utils/mod.rs
yazi-plugin/src/utils/utils.rs
yazi-shared/src/layer.rs

In async plugins, you can use `ya.which()` to prompt users with a set of available keys:
```lua
return {
entry = function()
local key = ya.which {
cands = {
{ on = "a" },
{ on = "b", desc = "optional description" },
{ on = "<C-c>", desc = "key combination" },
{ on = { "d", "e" }, desc = "multiple keys" },
},
-- silent = true, -- If you don't want to show the UI of key indicator
}
ya.err(key)
end,
}
```
When the user clicks a valid candidate, `ya.which` returns the 1-based index of that "cand"; otherwise, it returns `nil`, indicating that the user has canceled the key operation.
https://github.com/sxyazi/yazi/assets/17523360/9ef34c9f-6160-4452-a2a6-96d001b55e36
If you want to use the key in a sync plugin, you can awaken the plugin in an async plugin by:
```lua
ya.manager_emit("plugin", { …
```

feat: plugin interface for key events via `ya.which()`

---

yazi-fm/src/app/commands/plugin.rs
yazi-plugin/preset/state.lua
yazi-plugin/src/isolate/entry.rs

Fixes https://github.com/sxyazi/yazi/pull/587
As no new version has been released yet, this is not considered a breaking change.
Now please use:
```
return {
entry = function(self, args)
ya.err(args[1]) -- "foo"
ya.err(args[2]) -- "bar"
end,
}
```
to access the arguments of the plugin.

fix: attach plugin `args` to the `entry` method for better future optimization possibilities

---

yazi-config/src/theme/filetype.rs

Was messing around with themes and realized that character special device is not supported in filetype despite already being implemented. This adds it back.

feat: support char device in filetype

---

yazi-config/src/keymap/keymap.rs
yazi-config/src/theme/icon.rs

Add `prepend_rules` and `append_rules` for merging custom icon rules with default rules. But didn't wrote about this feature in docs, can do it tomorrow.
Also removed TODO warnings in `keymap.rs`.
Is it okay that I use rustfmt in separate commit, should i squash it somehow?

feat: add [icon] prepend_rules and append_rules in theme.toml

---

yazi-core/src/tab/commands/escape.rs
yazi-core/src/tab/commands/select.rs
yazi-core/src/tab/commands/select_all.rs
yazi-core/src/tab/mod.rs
yazi-core/src/tab/selected.rs
yazi-core/src/tab/tab.rs
yazi-fm/src/lives/tab.rs

I implemented conflict path detection using HashMap. Using a prefix tree might also be a worthwhile option to consider.
Closes https://github.com/sxyazi/yazi/issues/688

feat: nested selection conflict detection

---

yazi-plugin/preset/ya.lua

This fixes a issue (yazi would panic) I encountered when calling an async plugin that uses `ya.sync` synchronously, which happened because I was creating a `setup` function for a plugin.

fix: allow running `ya.sync` in a sync plugin call

---

yazi-fm/src/app/app.rs
yazi-fm/src/logs.rs
yazi-fm/src/main.rs

As we talked in https://github.com/sxyazi/yazi/issues/703#issuecomment-1954797994 this PR makes it so that the logs are initialized in the beginning of the application.
I made it run right after the `yazi_config::init();` because I'm not sure if there's any log that might occur if any error ever happens when initializing `yazy_core` or the `yazi_scheduler`.

fix: initialize logs right after configurations

---

.github/workflows/cachix.yml

First time setting cachix up, not sure if I'm doing anything wrong. I used the following resources for reference:
- https://github.com/helix-editor/helix/blob/master/.github/workflows/cachix.yml
- https://nix.dev/tutorials/nixos/continuous-integration-github-actions
You now need to set up the secrets, which can only be done by someone with the right privileges. Here are the steps from the official tutorial:
> ### 1. Creating your first binary cache
> 
> It's recommended to have different binary caches per team, depending who will have write/read access to it.
> 
> Fill out the form on the [create binary cache](https://app.cachix.org/cache) page.
> 
> On your freshly created binary cache, follow the **Push binaries** tab instructions.
> 
> ### 2. Setting up secrets
> 
> On your GitHub …

ci: add cachix workflow

---

.github/workflows/cachix.yml

Whoops, looks like I messed up the syntax. The job is currently stuck on `Waiting for a runner to pick up this job...`, because I'm not using the `runs-on` property correctly.
You need to use a matrix if you want the job to be run by multiple runners.

ci: fix erroneous usage of runs-on in the cachix workflow

---

yazi-config/preset/yazi.toml
yazi-core/src/manager/commands/open.rs
yazi-core/src/manager/commands/rename.rs
yazi-core/src/manager/manager.rs
yazi-core/src/tab/commands/shell.rs
yazi-core/src/tab/tab.rs
yazi-core/src/tasks/commands/mod.rs
yazi-core/src/tasks/commands/open_with.rs
yazi-core/src/tasks/tasks.rs
yazi-fm/src/executor.rs
yazi-plugin/src/external/shell.rs

Closes #716 
New function `hovered_and_selected`.

feat: add hovered as `$0` for shell and opener

---

yazi-boot/src/boot.rs
yazi-config/preset/theme.toml
yazi-config/src/lib.rs
yazi-config/src/preset.rs
yazi-config/src/preview/preview.rs
yazi-config/src/theme/flavor.rs
yazi-config/src/theme/mod.rs
yazi-config/src/theme/theme.rs
yazi-core/src/lib.rs
yazi-fm/src/logs.rs
yazi-shared/src/ro_cell.rs
yazi-shared/src/xdg.rs

Docs here https://yazi-rs.github.io/docs/flavors/overview

feat: flavor

---

yazi-plugin/preset/plugins/mime.lua

The `mime` plugin shall use `YAZI_FILE_CMD_PATH` to check mime type, if that environment variable does not exist, it call `file` directly.
This PR benefits mostly Windows users. Currently, Windows users have to add `Git\usr\bin` to PATH. But aside from the `file` command, this also add a lot more commands (`ls`, `less`, `cp`...). Those commands have conflicting names with Powershell or Nushell commands and can cause undesirable behavior.
The solution is to give yazi the path of `file` command via some form of configuration. Considering that `mime` is a lua plugin, an environment variable config is easier to implement.
**Note**: If this PR is accepted, we need to update the doc, but I can't find where it is.

feat: support `YAZI_FILE_ONE` environment variable for `file(1)` path

---

yazi-core/src/manager/commands/create.rs

On Windows, I have to use `\` for folder creation but this character is hard to type. So, for convenient sake, let's allow both `/` and `\` just in folder creation.

feat: allow both `/` and `\` in folder creation

---

.github/workflows/cachix.yml
.github/workflows/release.yml
scripts/build.sh

Hopefully resolves #723 - adds two targets to the release matrix of Actions Workflow.
I also changed conditional for adding targets via `rustup target add` to happen for every target - mainly for consistency, but also because `fromJson` clause becomes more and more lengthy. I'm also open for discussion whether this step should actually happen at all, I haven't seen it in other Rust repos.
Cheers!

feat: add musl linux build targets

---

yazi-config/preset/keymap.toml
yazi-config/preset/theme.toml
yazi-config/preset/yazi.toml
yazi-config/src/keymap/control.rs
yazi-config/src/keymap/cow.rs
yazi-config/src/keymap/mod.rs
yazi-config/src/keymap/run.rs
yazi-config/src/open/opener.rs
yazi-config/src/plugin/mod.rs
yazi-config/src/plugin/plugin.rs
yazi-config/src/plugin/rule.rs
yazi-config/src/plugin/run.rs
yazi-config/src/theme/theme.rs
yazi-core/src/manager/commands/rename.rs
yazi-core/src/tab/commands/select_all.rs
yazi-core/src/tab/commands/shell.rs
yazi-core/src/tab/selected.rs
yazi-core/src/which/sorter.rs
yazi-fm/src/app/app.rs
yazi-fm/src/help/bindings.rs
yazi-fm/src/main.rs
yazi-fm/src/which/cand.rs
yazi-plugin/src/bindings/position.rs
yazi-plugin/src/utils/layer.rs
yazi-scheduler/src/scheduler.rs

This PR adds a new `run` attribute with the intention of eventually replacing the existing `exec`, this will be a slow and gentle process, possibly happening in the next major version Yazi v0.3.
While **the existing `exec` remains available**, so it won't affect existing users. By changing `exec` to `run` in the default configuration, new users are encouraged to use the new `run` instead of `exec` when copying the default configuration.

refactor: add new `run` property

---

yazi-config/preset/keymap.toml

In Vim, Ctrl + [ is an alternative to using the <Esc> key and behaves exactly the same way. This pull request adds that functionality to Yazi.
Also added ^ as a key to move to the beginning of the line, like in Vim. This is a little inaccurate as in Vim, the ^ key moves to the first non-whitespace character in a line, not to the beginning of the line, but I think for the use cases in Yazi, the ^ key being the same as the 0 key shouldn't be much of an issue.

feat: add `Ctrl-[` as an escape key

---

yazi-config/preset/keymap.toml

Particularly, <kbd>Ctrl</kbd> + <kbd>n</kbd> and <kbd>Ctrl</kbd> + <kbd>p</kbd> to move down and up the completion menu respectively.
Closes #778

feat: add `<C-p>` and `<C-n>` to the select component for moving the cursor up/down

---

.github/ISSUE_TEMPLATE/bug.yml
scripts/publish.sh
yazi-fm/src/signals.rs

Fixes https://github.com/sxyazi/yazi/issues/796

fix: respond to the `SIGTERM` signal even when Yazi is in the background and has passed control of the terminal to the spawned process

---

yazi-core/src/notify/message.rs

Fixes #822 by fixing the width division calculation (`+1`) and taking lines within the message content itself into account

fix: adjust calculation for number of lines in a notification message

---

yazi-fm/src/logs.rs

fix: disable ANSI encoding for formatted events for the `tracing_subscriber` to clean up the logs

---

yazi-adaptor/src/emulator.rs

Fixes https://github.com/sxyazi/yazi/issues/844

fix: Windows `cmd.exe` not responding to correct CSI sequences due to ConPTY

---

yazi-adaptor/src/emulator.rs
yazi-adaptor/src/iterm2.rs
yazi-adaptor/src/kitty.rs
yazi-adaptor/src/kitty_old.rs
yazi-adaptor/src/sixel.rs
yazi-core/src/clipboard.rs
yazi-core/src/tab/selected.rs
yazi-core/src/tasks/commands/inspect.rs
yazi-fm/src/app/commands/render.rs
yazi-shared/src/term/cursor.rs
yazi-shared/src/term/term.rs

This PR fixes a performance regression introduced by the latest main branch. Recently, Yazi switched from `stdout` to `stderr`, but since `stderr` is unbuffered (previously `stdout` was line-buffered, i.e. `LineWriter`), this change caused a decrease in rendering frame rate. 
This PR adds a block buffer ( `BufWriter`) to `stderr`, while solving this performance regression, it *theoretically* can further improve performance - this is an example comparing `LineWriter` and `BufWriter`, https://github.com/orhun/rust-stdout-vs-stderr
(Image source: https://github.com/orhun/rust-stdout-vs-stderr)

perf: add `BufWriter` to `Stderr` to avoid frequent system calls and increase rendering frame rate

---

yazi-config/src/lib.rs
yazi-config/src/preset.rs
yazi-fm/src/main.rs

See commit message for the new error message.
For more information see issue GH-847. Closes https://github.com/sxyazi/yazi/issues/847
Because this is my first pull request in yazi, I've tried to keep it as minimal as possible. Here are some things I noticed while working on this issue:
- Only one file is parsed at a time, this means the user does not get information about `keymap.toml`, if `yazi.toml` has an error.
- No unit test was written for the new functionality. I would need some pointers, if this is needed.
- If `yazi.toml` is valid, but contains an unknown key, then the key appears to silently omitted.
```
[manager]
sortt_by = "natural"
```
- If `yazi.toml` could not be read, due to an IO error, then the file is silently omitted.
- It looks like there is some slight shotgun …

feat: readable toml parsing error

---

yazi-core/src/completion/commands/trigger.rs
yazi-core/src/input/commands/complete.rs

Fix some issues described in #782:
- Trigger completion with both `/` and `\`.
- Normalized path with `MAIN_SEPARATOR` when pressing `tab` for completion.
I've implemented them in Windows specific code. Because Linux apparently allows `\` in file name.

feat: trigger path completion with both `/` and `\` on Windows

---

yazi-core/src/manager/commands/tab_create.rs

Closes https://github.com/sxyazi/yazi/issues/912

feat: allow creating a tab with the startup directory when the `tab_create` command is called without specifying a `path` parameter

---

yazi-core/src/manager/commands/open.rs

This commit fixes a bug where the user was unable to open a file interactively using when the `--chosen-file` flag was used.
This is provided by default in yazi for the `O` (capital o) keybinding.
(keymap.toml)
```toml
[manager]
keymap = [
{ on = [ "O", ], run = "open --interactive", desc = "Open the selected files interactively" },
]
```
This came to me today as a question from a user in https://github.com/mikavilpas/yazi.nvim/issues/30

fix: allow opening interactively with the --chosen-file flag

---

yazi-plugin/preset/components/status.lua

Vim shows Top at the top of a file (which yazi already does) and Bot at the bottom. This change makes the Bot at the bottom also happen.

feat: change status bar percent at 100 to Bot

---

yazi-scheduler/src/file/file.rs
yazi-scheduler/src/scheduler.rs

Closes #894 
Just the first approach I could think of but let me know if you had something else in mind.
Edit: Figured out a much easier way - did not know about `path.startswith` haha

fix: prevent pasting a directory into itself

---

yazi-dds/Cargo.toml
yazi-fm/Cargo.toml
yazi-plugin/Cargo.toml
yazi-proxy/Cargo.toml

Still defaults to vendored lua, but that can be overridden by using `--no-default-features`

feat: allow building with the system Lua

---

scripts/publish.sh
yazi-shared/Cargo.toml
yazi-shared/src/fs/path.rs
yazi-shared/src/lib.rs

Resolves https://github.com/sxyazi/yazi/issues/939

feat: support expanding Windows paths like "D:" that only have a drive letter but no root

---

yazi-core/src/manager/commands/bulk_rename.rs
yazi-dds/src/body/body.rs
yazi-dds/src/body/bulk.rs
yazi-dds/src/pubsub.rs

This makes bulk renaming send one event per rename, exactly how the existing rename events are sent.
https://github.com/sxyazi/yazi/assets/300791/b43ef535-a38d-46cc-9055-241ef4bc12d1
I have a couple of ideas related to bulk renaming that I want to explore in neovim. I think I'll open an issue for discussion separately.

feat: add new `bulk` event kind to DDS

---

yazi-config/src/preview/preview.rs

Fixes https://github.com/sxyazi/yazi/issues/947

fix: always create XDG cache directory even if user has set a custom one

---

yazi-config/preset/theme.toml

Adds support for [Opus audio format](https://en.m.wikipedia.org/wiki/Opus_(audio_format)).Opus is widely used and has replaced mp3 in many places.

feat: add `*.opus` file icon

---

yazi-config/preset/theme.toml
yazi-plugin/preset/components/file.lua

This adds rules for empty files, links and executables.
Coloring is based on [eza's default theme](https://github.com/eza-community/eza/blob/main/src/theme/default_theme.rs). This also seems to be a default across  terminal file managers.

feat: add more rules to `[filetype]` and `[icon]`

---

yazi-shared/src/fs/cha.rs

Issue https://github.com/rust-lang/rust/issues/108277 has been resolved and https://github.com/rust-lang/rust/pull/114038 is released with rust 1.78.0 on May 2nd, this revision allows `h.cha.created` usage, e.g.:
```lua
function Status:date()
local h = cx.active.current.hovered
if not h then
return ui.Span('')
end
local spans = {}
local show = {
modified = { 'm', 'yellow' },
created  = { 'c', 'green' },
accessed = { 'a', 'blue' },
}
for key, display in pairs(show) do
if h.cha[key] ~= nil and h.cha[key] then
local time = ya.round(h.cha[key])
local ok, fmt = pcall(os.date, '%Y-%m-%d %H:%M', time)
if ok then
table.insert(spans, ui.Span(display[1] .. ' '))
table.insert(spans, ui.Span(fmt .. ' '):fg(display[2]))
end
end
end
return ui.Line(spans)
end
```

feat: re-enable the file `created` attribute

---

yazi-shared/src/fs/cha.rs

There was a bug in Rust versions before 1.78.0 that caused a crash when trying to get the creation time of a file.
Rust team recently released version 1.78.0 which fixes this bug, so in PR https://github.com/sxyazi/yazi/pull/987 we have re-enabled the creation time.
But the archlinuxcn repository currently [does not support the latest Rust](https://github.com/sxyazi/yazi/issues/990#issuecomment-2090847809) version, so let's temporarily disable it for now.
Fixes https://github.com/sxyazi/yazi/issues/990
CC @rafi

fix: temporarily disable the file creation time until Rust v1.78.0 becomes popular

---

yazi-core/src/manager/commands/quit.rs
yazi-core/src/tasks/commands/cancel.rs
yazi-core/src/tasks/commands/inspect.rs
yazi-core/src/tasks/tasks.rs

Resolves https://github.com/sxyazi/yazi/issues/993

feat: close confirmation prompts and exit automatically when the ongoing task gone

---

yazi-cli/Cargo.toml
yazi-fm/Cargo.toml

This will enable binstall installs work directly from github. Required for raspberry pi.
This is needed since crate name is `yazi-fm` but the archive files are named `yazi-`

feat: support `cargo binstall yazi-fm` and `cargo binstall yazi-cli`

---

yazi-boot/src/boot.rs

Solves https://github.com/sxyazi/yazi/issues/995
Example output:
```sh
Yazi
Version: 0.2.5 (aee65bc 2024-05-04)
OS: macos-aarch64 (unix)
Debug: true
Ya
Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "ya 0.2.5\n", stderr: "" })
Emulator
Emulator.via_env: ("xterm-256color", "WezTerm")
Emulator.via_csi: Ok(WezTerm)
Emulator.detect: WezTerm
...
```

feat: yazi --debug shows `ya` version in its output

---

yazi-plugin/src/utils/target.rs

As of [this blog post](https://blog.rust-lang.org/2024/05/06/check-cfg.html), rust nightly checks `cfg` annotations to make sure they are valid and actually refer to a real cfg. Using one of the recent versions of nightly, I started to get warnings that `cfg(wasm)` isn't a real cfg, so this config prevents compilation of that block in all instances. 
In this PR, I fixed it to actually only compile under wasm, as per [the reference on conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html)

fix: correct wasm target condition

---

yazi-adaptor/src/emulator.rs

Fixes #1026.
I confirmed that <code>cargo build --release && target/release/yazi</code> and pressing <kbd>q</kbd> to exit no longer leaves characters on the next line.
`target/release/yazi --debug >/dev/null` still does, but I think that is intentional and fine. The `--debug` output contains:
```console
...
Emulator
Emulator.via_env: ("rxvt-unicode-256color", "")
Emulator.via_csi: Ok(Unknown([]))
Emulator.detect: Urxvt
...
```
According to https://www.arewesixelyet.com/#urxvt, SIXEL graphics format is not supported by this terminal emulator, but I wasn't sure how to determine whether Adaptor::Iterm2 would be supported.

fix: recognize `TERM=rxvt-unicode-256color`

---

yazi-core/src/input/commands/kill.rs
yazi-core/src/input/input.rs
yazi-plugin/src/process/child.rs
yazi-plugin/src/process/command.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1030
Closes https://github.com/sxyazi/yazi/issues/1030
```lua
local echo = Command("echo"):arg("Hello"):stdout(Command.PIPED):spawn()
local rev = Command("rev"):stdin(echo:take_stdout()):stdout(Command.PIPED):output()
ya.err(rev.stdout) -- "olleH\n"
```

feat: support `stdin` and pipe for `Child` API

---

.github/workflows/check.yml
.styluaignore
stylua.toml

This commit adds a GitHub Actions workflow that checks the lua files against the yazi lua coding style.
The workflow uses the `stylua` tool, which can be installed using cargo:
```sh
cargo install stylua --features lua54
```
I picked the options for the formatter in a way that forced minimal changes to the existing style.
<https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options>

ci: consistently enforce Lua coding style

---

.github/workflows/test.yml

The current test command `cargo test --verbose` does not account for running tests in the nested cargo modules. A simple change to `cargo test --all --verbose` fixes that issue.
Without `--all`:
```console
Running `/home/runner/work/yazi/yazi/target/debug/deps/ya-2ddc42514f24a284`
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running `/home/runner/work/yazi/yazi/target/debug/deps/yazi-b4da7ef94736c14f`
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
With `--all`:
```console
Running unittests src/lib.rs (target/debug/deps/yazi_adaptor-3992d172dc5e1838)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s …
```

ci: fix cargo unit tests execution

---

yazi-plugin/src/external/fd.rs
yazi-plugin/src/external/rg.rs

When `yazi`'s `hidden` option is true, it passes `--no-ignore` to `fd` and `rg`. However, ignore files have no actual relation to hidden files. They often contain entries like `node_modules` that users want to ignore in all situations.
Example use case: In a code project, I turn on the `hidden` option to navigate to configuration files like `.editorconfig` and search their contents with <kbd>S</kbd>. I do not want the `hidden` option to expose thousands of search results in `node_modules`, `.gocache`, or `dist`.

fix: remove `ignore` options from `rg` and `fd` search

---

Cargo.lock
yazi-adaptor/Cargo.toml
yazi-adaptor/src/adaptor.rs
yazi-adaptor/src/chafa.rs
yazi-adaptor/src/image.rs
yazi-adaptor/src/iterm2.rs
yazi-adaptor/src/kitty.rs
yazi-adaptor/src/kitty_old.rs
yazi-adaptor/src/lib.rs
yazi-adaptor/src/sixel.rs
yazi-adaptor/src/ueberzug.rs
yazi-plugin/src/utils/image.rs

In previous versions, Yazi has been using Chafa provided by Überzug++ with the aim of minimizing external dependencies installed by users.
However, in practice, Überzug++ is not always available. It needs to obtain the pixel dimensions of the terminal when starting up, and in some terminal/desktop environments, it fails to do so, this results in Überzug++ [crashing on startup](https://github.com/jstkdng/ueberzugpp/issues/172), and is also not available on Windows.
But Chafa does not have these issues, so in Yazi v0.3, Chafa is added as an ***optional*** dependency and takes over ASCII art preview.
Also resolves https://github.com/sxyazi/yazi/issues/777

feat: Chafa integration

---

yazi-adaptor/src/iterm2.rs
yazi-config/src/keymap/key.rs
yazi-core/src/help/help.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1065
Closes https://github.com/sxyazi/yazi/issues/1065

feat: support Super/Command/Windows key notation `D-`

---

yazi-config/preset/keymap.toml

Fixes https://github.com/sxyazi/yazi/issues/1072

fix: remove the default keybinding for going to the temporary directory

---

yazi-config/preset/keymap.toml
yazi-config/preset/yazi.toml
yazi-config/src/open/open.rs
yazi-config/src/open/rule.rs
yazi-config/src/theme/icons.rs
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/fzf.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/mime.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/preset/plugins/zoxide.lua
yazi-plugin/src/bindings/cha.rs
yazi-plugin/src/process/status.rs

```diff
local status = Command("ls"):spawn():wait()
- ya.err("success:", status:success(), "code:", status:code())
+ ya.err("success:", status.success, "code:", status.code)
```
- `is_block_device` => `is_block`
- `is_char_device` => `is_char`
- `is_socket` => `is_sock`

refactor!: v0.3 API changes

---

yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-cli/src/package/parser.rs

Add `-l`, `--list` flags to the `ya` `pack` command.
It prints a list of the currently installed packages as specified in the `package.toml` file.
Result:
```
ya pack --list
plugin:
dedukun/relative-motions
DreamMaoMao/mime
flavor:
```
```
ya pack --help
Manage packages
Usage: ya pack [OPTIONS]
Options:
-a, --add <ADD>  Add a package
-i, --install    Install all packages
-l, --list       List all installed packages
-u, --upgrade    Upgrade all packages
-h, --help       Print help
```
The implementation is probably very naive. I'm open to any feedback.

feat: add `pack --list` subcommand to Ya CLI

---

Cargo.lock
yazi-adaptor/Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-core/src/tab/commands/escape.rs
yazi-dds/Cargo.toml
yazi-dds/build.rs
yazi-dds/src/body/body.rs
yazi-dds/src/body/bye.rs
yazi-dds/src/body/hey.rs
yazi-dds/src/body/hi.rs
yazi-dds/src/client.rs
yazi-dds/src/server.rs
yazi-fm/Cargo.toml
yazi-plugin/Cargo.toml
yazi-proxy/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-shared/Cargo.toml

This PR also simplifies the parameters for `ya pub`:
- Now you can omit the body, meaning an empty body is allowed. This allows:
```bash
ya pub "$YAZI_ID" dds-test -str ""
```
to be written as:
```bash
ya pub "$YAZI_ID" dds-test
```
- Now you can omit the receiver. When the receiver is not specified, it uses the value from the environment variable `YAZI_ID`. This allows:
```bash
ya pub "$YAZI_ID" dds-test
```
to be written as:
```bash
ya pub dds-test
ya pub dds-test "$YAZI_ID"
```
Note: To achieve this, the receiver has been moved from the first parameter to the second parameter, i.e., `ya pub <receiver> <kind>` becomes `ya pub <kind> <receiver>`. 
This is a breaking change in Yazi v0.3. `ya pub` was added in the previous version, so the amount of code broken by this is reasonably small. …

feat!: DDS client-server version check

---

Cargo.lock
README.md
nix/yazi-unwrapped.nix
yazi-boot/Cargo.toml
yazi-boot/src/boot.rs
yazi-fm/src/components/current.rs
yazi-fm/src/components/header.rs
yazi-fm/src/components/parent.rs
yazi-fm/src/components/preview.rs
yazi-fm/src/components/status.rs
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/magick.lua

Fixes #1104
I made it so that it would print Nill if the user doesn't have that dependency and the version otherwise
Here is a sample output after changes:
Yazi
Version: 0.2.5 (0b2089b 2024-06-02)
OS: linux-x86_64 (unix)
Debug: true
Ya
Version: Ok("ya 0.2.5\n")
Emulator
Emulator.via_env: ("alacritty", "")
Emulator.via_csi: Ok(Unknown([]))
Emulator.detect: Unknown([])
Adaptor
Adaptor.matches: X11
Desktop
XDG_SESSION_TYPE: Some("x11")
WAYLAND_DISPLAY: None
DISPLAY: Some(":0")
SSH
shared.in_ssh_connection: false
WSL
/proc/sys/fs/binfmt_misc/WSLInterop: false
Variables
SHELL: Some("/usr/bin/zsh")
EDITOR: Some("nvim")
ZELLIJ_SESSION_NAME: None
YAZI_FILE_ONE: None
YAZI_CONFIG_HOME: None
file(1)
Version: Ok("file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n")
Text …

feat: add some dependency version information to `yazi --debug`

---

Cargo.lock
yazi-cli/Cargo.toml
yazi-config/Cargo.toml
yazi-config/preset/yazi.toml
yazi-core/Cargo.toml
yazi-fm/src/signals.rs
yazi-plugin/Cargo.toml
yazi-scheduler/src/process/shell.rs

Fixes https://github.com/sxyazi/yazi/issues/1130

fix: block `SIGINT` signal from the spawned subprocess

---

yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-dds/src/body/body.rs
yazi-dds/src/client.rs
yazi-dds/src/payload.rs
yazi-dds/src/pubsub.rs
yazi-dds/src/server.rs
yazi-dds/src/state.rs
yazi-plugin/preset/plugins/session.lua
yazi-plugin/src/pubsub/pubsub.rs

In practice, the `severity` of static messages has proven to be meaningless and increases protocol complexity.
This PR replacing `severity` with `sender` to resolves https://github.com/sxyazi/yazi/pull/1004#discussion_r1596707396
This PR removes the `ps.pub_static()` method and replaces it with `ps.pub_to()`:
```diff
- ps.pub_static(10, "greeting", "Hello, World!")
+ ps.pub_to(0, "@greeting", "Hello, World!")
```
Messages with a `kind` that starts with `@` indicate they are static messages. Accordingly, `ps.sub_remote()` subscribes to static messages using that kind:
```diff
- ps.sub_remote("greeting", function() end)
+ ps.sub_remote("@greeting", function() end)
```
The `ya pub-static` command has also been removed and replaced with `ya pub`:
```diff
- ya pub-static 10 "greeting" --str …
```

feat!: include the `sender` ID in static messages

---

yazi-core/src/manager/commands/hover.rs
yazi-core/src/tab/commands/arrow.rs
yazi-core/src/tab/commands/cd.rs

Original issue here: https://github.com/sxyazi/yazi/issues/1186
Fixed the issue by add `pub_from_hover` in `cd` command.

fix: accommodate all `hover` events for DDS

---

yazi-config/preset/yazi.toml
yazi-core/src/manager/commands/remove.rs
yazi-core/src/manager/commands/rename.rs
yazi-plugin/preset/plugins/archive.lua

This allows users to only rename or remove the currently hovered file.
Fixes #1226

feat: add `--hovered` option to the `rename` and `remove` commands

---

yazi-config/preset/keymap.toml
yazi-plugin/preset/components/folder.lua
yazi-plugin/src/cha/cha.rs

Allowed uid and gid to be called on windows. When uid or gid is called on Windows it will return nil. This is similar to how "permissions" works.
This is a continuation of #932 I decided to not support ownership on Windows and instead have the same behaviour as permissions, which is to have the keybind do nothing.
Additionally added #[allow(unused_variables)] to permissions in order to suppress compiler warnings for unused variable "me" when compiling on Windows.

feat: ownership linemode

---

yazi-config/src/keymap/control.rs
yazi-config/src/lib.rs
yazi-core/src/tab/commands/shell.rs

I hit an issue in my config and found the existing migration error messages slightly confusing.
My issue was that I had key bindings using `--interactive` and `--block` at the same time, which seems to be disallowed in v0.3.
https://github.com/mikavilpas/dotfiles/commit/d2c8040760e49bf74d29c62390f4ca8be1b488a9

feat: help users migrate shell key bindings to v0.3

---

Cargo.lock
yazi-adapter/src/lib.rs
yazi-boot/src/actions/actions.rs
yazi-boot/src/actions/clear_cache.rs
yazi-boot/src/actions/debug.rs
yazi-boot/src/actions/mod.rs
yazi-boot/src/actions/version.rs
yazi-boot/src/args.rs
yazi-boot/src/boot.rs
yazi-boot/src/lib.rs
yazi-cli/Cargo.toml
yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-config/src/lib.rs
yazi-core/src/lib.rs
yazi-dds/src/lib.rs
yazi-dds/src/pump.rs
yazi-plugin/src/lib.rs
yazi-plugin/src/loader/mod.rs

As discussed in
https://github.com/sxyazi/yazi/issues/989#issuecomment-2231468495, this will allow applications embedding yazi to set the YAZI_ID environment variable to a known value. Afterwards, the application can use this id with `ya pub` to publish messages to the specific yazi instance.
Here's a quick demo from yazi.nvim. I generate the id based on the current time, and added a notification for the demo. In yazi, I open a shell to see the id.
https://github.com/user-attachments/assets/7b1f3c87-7622-4b50-9e90-66873f9c7e0d

feat: allow setting `YAZI_ID` as a command line argument

---

yazi-dds/src/body/delete.rs
yazi-dds/src/body/trash.rs
yazi-fm/src/lives/lives.rs
yazi-shared/src/ro_cell.rs

Clippy showed these warnings before this commit
```
warning: you should consider adding a `Default` implementation for `RoCell<T>`
--> yazi-shared/src/ro_cell.rs:12:2
|
12 |     pub const fn new() -> Self { Self(UnsafeCell::new(None)) }
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
= note: `#[warn(clippy::new_without_default)]` on by default
help: try adding this
|
10 + impl<T> Default for RoCell<T> {
11 +     fn default() -> Self {
12 +         Self::new()
13 +     }
14 + }
|
warning: useless conversion to the same type: `image::ColorType`
--> yazi-adapter/src/image.rs:43:5
|
43 |                 img.color().into(),
|                 ^^^^^^^^^^^^^^^^^^ …
```

refactor: fix Clippy warnings

---

Cargo.lock
yazi-config/Cargo.toml
yazi-config/src/keymap/control.rs
yazi-fm/src/help/bindings.rs

Fixes https://github.com/sxyazi/yazi/issues/1342

fix: help menu multi-line text rendering

---

yazi-core/src/manager/watcher.rs

Fixes https://github.com/sxyazi/yazi/issues/1313
The retrun is_ok from to_unwatch a `deleted path` is always false. 
But the directory has actually been unwatch, because the return is false, so it was not actively removed from the `WATCHED`, 
so when the same name path is created, the path recognize as a watching path in  `old` var.  
so the new path with the same name will not add to the `to_watch` to rewatcher.

fix: can't rewatch a directory that has been deleted once before

---

flake.nix
nix/yazi-unwrapped.nix

Similar to my recent https://github.com/NixOS/nixpkgs/pull/330520 (but without the need for https://github.com/NixOS/nixpkgs/pull/330619 since this is entirely automatic). Changes the `yazi --version` output from the not-so-helpful `Yazi 0.2.5 (VERGEN_IDEMPOTENT_OUTPUT 1980-01-01)` to `Yazi 0.2.5 (cdb34de 2024-07-31)`.

feat(nix): set `VERGEN_*` build env vars

---

flake.nix
nix/shell.nix
nix/yazi-unwrapped.nix
nix/yazi.nix

Cleans up the code with the `statix` and `deadnix` tools, and switches the formatter to `nixfmt-rfc-style`.

refactor(nix): cleanup and switch to `nixfmt-rfc-style`

---

yazi-scheduler/src/file/file.rs

fix: android building error caused by `trash` crate

---

scripts/publish.sh
yazi-config/preset/keymap.toml
yazi-config/src/keymap/keymap.rs
yazi-core/src/help/commands/escape.rs
yazi-core/src/help/help.rs
yazi-fm/src/help/layout.rs

This is a follow up to https://github.com/sxyazi/yazi/pull/1360 conversation in attempt to get users more familiar with filtering help items feature.
[simplescreenrecorder-2024-07-27_23.35.40.webm](https://github.com/user-attachments/assets/d08d35b6-3b09-40d7-8f95-ae663638bf01)
It will work correctly in case if a user overrides it with combination of keys like that:
By default filtering key changed to `f` for consistency with manager keymap

feat: add filtering tip in help component

---

yazi-config/preset/yazi.toml
yazi-config/src/manager/manager.rs
yazi-core/src/manager/commands/refresh.rs
yazi-fm/src/term.rs

This PR introduces an `update_title` manager config option, which controls whether Yazi updates the terminal title using ANSI escape sequences. For some users, this behavior is undesirable since:
1. Yazi may be invoked within another process (like Vim). If Yazi updates the terminal title, it overrides the title set by / for the parent process.
2. Users may have their own mechanisms or preferences for setting the terminal title and may not want it overridden.
Apologies that this feature request is a PR and not an issue, but I was eager to experiment with Rust. :) Happy to have it closed in favor of another implementation.
Closes https://github.com/sxyazi/yazi/issues/1350

feat: add `title_format` manager config option

---

Cargo.lock
Cargo.toml
yazi-adapter/Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-config/Cargo.toml
yazi-config/preset/yazi.toml
yazi-core/Cargo.toml
yazi-dds/Cargo.toml
yazi-fm/Cargo.toml
yazi-fs/Cargo.toml
yazi-plugin/Cargo.toml
yazi-proxy/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-shared/Cargo.toml

It's easier to keep versions in sync across the entire workspace this way.

chore: move common dependencies to workspace Cargo.toml

---

yazi-adapter/src/image.rs

Fixes #1383.
Image precache uses jpeg which does not support alpha channel, and the latest version of the image crate removed the silent drop. (See [this issue](https://github.com/image-rs/image/issues/2211)).

fix: precache for images with alpha

---

.github/workflows/draft.yml

Named after and hopefully resolving #1382
Changes include:
- workflow running at a cron schedule (12:00 AM / 00:00 UTC)
- workflow scheduled by cron runs `nightly` job, generating a pre-release
Nightly build name is `yazi-nightly-<timestamp>`. Flow tested with dummy artifact created:
https://github.com/uznog/yazi/actions/runs/10215675482
And here's the resulting pre-release: https://github.com/uznog/yazi/releases/tag/yazi-nightly-20240802-1236

feat: Add automatic nightly builds to the Github Actions workflow

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
README.md
yazi-adapter/src/adapter.rs
yazi-adapter/src/emulator.rs
yazi-config/src/preview/preview.rs
yazi-fm/src/input/input.rs
yazi-plugin/preset/components/status.lua
yazi-plugin/src/external/highlighter.rs

Ghostty now supports [kitty unicode placeholders](https://github.com/ghostty-org/ghostty/pull/2015), it's the first terminal I know of besides kitty itself to implement this feature. Much respect!

feat: switch to kitty unicode placeholders for Ghostty image previewing

---

yazi-shared/src/fs/path.rs

Fix #1416
But I still have a question: when `current_cwd()` returns `None`, the code executes the first closure and returns `p`, but `p` is not an absolute path. I can't figure out how to solve this in this scenario.

fix: resolve relative path when expanding path

---

flake.lock
flake.nix
nix/shell.nix
nix/yazi-unwrapped.nix
nix/yazi.nix

changes and why:
- drop flake-utils: flake-utils was removed from rust-overlay, so pulling it in only to do something that a function could do seems uneeded
- sync "yazi" to be more in sync with upstream
- add "?" to "constructed" args since the ordinary `callPackage` won't pass these args
- remove the last `rec` this is following upstreams nixpkgs pattern on this pattern
- use `prev.stdenv.system` over `final.system` since users can disable aliases, we also have no need to use the final specifically either so `prev` makes more sense
-`shell.nix` is now constructed via `yazi-unwrapped.nix` meaning all dependencies are transfered, reducing some repetion

refactor(nix): home keeping

---

flake.lock
flake.nix

fix from https://github.com/sxyazi/yazi/pull/1380#issuecomment-2276039515

fix(nix): pin `rust-overlay` to workaround `cargo-c`

---

yazi-core/src/tab/commands/shell.rs
yazi-proxy/src/app.rs

Add a `cursor` option to `shell` command, similar to `rename`.
This allows user to define keymaps with cursor set to generic place, so that they don't have to manually move the cursor every time. When the option is unspecified the behavior is same as before (at the end).
Some examples:
```
[manager]
prepend_keymap = [
{ on = [ ":" ], run = 'shell --block --interactive "vim $@"' },
{ on = [ ":" ], run = 'shell --block --interactive --cursor=start "$@"' },
{ on = [ ":" ], run = 'shell --block --interactive --cursor=7 "command $@"' },
]
```
`--cursor=start` is equivalent to `--cursor=0`. I added it here because it is supported by rename already. There could be some extra variants like `after_first`, `before_last` if necessary. `--cursor=<usize>` is sufficient for most cases.

feat: add `cursor` option to the `shell` command

---

yazi-plugin/src/process/child.rs

Fixes https://github.com/sxyazi/yazi/issues/1463

fix: close stdin before waiting for child process

---

yazi-core/src/manager/commands/hover.rs
yazi-plugin/preset/plugins/archive.lua

Fixes https://github.com/sxyazi/yazi/issues/1465
Also fixes https://github.com/sxyazi/yazi/issues/1466

fix: 7zip shows different error messages for RAR and ZIP files

---

yazi-cli/src/main.rs
yazi-cli/src/package/add.rs
yazi-cli/src/package/git.rs
yazi-cli/src/package/install.rs
yazi-cli/src/package/package.rs
yazi-cli/src/package/parser.rs
yazi-cli/src/package/upgrade.rs
yazi-core/src/completion/commands/show.rs

Fixes https://github.com/sxyazi/yazi/issues/1471
When users use `#`, a warning will appear encouraging them to use `:`, but `#` is still usable.

fix: replace `#` with `:` to resolve the problem where certain shells recognize it as a special character

---

yazi-boot/src/actions/debug.rs
yazi-core/src/manager/commands/tab_switch.rs
yazi-core/src/manager/tabs.rs
yazi-dds/src/body/body.rs
yazi-dds/src/body/mod.rs
yazi-dds/src/body/tab.rs
yazi-dds/src/payload.rs
yazi-dds/src/pubsub.rs

This is a simple suggestion on how https://github.com/sxyazi/yazi/issues/1396 could be solved - it simply sends the index of the tab that was switched to in yazi.
Example:
```js
$ ya sub tab-switch
tab-switch,0,1723480172088356,{"tab":1}
tab-switch,0,1723480172088356,{"tab":0}
```
Some observations for your consideration:
- the index in this implementation is currently 0-based while yazi displays tabs as 1-based (1-9). This seems to be what is happening inside yazi, but I'm not sure if this is okay or not.
- other tab commands seem to behave as expected (switch to tab, switch to next/previous tab, move tab, close tab all work without issues)
Closes https://github.com/sxyazi/yazi/issues/1396

feat: new `tab` DDS event on tab switch

---

yazi-config/preset/yazi.toml
yazi-config/src/preview/preview.rs
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/image.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/video.lua

I've been working on optimizing Yazi's image preview speed, and with multi-threading, preloading, and a built-in image decoder, it should already be the fastest among all terminal file managers.
However, I noticed some lag during fast scrolling and realized that at this point, the performance bottleneck isn't Yazi itself, but rather the terminal. When users scroll quickly, Yazi processes the images at a very high speed and sends them to the terminal, but the terminal can't keep up with processing them in time, which gives the impression of lag. In reality, it's not Yazi that's lagging, but the terminal.
This PR introduces a new `image_delay` configuration option to address this issue. When previewing images, it will wait at least `image_delay` milliseconds before starting to send the …

perf: new `image_delay` option debounces image previews to avoid lag caused by terminal image decoding during fast scrolling

---

yazi-core/src/manager/commands/create.rs

This simple pull request adds a new option to the 'create' command: --dir
With this option 'create' will always create a directory.
This allows you to bind 'create --dir' to a key, so you can easily create directories without having to remember to put / or \ at the end of the name.
Personally it makes sense to me to have a command for this. I very rarely need to create empty files, but I often create directories, and used to have a keybinding for this in ranger. After switching to yazi I very often forget to add the / when I want to make a directory.
I've tested this change on Linux. 'create --dir' now always creates a directory, trailing / is ignored, trailing \ is treated as part of the directory name (which is ok in Linux). Not tested on Windows, because I have no Windows machines :) …

feat: add `--dir` option to `create` command

---

scripts/build.sh

chore: set `MACOSX_DEPLOYMENT_TARGE` to 10.11 to make the binary compatible with old macOS

---

yazi-shared/src/number.rs

When calling `new` function to create a `OrderedFloat`, it shouldn't allow `NAN` type to pass in, but the issue now only allows `NAN` , which does make much sense for the logic of `OrderedFloat`.
I guess this issue hasn't been detected before is possibly because `OrderedFloat` only works on some edge cases. But anyway, it's better to make the code more robust.

fix: wrong `debug_assert` in `OrderedFloat` for NaN

---

yazi-plugin/preset/components/entity.lua
yazi-plugin/preset/plugins/code.lua
yazi-plugin/preset/plugins/empty.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/src/elements/line.rs
yazi-plugin/src/elements/paragraph.rs
yazi-plugin/src/elements/span.rs
yazi-plugin/src/elements/style.rs
yazi-plugin/src/external/highlighter.rs
yazi-plugin/src/lib.rs
yazi-plugin/src/macros.rs
yazi-plugin/src/utils/preview.rs
yazi-shared/src/errors/peek.rs

Invalid `\r` (appearing in the middle of a line and not followed by `\n`) will be replaced with `\n`, and a prompt will be given when using the `code` previewer to preview binary files, see https://github.com/sxyazi/yazi/issues/1546#issuecomment-2307986125.
This PR changes the first return value of `ya.preview_code()` from a boolean to a string. Considering that [only the second return value has been used](https://github.com/search?q=ya.preview_code%28&type=code) in practice for a long time, this change shouldn't have any impact.
Closes https://github.com/sxyazi/yazi/issues/1546

feat: make the builtin `code` previewer handle invalid carriage return chars and binary streams better

---

yazi-config/preset/yazi.toml
yazi-config/src/preview/mod.rs
yazi-config/src/preview/preview.rs
yazi-config/src/preview/wrap.rs
yazi-plugin/preset/plugins/code.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/src/elements/paragraph.rs
yazi-plugin/src/external/highlighter.rs
yazi-plugin/src/utils/preview.rs

This PR tries to add feature described in #1089 
I tried to implement feature without introducing new dependencies, like it was asked in #1142. Also I used #1142 commits as baseline to my changes (configuration from yazi.toml, highlight signature). 
I tried to separate new logic with two methods: `before_after` and `before_after_wrapped`. `before_after` is almost the same with minor change in readability `no_more_scroll`.
`before_after_wrapped` is more complicated. I had to read whole file first and apply logic afterwards. We have to decide if file is plaintext or not because we only apply indentation (tab_size in config) to plaintext files (in this method at least).
After that I chunk every line of file in chunks by column width using …

feat: word wrapping in `code` previewer

---

yazi-config/src/keymap/keymap.rs

Fixes https://discord.com/channels/1136203602898194542/1136203604076802092/1278457877249658941 reported by @Tyarel8

fix: keybindings disappear when mixing presets with a wrong filter condition

---

yazi-plugin/preset/components/entity.lua
yazi-plugin/preset/components/linemode.lua

For now the spacing of linemodes is a wild west. This change brings some uniformity - every linemode entry is followed by a space. This also means that every plugin linemode should only return text, without padding of spaces, just like builtin linemodes do.
Another path would be to add spacing parameters to children, so user can decided if certain linemodes should be padded with spaces or not.

feat: ensure that `Entity` and `Linemode` have consistent space padding

---

yazi-plugin/preset/ya.lua

This PR also removes `ya.basename` because it has [never been used](https://github.com/search?q=ya.basename&type=code) or documented, and the `Url` userdata has added a `name()` method, which is a better way to achieve the same functionality without relying on a regular expression.

feat: add `dict_merge()` function

---

yazi-adapter/src/lib.rs

Fixes https://github.com/sxyazi/yazi/issues/1624
Set `allow-passthrough` always to `all` instead of `on` to prevent overriding a user setting with a higher priority `all`.
It might be worth considering adding detection for user-defined values and moving this to a separate thread to avoid impacting Yazi's startup speed in the future, as this would involve one additional tmux process call.

fix: set `allow-passthrough` always to `all` instead of `on` to prevent overriding a user setting with a higher priority `all`

---

yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/extract.lua
yazi-plugin/src/fs/fs.rs

Close [#1548](https://github.com/sxyazi/yazi/issues/1548).
Description:
* Add `spawn_tar` function and `is_tar_compatible` function
- Create `spawn_tar` function to run command with `tar -xaf` to unzip file to tmp directory
- Create `is_tar_compatible` function to tell if a zip file can be extracted with `tar` command
* Add `os.excute()` line to make sure the tmp dir exists because `tar` command will not automatically create that dir, unlike `7z`
* Refactor the logic in the `try()` function to if the zip file can be unzipped with tar and no password required, use `tar`, otherwise use `7z` instead

feat: make the builtin `extract` plugin support compressed tarballs (`*.tar.gz`, `*.tar.bz2`, etc.)

---

yazi-config/preset/yazi.toml
yazi-config/src/lib.rs
yazi-config/src/popup/input.rs
yazi-config/src/popup/options.rs
yazi-core/src/manager/commands/create.rs

When using `create` the title will rename the same (`Create:`), but when using the new `--dir` option, it will show `Create (dir):` to show that it is different in the input prompt.

feat: change input title when using `create --dir`

---

yazi-core/src/manager/commands/bulk_rename.rs
yazi-core/src/manager/commands/create.rs
yazi-core/src/manager/commands/rename.rs
yazi-core/src/manager/commands/update_files.rs
yazi-core/src/manager/watcher.rs
yazi-core/src/manager/yanked.rs
yazi-core/src/tab/selected.rs
yazi-core/src/tasks/preload.rs
yazi-fm/src/lives/file.rs
yazi-fs/src/files.rs
yazi-fs/src/folder.rs
yazi-fs/src/sorter.rs
yazi-plugin/src/fs/fs.rs
yazi-scheduler/src/prework/prework.rs
yazi-shared/src/fs/file.rs
yazi-shared/src/fs/fns.rs
yazi-shared/src/fs/op.rs
yazi-shared/src/fs/path.rs
yazi-shared/src/fs/url.rs
yazi-shared/src/fs/urn.rs

Follow up to https://github.com/sxyazi/yazi/pull/1648
Sorting by size doesn't work, will be fixed later

perf: introduce URN to speed up large directory file updates

---

yazi-plugin/preset/plugins/json.lua
yazi-plugin/src/loader/require.rs
yazi-plugin/src/utils/sync.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1653
Closes https://github.com/sxyazi/yazi/issues/1653

feat: support calling methods in builtin plugins with arbitrary types of arguments (`self` can now be omitted)

---

Cargo.lock
Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-config/preset/keymap.toml
yazi-config/src/lib.rs
yazi-dds/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/1668
This issue was introduced in https://github.com/sxyazi/yazi/pull/1650

fix: warnings should be output to `stderr` instead of `stdout`

---

yazi-core/src/manager/commands/peek.rs
yazi-core/src/manager/commands/seek.rs
yazi-core/src/manager/commands/tab_create.rs
yazi-core/src/tab/commands/enter.rs
yazi-core/src/tab/commands/leave.rs
yazi-shared/src/fs/file.rs

Fixes https://github.com/sxyazi/yazi/issues/1683

fix: `enter` and `leave` commands should treat the search results as regular entities

---

yazi-plugin/preset/plugins/magick.lua

As the title describes it, this is an easy fix in order for the previewer to work for `xcf` and other files which handle layers. It should work as normal for non-layered files.

fix: `magick` previewer for multi-layered image files with `-flatten` argument

---

yazi-core/src/manager/commands/rename.rs
yazi-core/src/tab/commands/copy.rs
yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/empty.lua
yazi-plugin/preset/plugins/json.lua
yazi-scheduler/src/scheduler.rs

This PR makes implementing https://github.com/sxyazi/yazi/issues/1328#issuecomment-2379689321 easier — these `seek`ing behaviors are consistent, we just use the `code`'s `seek` method uniformly, so as long as the user rewrites the `code`'s, the other previewers will just work.

feat: reuse the `code` previewer seeking behavior for `json`, `archive`, and `empty`

---

yazi-adapter/src/adapter.rs
yazi-plugin/preset/plugins/video.lua

Fixes https://github.com/sxyazi/yazi/issues/1734
Also fixes https://github.com/sxyazi/yazi/issues/1611

fix: compositors not supported by Überzug Wayland layer, or WSL not with WezTerm should fallback to Chafa

---

yazi-adapter/src/emulator.rs
yazi-adapter/src/lib.rs
yazi-adapter/src/mux.rs
yazi-boot/src/actions/debug.rs
yazi-core/src/manager/commands/bulk_rename.rs
yazi-fm/src/term.rs

A Yazi side implementation of https://github.com/tmux/tmux/issues/4177
---
This PR also changes the `bulk.txt` filename to `bulk-rename.txt` used in bulk renaming, in preparation for the future `bulk-create.txt`. 
This will impect the ["Specify a different editor for bulk renaming" tip](https://yazi-rs.github.io/docs/tips#bulk-editor), but considering it was added just 4 days ago in https://github.com/yazi-rs/yazi-rs.github.io/commit/1c1671b9cdbf4d09b0aa958a5441a44d200af8e9, the impact should be reasonably small, and it will be updated accordingly.

feat: `yazi --debug` supports detecting whether `tmux` is built with `--enable-sixel`

---

yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/header.lua
yazi-plugin/preset/components/marker.lua
yazi-plugin/preset/components/progress.lua
yazi-plugin/preset/components/rail.lua
yazi-plugin/preset/components/status.lua
yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/code.lua
yazi-plugin/preset/plugins/empty.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/src/elements/bar.rs
yazi-plugin/src/elements/border.rs
yazi-plugin/src/elements/constraint.rs
yazi-plugin/src/elements/gauge.rs
yazi-plugin/src/elements/line.rs
yazi-plugin/src/elements/list.rs
yazi-plugin/src/elements/span.rs
yazi-plugin/src/elements/text.rs

Before version 0.4, `ui.List`, `ui.Bar`, `ui.Border`, and `ui.Gauge` required an `area` parameter to specify the element's position in the terminal. While this worked fine in most cases, a few issues arose:
- **Limited flexibility:** These elements could not exist independently without being tied to specific coordinates.  
- **Redundant calculations:** Coordinates had to be computed before constructing the elements, even though the same calculations are done again during rendering, impacting performance.  
- **Inflexibility with dynamic layouts:** It was difficult to apply dynamic coordinates on the Rust side. Whenever the terminal size or layout area changed, a Lua function had to be called to recalculate coordinates, as the `area` needed to be passed from the Lua side.  
This PR removes …

feat!: decouple `ui.List`, `ui.Bar`, `ui.Border`, and `ui.Gauge` from coordinates

---

yazi-adapter/src/image.rs

Currently, the `image` crate only supports ICC for WebP. 
Support for other image formats (JPEG, PNG, etc.) will be added in the future as the `image` crate is updated, to potentially address https://github.com/sxyazi/yazi/issues/1599.
See https://github.com/image-rs/image/blob/main/CHANGES.md#version-0254 for details

feat: add ICC profile to images for better color accuracy

---

yazi-core/src/manager/commands/hover.rs
yazi-core/src/manager/commands/tab_close.rs
yazi-core/src/manager/commands/tab_create.rs
yazi-core/src/manager/commands/tab_swap.rs
yazi-core/src/manager/commands/update_files.rs
yazi-core/src/manager/manager.rs
yazi-core/src/manager/tabs.rs
yazi-core/src/tab/commands/arrow.rs
yazi-core/src/tab/commands/cd.rs
yazi-core/src/tab/commands/filter_do.rs
yazi-core/src/tab/commands/hidden.rs
yazi-core/src/tab/commands/reveal.rs
yazi-core/src/tab/tab.rs
yazi-dds/src/body/cd.rs
yazi-dds/src/body/hover.rs
yazi-dds/src/pubsub.rs
yazi-fm/src/lives/tab.rs
yazi-fs/src/files.rs
yazi-plugin/src/external/highlighter.rs
yazi-proxy/src/manager.rs
yazi-shared/src/event/data.rs
yazi-shared/src/fs/op.rs
yazi-shared/src/id.rs
yazi-shared/src/lib.rs

Fixes https://github.com/sxyazi/yazi/issues/1824

fix: use a unique `Id` for each tab

---

README.md
yazi-plugin/src/cha/cha.rs
yazi-shared/src/fs/cha.rs
yazi-shared/src/fs/fns.rs
yazi-shared/src/fs/loc.rs

`usize` only needs `8` bytes, while `*const OsStr` needs `16` bytes since it carries extra length information. 
This change can lower memory usage for large directories since `Loc` is included in each file entity.

perf: using `usize` instead of `*const OsStr` reduces memory usage

---

yazi-fm/src/lives/finder.rs
yazi-plugin/preset/components/header.lua
yazi-plugin/preset/components/status.lua

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1825
Closes https://github.com/sxyazi/yazi/issues/1825

feat: suggest keywords in the header if a finder is active

---

yazi-core/src/manager/commands/bulk_rename.rs

Resolve #1766 . Sort bulk-renamed files in a similar way to topological sort.

feat: prioritize paths that need to be processed first during bulk renaming

---

yazi-config/src/layout.rs
yazi-fm/src/app/commands/mod.rs
yazi-fm/src/app/commands/reflow.rs
yazi-fm/src/app/commands/resize.rs
yazi-fm/src/components/progress.rs
yazi-fm/src/root.rs
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/entity.lua
yazi-plugin/preset/components/header.lua
yazi-plugin/preset/components/linemode.lua
yazi-plugin/preset/components/marker.lua
yazi-plugin/preset/components/parent.lua
yazi-plugin/preset/components/preview.lua
yazi-plugin/preset/components/progress.lua
yazi-plugin/preset/components/rail.lua
yazi-plugin/preset/components/root.lua
yazi-plugin/preset/components/status.lua
yazi-plugin/preset/components/tab.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/src/utils/call.rs

Previously, when the terminal size changed, it required two complete renderings: the first rendered a virtual frame with the new size, and the information from that frame was applied to the second rendering.
This PR introduces the new concept of "reflow", which has almost no overhead compared to rendering, and the actual rendering only needs to happen once, and only the changes detected during reflow will trigger it
Also fixes https://github.com/sxyazi/yazi/issues/1855

perf: introduce reflow for the rendering engine

---

yazi-fs/src/folder.rs

this pr fix:
wrong file list offset squeeze (#1865)

fix: wrong file list offset squeeze when `scrolloff = 0`

---

yazi-core/src/tab/commands/copy.rs

resolves #1861 
This PR adds support for choosing the path separator for the copy command between:
- `auto`: uses `/` on Unix-like systems and `\` on Windows
- `unix`: forces forward slashes (`/`) in the path copied to the user's clipboard
EDIT: The tests in CI passes! So it should be working now. 
I havn't written mcuh cross-platform Rust code, and I'm unsure how to run tests targeted for Windows on my Linux machine 😅. Any advice or extra caution during review would be appreciated.

feat: new `copy --separator` option to allow specifying the path separator

---

yazi-cli/src/package/parser.rs
yazi-shared/src/event/cmd.rs

resolves #1881 
When using `ya pack -l`, show commit hash.
Before(don't show commit hash)
```
$ ya pack -l
plugins:
GrzegorzKozub/mdcat
flavors:
yazi-rs/flavors:catppuccin-mocha
```
After(show commit hash)
```
$ ya pack -l
plugins:
GrzegorzKozub/mdcat (78cef96)
flavors:
yazi-rs/flavors:catppuccin-mocha (d504f70)
```
This content is specific to my environment, so please don't worry about it.

feat: include package revision hash in `ya pack --list`

---

yazi-adapter/src/ueberzug.rs
yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/extract.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/fzf.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/mime.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/preset/plugins/zoxide.lua
yazi-scheduler/src/process/process.rs

- "Spawn a command/process" is not straightforward for non-technical users. Using "Run a command/process" or "Execute a command/process" in error messages would be better.

refactor: make error messages more user-friendly

---

yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/extract.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/fzf.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/mime.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/preset/plugins/zoxide.lua
yazi-plugin/src/config/config.rs
yazi-plugin/src/elements/elements.rs
yazi-plugin/src/elements/paragraph.rs
yazi-plugin/src/error.rs
yazi-plugin/src/fs/fs.rs
yazi-plugin/src/loader/require.rs
yazi-plugin/src/process/child.rs
yazi-plugin/src/process/command.rs
yazi-plugin/src/pubsub/mod.rs
yazi-plugin/src/url/url.rs
yazi-plugin/src/utils/utils.rs
yazi-shared/src/fs/fns.rs
yazi-shared/src/fs/urn.rs

In practice, most of these I/O errors need to be displayed to the end user through logs or prompts. Showing an error code to the user doesn't make much sense:
```lua
local _, code = fs.remove("file", Url("/foo"))
ya.dbg("Failed to remove `/foo`, error code: " .. code)
```
which prints:
```
Failed to remove `/foo`, error code: 2
```
This PR changes the type of I/O errors from a number to a new `Error` type. 
The `Error` type implements the [`__tostring()`](https://www.lua.org/manual/5.4/manual.html#pdf-tostring) and [`__concat()`](https://www.lua.org/manual/5.4/manual.html#3.4.6) meta method, allowing it to generate more human-readable error messages:
```lua
local _, err = fs.remove("file", Url("/foo"))
ya.dbg("Failed to remove `/foo`, error: " .. err)
```
which prints:
```
Failed to …
```

feat!: use an `Error` userdata instead of a plain error code for I/O errors

---

README.md
yazi-config/preset/theme+dark.toml
yazi-config/preset/theme+light.toml
yazi-config/preset/theme-base.toml
yazi-config/src/theme/theme.rs
yazi-macro/src/asset.rs
yazi-plugin/preset/components/status.lua

An implementation of the feature request: https://github.com/sxyazi/yazi/pull/732, https://github.com/sxyazi/yazi/issues/1228
Closes https://github.com/sxyazi/yazi/pull/732, https://github.com/sxyazi/yazi/issues/1228
---
Previously, only a single mode style was supported, which meant the same mode style was used for both the highlight and secondary colors, and the separator style was applied to the secondary color. 
This led to the inability to set different styles for the primary color of the mode, and users couldn't control the mode style independently because it depended on the separator style.
This PR separates the mode from the separator style, making it its own distinct style. Users will now be able to set different main and alternate styles for each of the 3 modes individually. …

feat!: extend the available styles for `mode` by separating `mode` from the `separator` styles

---

yazi-cli/src/package/deploy.rs
yazi-cli/src/package/git.rs
yazi-shared/src/fs/fns.rs

feature for #1947 , haven tested based on [my sudo.yazi fork](https://github.com/zooeywm/sudo.yazi/tree/main)
```zsh
❯ ./ya pack --add=zooeywm/sudo
Upgrading package `sudo.yazi`
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 544 bytes | 544.00 KiB/s, done.
From https://github.com/zooeywm/sudo.yazi
4f446d3..8a3c803  main       -> origin/main
Previous HEAD position was 4f446d3 chore(ya): `ya pack` -a support assets folder contains miscellaneous files
HEAD is now at 8a3c803 chore(yazi): https://github.com/sxyazi/yazi/pull/1966
❯ tree ~/.config/yazi/plugins/sudo.yazi
/home/zooeywm/.config/yazi/plugins/sudo.yazi …
```

feat: support `assets` installation for the `ya pack` subcommand

---

yazi-config/src/lib.rs
yazi-core/src/tab/commands/shell.rs
yazi-dds/src/sendable.rs
yazi-shared/src/event/data.rs

This PR removes the `--confirm` option for the [`shell` command](https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell), as it was a design flaw - running shell commands shouldn't be so painful; it should feel as natural as drinking water. 
When users write shell commands, they usually want to run them directly, not enter an interactive mode through a shell input box.
To ensure the safe removal of this option, [since Yazi v0.3](https://github.com/sxyazi/yazi/commit/987b1d5c49f5d11ab9e6a9cdea21974b440ae463#diff-50eb0ae5b409b5134616d6b4fa8f88d4d6010ada7bc2fc2ec2f64da126d1fe58), users have been required to explicitly specify the `--interactive` flag for interactive shell commands:
https://github.com/sxyazi/yazi/blob/4bd8b0b44681cef9d12b16e3b3e70520711599ba/yazi-config/src/lib.rs# …

feat!: remove the meaningless `--confirm` option to simplify the `shell` command

---

yazi-core/src/manager/commands/update_files.rs
yazi-core/src/manager/linked.rs
yazi-core/src/manager/watcher.rs
yazi-plugin/preset/ya.lua

Fixes https://github.com/sxyazi/yazi/issues/1981

fix: propagate and update the directory node till its first parent when the files of a directory change

---

yazi-fs/src/files.rs

Fixes https://github.com/sxyazi/yazi/issues/1990

fix: revise `revision` if the new file list is empty but the previous one was not

---

.github/workflows/draft.yml
Cargo.lock
Cargo.toml
yazi-adapter/src/dimension.rs
yazi-adapter/src/emulator.rs

All terminals on Windows (MS Terminal, WezTerm for Windows) do not support `TIOCGWINSZ` because Windows doesn't have `ioctl`. 
Some terminals based on `node-pty` also don't support it (like Tabby, VSCode, Hyper, etc.).
This PR falls back to `CSI 16 t` when `TIOCGWINSZ` is unavailable to provide better image size calculation for previews.

feat: fallback to `CSI 16 t` for certain terminals that do not support `TIOCGWINSZ`

---

yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua

See also: https://man.archlinux.org/man/pdftoppm.1#quality

fix: respect `PREVIEW.image_quality` for the default PDF previewer

---

yazi-plugin/preset/plugins/video.lua

See also:
- https://trac.ffmpeg.org/wiki/Scaling
- https://superuser.com/questions/566998/how-can-i-fit-a-video-to-a-certain-size-but-dont-upscale-it-with-ffmpeg
Additionally, ensuring even dimensions (using `-2`) may not be necessary, as these frames are only being extracted as images without any further encoding.

fix: avoid upscaling for the video previewer

---

scripts/publish.sh
yazi-adapter/src/brand.rs
yazi-adapter/src/lib.rs
yazi-adapter/src/mux.rs
yazi-boot/src/actions/debug.rs
yazi-codegen/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/2013

fix: disable passthrough when the user launches Yazi in Neovim inside tmux

---

yazi-boot/src/actions/version.rs
yazi-dds/src/body/hey.rs
yazi-dds/src/body/hi.rs
yazi-dds/src/client.rs

- Although `format!` macro is very powerful, it introduces overhead of memory allocation on the heap compared to `&str`. Therefore, when `format!` macro is unnecessary, we should avoid using it.

refactor: replace `format!` with `concat!` for string literals

---

Cargo.lock
yazi-adapter/Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-codegen/Cargo.toml
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-dds/Cargo.toml
yazi-fm/Cargo.toml
yazi-fs/Cargo.toml
yazi-macro/Cargo.toml
yazi-plugin/Cargo.toml
yazi-proxy/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-shared/Cargo.toml

This is a quick patch version with 4 fixes:
- Fixed an issue where Yazi would freeze when waiting for terminal response, in old tmux versions (v3.2a or lower), or 2-layer nested terminal setup (tmux -> Neovim's `:terminal` -> Yazi).
- Fixed a bug in the Überzug++ backend where certain image dimension parsing failed, preventing images from displaying.
- Fixed a build failure for Android 32-bit architectures.
- Fixed an issue with the preset `archive` and `json` plugins not handling CRLF properly on Windows.

chore: bump version to 0.4.1

---

yazi-config/src/manager/manager.rs
yazi-plugin/src/bindings/cha.rs
yazi-proxy/src/app.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2026
Closes https://github.com/sxyazi/yazi/issues/2026
```toml
[manager]
_v4_suppress_deprecation_warnings = true
```

feat: new option to suppress 0.4 deprecation warnings

---

yazi-config/preset/yazi-default.toml
yazi-fs/src/path.rs
yazi-scheduler/src/file/file.rs

Fixes https://github.com/sxyazi/yazi/issues/2036

fix: choose a more conservative `macro_workers` value to ensure concurrency safety with certain USB flash drives

---

Cargo.lock
README.md
yazi-core/src/manager/commands/refresh.rs
yazi-fs/src/cwd.rs
yazi-plugin/src/utils/user.rs
yazi-shared/src/os.rs

Fixes https://github.com/sxyazi/yazi/issues/2042

fix: set the current working directory in a thread-safe way

---

yazi-adapter/src/lib.rs
yazi-adapter/src/mux.rs
yazi-fm/src/term.rs

Fixes https://github.com/sxyazi/yazi/issues/2050

fix: `allow-passthrough` must be set to `on` to prevent `tmux` from forwarding the real terminal's response to the inactive pane

---

yazi-adapter/src/emulator.rs
yazi-adapter/src/mux.rs
yazi-fm/src/term.rs

Fixes https://github.com/sxyazi/yazi/issues/2050

fix: use a less intrusive `DSR` instead of `DA1` workaround to forward terminal responses twice in `tmux`

---

yazi-plugin/src/elements/text.rs

Fixes https://github.com/sxyazi/yazi/issues/2091

fix: element style of `ui.Text` was not applied to the entire area

---

yazi-config/preset/yazi-default.toml
yazi-config/src/popup/options.rs
yazi-core/src/confirm/commands/show.rs
yazi-core/src/confirm/confirm.rs
yazi-fm/src/confirm/confirm.rs
yazi-fm/src/confirm/content.rs
yazi-plugin/src/elements/line.rs
yazi-plugin/src/utils/layer.rs
yazi-plugin/src/utils/utils.rs
yazi-shared/src/theme/style.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2082
Closes https://github.com/sxyazi/yazi/issues/2082
---
```lua
local answer = ya.confirm {
pos = { "center", w = 40, h = 10 },
title = "Test",
content = "Hello, World!",
}
```
You can also apply a UI element to the title and content, to customize the appearance:
```lua
local answer = ya.confirm {
pos = { "center", w = 40, h = 10 },
title = ui.Line("Test"):fg("yellow"):bold(),
content = ui.Text("Hello, World!"):bg("red"):fg("#ffffff"),
}
```
The available values for `pos` are the same as those for `ya.input()`, https://yazi-rs.github.io/docs/plugins/utils#ya.input

feat: new `ya.confirm()` API

---

yazi-plugin/preset/plugins/zoxide.lua

Also fixed some local variables that were redefined.
Closes #1851.

feat: prompt users without `fzf` for the `zoxide` plugin

---

yazi-fs/src/files.rs

fix: correct Vec capacity allocation caused by variable name shadowing

---

yazi-config/preset/yazi-default.toml

Fixes https://github.com/sxyazi/yazi/issues/2172
Also removed `*/xml` since the mimetype `text/xml` is already covered by `text/*`

feat: support `application/mbox` mimetype

---

yazi-config/preset/keymap-default.toml
yazi-core/src/input/commands/backspace.rs
yazi-core/src/input/commands/backward.rs
yazi-core/src/input/commands/complete.rs
yazi-core/src/input/commands/escape.rs
yazi-core/src/input/commands/forward.rs
yazi-core/src/input/commands/mod.rs
yazi-core/src/input/commands/move_.rs
yazi-core/src/input/commands/replace.rs
yazi-core/src/input/commands/show.rs
yazi-core/src/input/commands/type_.rs
yazi-core/src/input/input.rs
yazi-core/src/input/mode.rs
yazi-fm/src/app/app.rs
yazi-fm/src/executor.rs
yazi-fm/src/input/input.rs
yazi-fm/src/term.rs
yazi-shared/src/chars.rs

feat: replace mode and Vim motions (`W`, `E`, `B`, `^`, `_`) for inputs

---

.github/workflows/test.yml
CONTRIBUTING.md

While following the [Development setup](https://github.com/sxyazi/yazi/blob/ba62b407bdf0cb0b21641981a5729c4a6de0fa6c/CONTRIBUTING.md#development-setup) section of the `CONTRIBUTING.MD`, I noticed that running `cargo test` in the root directory (`yazi/`) results in no tests being executed.
As specified in https://doc.rust-lang.org/cargo/commands/cargo-test.html, running `cargo test --workspace` executes all of the project tests, as expected.

docs: correct the `cargo test` command in the contribution guide

---

yazi-cli/src/package/dependency.rs
yazi-cli/src/package/deploy.rs
yazi-cli/src/package/git.rs

When attempting to install a plugin with a format like `yazi-rs/plugins:mime-ext`, an error message "No such file or directory" is returned.
The error occurs because the constructed local path to the plugin source is missing the `.yazi` extension. This results in incorrect paths such as `mime-ext/init.lua` instead of the correct `mime-ext.yazi/init.lua`.
This patch addresses this issue by ensuring the `.yazi` extension is correctly included when constructing the local path for these plugins.
Thanks for your amazing work!

fix: incorrect monorepo sub-plugin path resolution

---

yazi-core/src/manager/commands/close.rs
yazi-core/src/manager/commands/quit.rs

It will be helpful to forward `close` params to `quit`. Then users can use commands like `close --cwd-file`, `close --no-cwd-file`, to control the quit behavior indirectly.

feat: new `--no-cwd-file` option for the `close` command

---

yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-cli/src/package/delete.rs
yazi-cli/src/package/dependency.rs
yazi-cli/src/package/deploy.rs
yazi-cli/src/package/hash.rs
yazi-cli/src/package/install.rs
yazi-cli/src/package/mod.rs
yazi-cli/src/package/package.rs

Closes https://github.com/sxyazi/yazi/issues/2147
To add the `delete` command, I followed the same pattern that existed in the `src/args.rs`, `src/main.rs` and `src/package/*` directories.
I tried to follow the existing code style, and kept refactorings to a minimum - I created two helper methods - `find_dep_in_package` and `deployed_directory`. If there are any naming issues or you would like the code to be structured differently, feel free to say!
As things are, this will not delete the package code that is present in `Xdg::local()` directory, as I don't understand why the `state_dir()` of a dependency is using an hash to identify the package (`format!("{:x}", XxHash3_128::oneshot(self.remote().as_bytes()))`) instead of just using the package name. 
I'm assuming it is desired to also …

feat: new `ya pack -d` subcommand to delete packages

---

yazi-config/preset/keymap-default.toml

[spot]
description labels swapped

fix: wrong description of the `swipe` command

---

.github/workflows/draft.yml
.gitignore
snap/snapcraft.yaml

This PR makes a few small adjustments to the snap package.
Firstly, it uses packages from the Ubuntu archive (or Snap store) for `yazi`'s dependencies such as `fzf`, `zoxide`, `jq`, etc.
The one exception is `magick`, where in the Ubuntu package `magick` binary is not present (I don't know why!), so we build from source. This has the advantage over fetching the prebuilt binary in that it'll work across architectures.
Also re-enables `arm64` (see [post](https://forum.snapcraft.io/t/help-needed-cant-build-arm64-snap-with-github-actions/41356)).
Tested this on my `amd64` laptop - as far as I can tell it all works (including the image previews 😎 )

feat: arm64 Snap package

---

.github/workflows/draft.yml

Fixes a minor error in recently merged CI pipeline for snap build.

ci(snap): correct `runs-on` definition for snap workflow

---

.github/workflows/draft.yml

Resolves an error in the latest snap build run in CI. Disables shallow cloning when pulling the code.

ci(snap): don't use a shallow clone when checking out the repo for snap build

---

yazi-plugin/preset/components/modal.lua
yazi-plugin/preset/components/rail.lua
yazi-plugin/preset/components/root.lua
yazi-plugin/preset/components/tab.lua
yazi-plugin/src/lua.rs

With this PR, you'll be able to dynamically register custom modal components to Yazi. 
A modal is an isolated component on the screen where you can access all the app data that Yazi supports, and you can also use all available UI layout APIs to create flexible and powerful custom UIs.
To register a component to Yazi, use `Modal:children_add(component, order)`.
Each component has the following attributes:
- `_id`: A unique ID for the component, which cannot conflict with the [built-in component](https://github.com/sxyazi/yazi/tree/main/yazi-plugin/preset/components) IDs.
- `new`: The function to instantiate the component, which returns a component instance. This function accepts an `area` parameter, a `Rect` that represents the entire screen area.
- `reflow`: The component's reflow …

feat: custom modal component API

---

yazi-plugin/src/bindings/chan.rs
yazi-plugin/src/bindings/mod.rs
yazi-plugin/src/utils/sync.rs
yazi-plugin/src/utils/utils.rs

Two new APIs added:
- `ya.chan()` - Create a channel
- `ya.join()` - Join multi-concurrent tasks
For example:
```lua
local keys = {
{ on = "q", run = "quit" },
{ on = "k", run = "up" },
{ on = "j", run = "down" },
{ on = "h", run = "left" },
{ on = "l", run = "right" },
}
local tx, rx = ya.chan("mpsc")
function producer()
while true do
local cand = self.keys[ya.which { cands = self.keys, silent = true }]
if cand then
tx:send(cand.run)
if cand.run == "quit" then
break
end
end
end
end
function consumer()
repeat
local run = rx:recv()
if run == "quit" then
break
elseif run == "up" then
ya.dbg("up")
elseif run == "down" then
ya.dbg("down")
elseif run == "left" then
ya.dbg("left")
elseif run == "right" then
ya.dbg("right")
end
until not run
end
ya.join(producer, consumer)
```

feat: channel and multi-concurrent task join support for the plugin system

---

.github/workflows/draft.yml
snap/snapcraft.yaml

I've taken a look at the snap build failures on arm64. It looks like snapcraft behaves subtly differently on amd64 and arm64 with respect to automatically patching ELF binaries. This PR addresses that - it turns out we don't need the manual patch for things to function. Tested locally on my machine, and everything seems to work just fine.
In addition, Github [announced](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) yesterday that arm64 runners are now available to public repos - so this PR also simplifies the snap build pipeline to use those - which simplifies both the pipeline and (hopefully) the debugging of any issues.

ci: use GitHub Linux arm64 runners for the snap build

---

flake.nix

The `rust-overlay` project strongly recommend not overlaying the global Rust platform since that can cause a dependency loop, creating an infinite recursion (see https://github.com/oxalica/rust-overlay/issues/198#issuecomment-2566755261).
Instead, a custom `rustPlatform` can be passed to the derivation, as per the instructions in the [Nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#using-rust-nightly-in-a-derivation-with-buildrustpackage).
Fixes: https://github.com/sxyazi/yazi/issues/2215

fix(nix): rust overlay infinite recursion

---

.github/workflows/draft.yml

Correct a minor error I introduced in refactoring the snap workflow. Now this actually uses an arm runner 🤦‍♂️ 
Sorry about the noise!

ci(snap): correct arm64 runner OS

---

.gitignore

Update `.gitignore` to not track the built completions files.
Added general pattern to ignore all `completions` directories in the first level of any `yazi-*` directory.

fix: ignore completions artifacts

---

yazi-fs/src/mounts/linux.rs
yazi-fs/src/mounts/macos.rs

Fixes https://github.com/yazi-rs/plugins/pull/53#issuecomment-2607313343
This will benefit downstream plugins using the `ya.partitions()` API, as the results they get will always be ordered after this PR.

feat: apply natural sort to partitions on both Linux and macOS

---

Cargo.lock
Cargo.toml
yazi-config/Cargo.toml
yazi-core/src/tab/commands/search.rs
yazi-fm/Cargo.toml
yazi-fm/src/tasks/tasks.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1582
Closes https://github.com/sxyazi/yazi/issues/1582
---
If task description is longer than window width -> wrap rest
Changes were made in responce for existing enhancement https://github.com/sxyazi/yazi/issues/1582
Was implemented by spliting text in lines with textwrap and using Text instead of ListItem for display
**Before changes**
**After changes**

feat: wrap long task descriptions

---

README.md
yazi-adapter/src/brand.rs

Bobcat, yet another cross-platform terminal emulator, also supports yazi's image preview feature, with both iTerm2 & sixel protocols.  (See the [screenshots](https://github.com/ismail-yilmaz/Bobcat?tab=readme-ov-file#Screenshots) section for an example.)
This PR adds Bobcat to the brands list and updates the README file. With this change, Yazi can recognize Bobcat by sending an extended attributes report request (`CSI > q`).

docs: add Bobcat to the list of VTEs with images preview support

---

yazi-core/src/manager/manager.rs
yazi-fm/src/app/commands/resize.rs

Fixes https://github.com/sxyazi/yazi/issues/1859
Fixes https://github.com/sxyazi/yazi/issues/1860

fix: squeeze the parent directory offset after terminal size change

---

Cargo.lock
Cargo.toml
yazi-boot/src/actions/actions.rs
yazi-boot/src/actions/version.rs
yazi-codegen/Cargo.toml
yazi-core/src/manager/commands/quit.rs
yazi-core/src/notify/commands/push.rs
yazi-core/src/notify/message.rs
yazi-fm/src/app/commands/plugin.rs
yazi-fm/src/term.rs
yazi-plugin/src/loader/chunk.rs
yazi-plugin/src/loader/loader.rs
yazi-plugin/src/macros.rs
yazi-proxy/src/options/notify.rs
yazi-scheduler/src/plugin/plugin.rs

You can now **optionally** specify the minimum supported Yazi version in your plugin:
```lua
--- @since 0.5.0
return {
entry = function() end
}
```
If specified, and the user's Yazi version is lower than the specified version, they will receive an error message, preventing the plugin from running accidentally.

feat: new `@since` plugin annotation to specify the minimum supported Yazi version

---

yazi-config/preset/keymap-default.toml
yazi-config/src/lib.rs
yazi-core/src/input/commands/move_.rs
yazi-core/src/tab/commands/arrow.rs
yazi-fs/src/step.rs

This PR deprecates `arrow -99999999` and `arrow 99999999`, replacing them with `arrow top` and `arrow bot`, respectively. `-99999999` and `99999999` are still available but will trigger a warning.
This change is in preparation for an upcoming navigation wraparound feature — when the cursor reaches the top or bottom of the list, it will automatically jump to the opposite end.  
Some users requested this feature, and I initially [provided a plugin](https://yazi-rs.github.io/docs/tips#navigation-wraparound) as a solution. However, I believe it's worth integrating into the core. 
The issue is that when users enable this feature, pressing `gg` or `G` would cause the cursor to behave erratically since `arrow 99999999` would make it loop through the file list multiple times, so `top` and `bot` …

feat: new `arrow top` and `arrow bot` commands to jump to the top and bottom

---

README.md

Sixel support in Windows Terminal is now stable as of https://github.com/microsoft/terminal/releases/tag/v1.22.10352.0 🎉
- Related: https://github.com/yazi-rs/yazi-rs.github.io/pull/202

docs: update Windows Terminal image preview support to stable

---

Cargo.lock
Cargo.toml
yazi-proxy/Cargo.toml
yazi-proxy/src/options/plugin.rs
yazi-proxy/src/options/search.rs
yazi-shared/Cargo.toml
yazi-shared/src/event/cmd.rs
yazi-shared/src/shell/mod.rs
yazi-shared/src/shell/unix.rs

This PR aims to simplify the usage of `shell` and `plugin` commands. 
The `shell` command accepts a shell script as a parameter that needs to be executed. Previously, if the script contained special characters like spaces, newlines, or quotes, it had to be quoted. 
For example, a simple `echo "hello 'world'"`:
```toml
[[manager.prepend_keymap]]
on  = "<C-e>"
run = '''
shell --block 'echo "hello '\''world'\''"'
'''
```
This resulted in nested quotes, which was error-prone and not intuitive. 
Now, you can directly include the entire shell script as plain text after `--` without any escaping, like this:
```toml
[[manager.prepend_keymap]]
on  = "<C-e>"
run = '''
shell --block -- echo "hello 'world'"
'''
```
Similarly, with (TODO), this will also simplify the usage of the `plugin` command, …

feat: support end of options (`--`) marker for all commands

---

yazi-plugin/src/isolate/preload.rs
yazi-plugin/src/macros.rs
yazi-proxy/src/lib.rs
yazi-proxy/src/macros.rs
yazi-proxy/src/options/plugin.rs
yazi-proxy/src/options/search.rs
yazi-proxy/src/tab.rs
yazi-shared/src/event/cmd.rs

Follow up to https://github.com/sxyazi/yazi/pull/2298
With https://github.com/sxyazi/yazi/pull/2298, all commands now support passing raw text as the last argument after `--`, without requiring any escaping.  
This PR aims to simplify argument passing for plugin commands by deprecating the `--args` option in the `plugin` command. 
Instead, the new second positional argument represents the list of arguments received by the plugin. For example:  
```toml
[[manager.prepend_keymap]]
on  = "<C-e>"
run = "plugin search --args='--keyword=\'hello world\''"
```  
can now be written as:  
```toml
[[manager.prepend_keymap]]
on  = "<C-e>"
run = "plugin search -- --keyword='hello world'"
```  
The existing `--args` option will still be available but will trigger a deprecation warning to ensure a …

feat: use positional argument instead of `--args` for the `plugin` command

---

scripts/publish.sh
yazi-adapter/src/adapter.rs
yazi-adapter/src/brand.rs
yazi-adapter/src/dimension.rs
yazi-adapter/src/drivers/iip.rs
yazi-adapter/src/drivers/kgp.rs
yazi-adapter/src/drivers/kgp_old.rs
yazi-adapter/src/drivers/sixel.rs
yazi-adapter/src/emulator.rs
yazi-adapter/src/lib.rs
yazi-adapter/src/mux.rs
yazi-adapter/src/unknown.rs
yazi-boot/src/actions/debug.rs
yazi-config/preset/README.md
yazi-core/src/manager/watcher.rs
yazi-core/src/tab/preview.rs
yazi-fm/src/term.rs
yazi-plugin/preset/plugins/extract.lua
yazi-plugin/src/elements/clear.rs
yazi-plugin/src/utils/image.rs
yazi-shared/src/either.rs
yazi-shared/src/sync_cell.rs

Fixes https://github.com/sxyazi/yazi/issues/2306

fix: reverse the order of CSI-based and environment-based terminal detection

---

yazi-cli/src/main.rs
yazi-cli/src/package/delete.rs
yazi-cli/src/package/package.rs
yazi-fs/src/fns.rs

Fixes https://github.com/sxyazi/yazi/issues/2318

fix: unable to delete sealed files on Windows due to platform differences

---

Cargo.lock
yazi-config/preset/theme-dark.toml
yazi-config/preset/theme-light.toml
yazi-config/src/theme/theme.rs
yazi-plugin/preset/components/status.lua
yazi-plugin/src/elements/rect.rs
yazi-plugin/src/loader/loader.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2228
Closes https://github.com/sxyazi/yazi/issues/2228

feat: new `overall` option under `[status]` to allow specifying the overall style of the status bar

---

yazi-plugin/preset/plugins/json.lua

Json previewer doesn't wrap even if user set `  wrap = "yes"` in yazi.toml. This PR fix it.
Before:
After:

feat: respect the user's `wrap` setting for the built-in JSON previewer

---

Cargo.lock
Cargo.toml
yazi-scheduler/Cargo.toml

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2387
Closes https://github.com/sxyazi/yazi/issues/2387

feat: bump `trash` and `libc` versions to support NetBSD

---

yazi-config/preset/theme-dark.toml
yazi-config/preset/theme-light.toml
yazi-config/preset/yazi-default.toml
yazi-config/src/theme/theme.rs
yazi-dds/src/body/delete.rs
yazi-dds/src/body/trash.rs
yazi-fm/src/main.rs
yazi-plugin/preset/components/entity.lua
yazi-plugin/preset/components/header.lua
yazi-plugin/preset/components/marker.lua
yazi-plugin/preset/components/progress.lua
yazi-plugin/preset/components/rail.lua
yazi-plugin/preset/components/status.lua
yazi-plugin/preset/components/tab.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/image.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/src/config/config.rs
yazi-plugin/src/config/mod.rs
yazi-plugin/src/config/plugin.rs
yazi-plugin/src/config/theme.rs
yazi-plugin/src/isolate/isolate.rs
yazi-plugin/src/lua.rs
yazi-plugin/src/utils/json.rs
yazi-plugin/src/utils/utils.rs
yazi-shared/src/event/cmd.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1986
Closes https://github.com/sxyazi/yazi/issues/1986
---
This PR replaces the existing `MANAGER`, `PREVIEW`, `PLUGIN`, and `THEME` with new `cf` and `th` to resolve the following issues:
- `MANAGER` can only be accessed in sync plugins, and not in async plugins.
- `PREVIEW` can only be accessed in async plugins, and not in sync plugins.
- `PLUGIN` can only be accessed in async plugins, and not in sync plugins.
- `THEME` can only be accessed in sync plugins, and not in async plugins.
The new `cf` and `th` can be consistently used in both sync and async plugins. They are lazy-loaded, meaning they are only loaded into Lua when a value is accessed, which improves performance.
`MANAGER`, `PREVIEW`, `PLUGIN`, and …

feat: new `cf` and `th` allow to access user configuration and theme scheme in sync/async plugins consistently

---

scripts/validate-form/main.js
yazi-config/preset/theme-dark.toml
yazi-config/preset/theme-light.toml
yazi-config/src/theme/theme.rs
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/image.lua
yazi-plugin/preset/plugins/video.lua

Follow up to https://github.com/sxyazi/yazi/pull/2389
---
An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1986
Closes https://github.com/sxyazi/yazi/issues/1986

feat: new `tbl_col` and `tbl_cell` in theme system for spotter table styling

---

yazi-core/src/tab/commands/search.rs
yazi-plugin/src/external/mod.rs
yazi-plugin/src/external/rg.rs
yazi-plugin/src/external/rga.rs
yazi-proxy/src/options/search.rs

ripgrep-all supports all options which are currently used for ripgrep. 
In the future, this could get spun out into  external/rga.rs, but as of now it would be a complete copy of rg.rs with even more duplicated code in the search function. 
I do not know if making use of features which ripgrep-all does not have is at all on any roadmap, so I went for the simpler solution.

feat: add ripgrep-all support for search

---

yazi-plugin/src/config/config.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2263
Closes https://github.com/sxyazi/yazi/issues/2263
With this PR, you can get the `--chooser-file` the user passed when starting Yazi and do anything you want:
```lua
if cf.args.chooser_file then
-- ...
end
```

feat: new `cf.args` to access startup arguments

---

yazi-fm/src/app/commands/accept_payload.rs
yazi-fm/src/app/commands/plugin.rs
yazi-plugin/preset/components/entity.lua
yazi-plugin/preset/components/tab.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/image.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/src/config/mod.rs
yazi-plugin/src/config/runtime.rs
yazi-plugin/src/isolate/isolate.rs
yazi-plugin/src/loader/require.rs
yazi-plugin/src/lua.rs
yazi-plugin/src/macros.rs
yazi-plugin/src/pubsub/pubsub.rs
yazi-plugin/src/utils/sync.rs

`cf` was introduced in https://github.com/sxyazi/yazi/pull/2389, and this PR renames it to `rt`. 
`cf` was introduced yesterday (Feb 23, 2025), and it was not included in any releases, so it should not break anything.

refactor: rename `cf` to `rt`

---

yazi-plugin/src/config/theme.rs

I realised that the `th` object only exposes the theme of a few components, so this commit exposes all theme fields, except for `filetypes` and `icons`.

feat: expose all theme fields in Lua

---

yazi-adapter/src/stdin.rs

Fixes https://github.com/sxyazi/yazi/issues/2421
Fixes https://github.com/sxyazi/yazi/issues/2423

fix: ignore stdin redirection to ensure always accessing the real tty

---

yazi-cli/src/args.rs
yazi-core/src/tab/commands/search.rs
yazi-proxy/src/options/plugin.rs
yazi-proxy/src/options/search.rs
yazi-shared/src/event/cmd.rs
yazi-shared/src/shell/mod.rs
yazi-shared/src/shell/unix.rs

Fixes https://github.com/sxyazi/yazi/issues/2429

fix: align the behavior of the end-of-options marker (`--`) with that of the shell

---

.github/workflows/draft.yml
yazi-config/preset/keymap-default.toml
yazi-core/src/input/commands/visual.rs
yazi-fm/src/executor.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2430
Closes https://github.com/sxyazi/yazi/issues/2430

feat: new `<C-A>` and `<C-E>` keybindings to select entire line for the input component

---

Cargo.lock
Cargo.toml
yazi-codegen/Cargo.toml
yazi-config/preset/keymap-default.toml
yazi-fm/Cargo.toml
yazi-plugin/src/config/runtime.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2368
Closes https://github.com/sxyazi/yazi/issues/2368
```lua
-- Whether the user's terminal is in light mode, which is a boolean
rt.term.light  
```

feat: new `rt.term` exports terminal emulator information

---

README.md
yazi-plugin/preset/components/status.lua

Fixes https://github.com/sxyazi/yazi/issues/2448
Now, for empty directories, it will show "0B". I think that makes sense since an empty directory doesn't have any files with a zero size

fix: always show the size in the status bar even in empty directories

---

Cargo.lock
Cargo.toml
yazi-codegen/Cargo.toml
yazi-config/preset/keymap-default.toml
yazi-config/src/layout.rs
yazi-config/src/lib.rs
yazi-core/src/tab/commands/arrow.rs
yazi-core/src/tab/folder.rs
yazi-fs/src/step.rs
yazi-plugin/src/isolate/preload.rs
yazi-plugin/src/utils/utils.rs

This PR adds new `arrow prev` and `arrow next` commands that provide wraparound navigation at list boundaries and sets them as the default key bindings. 
This decision is based on the following considerations:
- It was requested by multiple users in the past.
- It operates only on a single movement unit (±1), making wraparound navigation more intuitive when continuing to press `j` or `k` at the list boundaries.
- It does not affect the behavior of `arrow 5` (multiple units) or `arrow 50%` (percentage), and the original `arrow -1` and `arrow 1` commands remain available for the previous behavior.

feat: file navigation wraparound with new `arrow prev` and `arrow next` commands

---

Cargo.lock
Cargo.toml
yazi-config/preset/keymap-default.toml
yazi-config/preset/yazi-default.toml
yazi-config/src/plugin/previewer.rs
yazi-core/src/tab/preview.rs
yazi-fm/src/app/commands/plugin.rs
yazi-fm/src/term.rs
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/src/config/runtime.rs
yazi-plugin/src/isolate/entry.rs
yazi-plugin/src/isolate/fetch.rs
yazi-plugin/src/isolate/peek.rs
yazi-plugin/src/isolate/preload.rs
yazi-plugin/src/isolate/spot.rs
yazi-plugin/src/loader/chunk.rs
yazi-plugin/src/loader/loader.rs
yazi-plugin/src/loader/require.rs

After this PR, the runtime environment of the previewer (synchronous or asynchronous) will be distributed as metadata together with the source code.
This means that when a plugin needs to change the runtime, it will no longer require users to modify it in their `yazi.toml`.
`sync = true` has been removed:
```diff
[plugin]
prepend_previewers = [
-  { name = "*/", run = "folder", sync = true },
+  { name = "*/", run = "folder" },
]
```
and replaced with the new `--- @sync peek` annotation:
```diff
+ --- @sync peek
```
Considering that except for the [preset `folder` previewer](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/folder.lua), almost all previewers are asynchronous, the impact of this change should be reasonably small.

feat!: new `@sync peek` annotation for sync previewers

---

scripts/validate-form/main.js
yazi-fm/src/logs.rs
yazi-plugin/src/isolate/entry.rs
yazi-plugin/src/isolate/fetch.rs
yazi-plugin/src/isolate/peek.rs
yazi-plugin/src/isolate/preload.rs
yazi-plugin/src/isolate/spot.rs
yazi-plugin/src/loader/chunk.rs
yazi-plugin/src/loader/loader.rs

This PR aims to improve the loading performance of Lua plugins. 
After this PR, all plugins (preset and custom) will be lazily compiled and cached as a binary bytecode representation upon first use, and will subsequently be loaded directly from the binary cache rather than being recompiled from the textual source code, thereby improving the overall performance of the plugin system.

perf: lazy compile and cache lua plugins as binary bytecode

---

yazi-core/src/mgr/commands/rename.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2520
Closes https://github.com/sxyazi/yazi/issues/2520
---
Now you will be able to have something like this to place the cursor on the next file after renaming:
```lua
return {
setup = function()
ps.sub("rename", function()
ya.mgr_emit("arrow", { "next" })
end)
end,
}
```
DDS docs: https://yazi-rs.github.io/docs/dds

feat: allow repositioning the cursor in the `rename` DDS event

---

yazi-config/preset/theme-dark.toml
yazi-config/preset/theme-light.toml
yazi-config/src/theme/theme.rs
yazi-plugin/preset/components/entity.lua

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2516
Closes https://github.com/sxyazi/yazi/issues/2516

feat: new `symlink_target` to style the target of symbolic links

---

yazi-cli/src/package/hash.rs
yazi-config/src/keymap/chord.rs
yazi-config/src/keymap/deserializers.rs
yazi-config/src/keymap/keymap.rs
yazi-config/src/keymap/mod.rs
yazi-config/src/keymap/rules.rs
yazi-config/src/lib.rs
yazi-config/src/opener/opener.rs
yazi-config/src/platform.rs
yazi-plugin/src/utils/layer.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2509
Closes https://github.com/sxyazi/yazi/issues/2509
---
This PR adds a new *optional* `for` field to key bindings to specify the platform the key binding applies to.
For example:
```sh
{ on = [ "g", "d" ], run = "cd ~/dev",  desc = "Go dev",    for = "unix" },
{ on = [ "g", "d" ], run = 'cd C:\dev', desc = 'Go C:\dev', for = "windows" },
```
The available values ​​of `for` are the same as https://yazi-rs.github.io/docs/configuration/yazi#opener

feat: platform-specific key binding

---

yazi-core/src/mgr/commands/bulk_rename.rs

When handling numerous filenames, it's better to give indication to original filenames. I've added the original filenames below, separated by a divider, without changing the code related to renaming.

feat: allow bulk renaming to include trailing content in addition to the required new names

---

Cargo.lock
yazi-adapter/Cargo.toml
yazi-config/preset/keymap-default.toml
yazi-core/src/tasks/commands/close.rs
yazi-core/src/tasks/commands/mod.rs
yazi-core/src/tasks/commands/show.rs
yazi-fm/src/executor.rs

The `tasks_show` and `close_input` commands were introduced for cross-layer command invocation:
- `[manager]` calls the `[tasks]`'s `show` command to open the task manager
- `[cmp]` calls the `[input]`'s `close` command to close the input after completion
With https://github.com/sxyazi/yazi/pull/2399, Yazi now supports cross-layer command invocation in a more comprehensive and unified manner, making these two commands unnecessary.
`tasks_show` has been replaced by `tasks:show`:
```diff
- { on = "w", run = "tasks_show" },
+ { on = "w", run = "tasks:show" },
```
`close_input` has been replaced by `input:close`:
```diff
- { on = "<Enter>", run = [ "close --submit", "close_input --submit" ] },
+ { on = "<Enter>", run = [ "close --submit", "input:close --submit" ] },
```

refactor!: remove unnecessary `tasks_show` and `close_input` commands

---

yazi-config/preset/yazi-default.toml
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/svg.lua
yazi-plugin/src/loader/loader.rs

This should noticeably speed up previews and thumbnail generation when using `magick`. Also, the size of the thumbnail files should be smaller, especially when images have a landscape orientation.
Some numbers:
**AVIF**
Before:
```
Benchmark 1: taskset -c 19 magick -density 200 IMG_001.avif -flatten -resize 600x900^ -quality 75 -auto-orient JPG:IMG_001_th
Time (mean ± σ):      4.148 s ±  0.002 s    [User: 3.953 s, System: 0.156 s]
Range (min … max):    4.144 s …  4.151 s    10 runs
```
After:
```
Benchmark 1: taskset -c 19 magick IMG_001.avif -auto-orient -strip -sample 600x -flatten -quality 75 JPG:IMG_001_th
Time (mean ± σ):     844.7 ms ±   2.0 ms    [User: 740.8 ms, System: 93.8 ms]
Range (min … max):   841.8 ms … 848.3 ms    10 runs
```
**HEIF**
Before:
```
Benchmark 1: taskset -c 19 …
```

perf!: faster image preview with optimized `magick` arguments

---

.github/workflows/check.yml
Cargo.lock
Cargo.toml
yazi-config/preset/keymap-default.toml
yazi-core/src/cmp/commands/arrow.rs
yazi-core/src/confirm/commands/arrow.rs
yazi-core/src/help/commands/arrow.rs
yazi-core/src/pick/commands/arrow.rs
yazi-core/src/spot/commands/arrow.rs
yazi-core/src/spot/commands/swipe.rs
yazi-core/src/tab/folder.rs
yazi-core/src/tasks/commands/arrow.rs
yazi-fs/src/step.rs
yazi-plugin/src/elements/table.rs
yazi-plugin/src/utils/spot.rs
yazi-proxy/src/tab.rs

Follow up to https://github.com/sxyazi/yazi/pull/2485
With this PR, all components now support wraparound navigation and have it enabled by default to maintain overall interaction consistency. 
The old `arrow -1` and `arrow 1` can still be used to preserve the previous behavior.

feat!: support `arrow prev` and `arrow next` for more components

---

yazi-boot/src/actions/debug.rs
yazi-config/preset/keymap-default.toml
yazi-core/src/tab/commands/follow.rs
yazi-core/src/tab/commands/mod.rs
yazi-fm/src/executor.rs
yazi-fs/src/path.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2437
Closes https://github.com/sxyazi/yazi/issues/2437
---
A new `g` => `f` keybind (Follow hovered symlink) has been added to use the feature.

feat: new `follow` command to follow files pointed to by symlinks

---

yazi-config/preset/keymap-default.toml
yazi-core/src/mgr/commands/paste.rs
yazi-core/src/mgr/commands/remove.rs
yazi-core/src/tab/commands/escape.rs
yazi-core/src/tab/commands/toggle_all.rs
yazi-core/src/tab/selected.rs
yazi-macro/src/event.rs
yazi-plugin/preset/plugins/fzf.lua
yazi-shared/src/event/cmd.rs

See https://github.com/sxyazi/yazi/issues/2546
Closes https://github.com/sxyazi/yazi/issues/2546
The default behavior of the keys `z` and `Z` are swapped.
You can use custom keybinds to keep the original behavior if that's preferred:
```sh
{ on = "z", run = "plugin zoxide" },
{ on = "Z", run = "plugin fzf" },
```

feat!: enhance `fzf` integration

---

yazi-plugin/src/elements/pad.rs
yazi-plugin/src/elements/rect.rs

This PR deprecates `ui.Padding` in favor of the new `ui.Pad`, which uses the same [parameter order as CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/padding#syntax). This change makes it possible to further simplify syntax in the future:
```diff
- ui.Padding(left, right, top, bottom)
+ ui.Pad(top, right, bottom, left)
```
The `padding()` method of `ui.Rect` is also deprecated to align with the new `ui.Pad` naming:
```diff
- ui.Rect.default:padding(padding)
+ ui.Rect.default:pad(pad)
```
The old `ui.Padding` and `ui.Rect:padding()` are still available, but will trigger a warning.

refactor: deprecate `ui.Padding` and `ui.Rect:padding()`

---

yazi-core/src/mgr/commands/create.rs
yazi-core/src/mgr/commands/open.rs
yazi-core/src/mgr/commands/remove.rs
yazi-core/src/mgr/commands/rename.rs
yazi-core/src/tab/commands/cd.rs
yazi-core/src/tab/commands/filter.rs
yazi-core/src/tab/commands/find.rs
yazi-core/src/tab/commands/search.rs
yazi-core/src/tab/commands/shell.rs
yazi-proxy/src/options/search.rs
yazi-proxy/src/tab.rs

With this PR, you will be able to initialize the input components when running `create`, `rename`, `cd`, `filter`, `find`, `search`, and `shell` commands, for example:
```sh
{ on = "r", run = [ "rename", "input:escape" ] }
```
This will open the rename input box and exit insert mode, meaning the default state will be normal mode.

feat: allow initializing input when opening it with commands like `rename`, `create`, `find`, `filter`, etc.

---

yazi-plugin/src/elements/text.rs
yazi-plugin/src/utils/preview.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2531
Closes https://github.com/sxyazi/yazi/issues/2531
---
```lua
local x, y = 10, 0
ui.Text("Never say never"):scroll(x, y)
```

feat: new `ui.Text:scroll()` API for setting text to scroll horizontally or vertically

---

yazi-config/preset/yazi-default.toml
yazi-plugin/preset/plugins/magick.lua

~Fixes https://github.com/sxyazi/yazi/issues/2598~ This limits the memory available to `magick`, but regardless, `magick` tries to scale the image anyway and fails. This is very wasteful, therefore it is not a solution.

feat: limit memory usage for previewing large images

---

yazi-plugin/preset/plugins/video.lua

Currently, Yazi only scales thumbnails to `preview.max_height`, which means that thumbnails of videos in landscape orientation are unnecessarily large.
```
max_width       = 600
max_height      = 900
image_quality   = 75
```
File size: 131 kB
Image size: 1600x900
On the left is a preview in Yazi, and on the right is a generated thumbnail.
File size: 28 kB
Image size: 600x338

fix: respect the user's `max_width` setting for the built-in video previewer

---

yazi-core/src/mgr/commands/close.rs
yazi-core/src/mgr/commands/open.rs
yazi-core/src/mgr/commands/quit.rs
yazi-fm/src/app/commands/quit.rs
yazi-fm/src/panic.rs
yazi-fm/src/term.rs
yazi-shared/src/event/data.rs
yazi-shared/src/event/event.rs

Hi! Very cool project, I recently started using it and have a (not too obscure in my opinion) use case: When integrating yazi with other tools, it is useful to be able to return with a non-zero exit code. An example for this is the pager for https://github.com/aurutils/aurutils 
I don't think it is possible to do this via a plugin (except for maybe somehow purposefully panicking from lua), so I added an option to the quit command.
Hope this is helpful.

feat: allow custom exit code with `quit --code`

---

yazi-binding/src/macros.rs
yazi-binding/src/url.rs
yazi-fm/src/lives/files.rs
yazi-fm/src/lives/folder.rs
yazi-fm/src/lives/preference.rs
yazi-fm/src/lives/preview.rs
yazi-fm/src/lives/tab.rs
yazi-fm/src/lives/tasks.rs
yazi-plugin/src/bindings/icon.rs
yazi-plugin/src/config/plugin.rs
yazi-plugin/src/macros.rs
yazi-plugin/src/process/output.rs

See https://github.com/mlua-rs/mlua/issues/557

feat: copy-on-write support for field caching

---

yazi-core/src/mgr/commands/update_files.rs
yazi-core/src/mgr/watcher.rs

Fixes https://github.com/sxyazi/yazi/issues/2642

fix: lazily update files to avoid triggering issues dependent on sort order

---

yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/parent.lua
yazi-plugin/preset/components/preview.lua
yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/code.lua
yazi-plugin/preset/plugins/dds.lua
yazi-plugin/preset/plugins/empty.lua
yazi-plugin/preset/plugins/extract.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/preset/plugins/fzf.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/preset/plugins/mime.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/session.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/preset/plugins/zoxide.lua
yazi-plugin/src/utils/call.rs
yazi-plugin/src/utils/utils.rs
yazi-shared/src/event/cmd.rs

This PR introduces a new `ya.emit()` API to address:
- The existing `ya.mgr_emit()` API can only emit events to `[manager]`.
- The existing `ya.app_emit()` and `ya.input_emit()` can be used to emit events to `[app]` and `[input]`, but they are private and undocumented APIs.
- There is no available API to send events to `[tasks]`, `[spot]`, `[pick]`, `[confirm]`, `[cmp]`, or `[help]`.
The first parameter of `ya.emit()` is the event ID in the format `component:event`, where the `component:` part is optional and defaults to `[manager]`, for example:
```lua
ya.emit("arrow", { 1 })  -- Emit an "arrow" event to [manager]
ya.emit("cmp:arrow", { 1 })  -- Emit an "arrow" event to [cmp]
```
The second parameter is the parameters for the event.
`ya.emit()` can be used as a direct replacement for …

feat: new `ya.emit()` API

---

yazi-adapter/src/brand.rs
yazi-config/src/popup/options.rs
yazi-core/src/input/commands/show.rs
yazi-core/src/input/input.rs
yazi-core/src/mgr/mgr.rs
yazi-core/src/mgr/tabs.rs
yazi-plugin/preset/plugins/extract.lua
yazi-plugin/src/utils/layer.rs
yazi-widgets/src/input/commands/move_.rs
yazi-widgets/src/input/input.rs
yazi-widgets/src/input/snap.rs
yazi-widgets/src/input/snaps.rs
yazi-widgets/src/input/widget.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2671
Closes https://github.com/sxyazi/yazi/issues/2671
```lua
local value = ya.input {
title = "Password:",
obscure = true,
position = { "center", w = 50 },
}
```

feat: obscure input component for inputting passwords

---

yazi-config/src/keymap/key.rs
yazi-fs/src/calculator.rs
yazi-fs/src/fns.rs
yazi-fs/src/lib.rs
yazi-scheduler/src/file/file.rs
yazi-scheduler/src/prework/prework.rs

This PR greatly improves directory computation performance by dividing the task into chunks and reusing existing threads. Directory sorting and file trashing will be observably twice as fast.
By leveraging chunking, it now can produce real-time directory statistics reports. This means that for a large directory, you will be able to see the process of size changes in real-time, which is beneficial for the upcoming `fs.dir_size()` API.
The new implementation is still async cancelable, which is important for using `fs.dir_size()` in spotters, as it will allow canceling a still-incomplete directory computation when quickly switching between files, thereby avoiding wasted resources.
```rust
let p = std::path::Path::new("/tmp/yazi");
let now = std::time::Instant::now(); …
```

perf: double directory size calculation speed

---

yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/empty.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/image.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/svg.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/src/bindings/calculator.rs
yazi-plugin/src/bindings/chan.rs
yazi-plugin/src/elements/text.rs
yazi-plugin/src/fs/fs.rs
yazi-plugin/src/process/child.rs
yazi-plugin/src/process/command.rs
yazi-plugin/src/utils/image.rs
yazi-plugin/src/utils/json.rs
yazi-plugin/src/utils/layer.rs
yazi-plugin/src/utils/preview.rs
yazi-plugin/src/utils/utils.rs

Before this change, when `ya.image_info()` and `ya.image_show()` failed, there was no way to determine the reason for the failure. 
With this PR, a new second return value has been added to them, in the event of a failure, it will carry an [`Error`](https://yazi-rs.github.io/docs/plugins/types/#shared.error) userdata that provides the caller with the error message.
All built-in image previewers in Yazi have been updated to support this, that is, when an image preview fails, the error will be displayed in the preview pane so that the user knows what went wrong.
`ya.preview_widgets()` has been deprecated and replaced by the new `ya.preview_widget()`:
```diff
- ya.preview_widgets(job, { ui.Text("..."):area(job.area) })
+ ya.preview_widget(job, { ui.Text("..."):area(job.area) })
```
In …

feat: show error when image preview fails

---

Cargo.lock
yazi-adapter/Cargo.toml
yazi-adapter/src/drivers/sixel.rs
yazi-config/preset/yazi-default.toml
yazi-config/src/preview/preview.rs
yazi-plugin/src/config/runtime.rs
yazi-plugin/src/elements/text.rs

See https://github.com/sxyazi/yazi/issues/2681
Closes https://github.com/sxyazi/yazi/issues/2681
---
This PR replaces the existing neural network quantization algorithm with Wu's Color Quantizer, which offers [better performance](https://github.com/Ivordir/quantette/blob/main/docs/Benchmarks%20and%20Accuracy.md#time) while [maintaining comparable quality](https://github.com/Ivordir/quantette/blob/main/docs/Benchmarks%20and%20Accuracy.md#accuracydssim).
I've integrated the new algorithm into Yazi's Sixel encoding process, and the benchmark has shown that the speed is 9 times faster than before.
Old implementation (neural network via [`color_quant`](https://github.com/image-rs/color_quant)) – average 189.5763999ms:
```sh
time: 190.025ms
time: 191.054417ms
time: 187.696792ms
time: …
```

feat!: 9x faster Sixel image preview

---

yazi-core/src/tab/commands/copy.rs

Similar to the `open`, `rename` and `remove` commands, the `--hovered` flag will cause the copy command to operate only on the hovered file.

feat: add `--hovered` to the `copy` command

---

yazi-adapter/src/drivers/kgp.rs
yazi-adapter/src/emulator.rs
yazi-core/src/tab/commands/arrow.rs
yazi-fm/src/term.rs

Closes https://github.com/sxyazi/yazi/issues/2725

fix: avoid tmux interfering with kitty graphical sequences

---

yazi-term/Cargo.toml

Closes #2727
it makes yazi-cli buildable on windows

fix: `windows-sys` missing a `Win32_Security` feature

---

yazi-config/preset/theme-dark.toml
yazi-config/preset/theme-light.toml
yazi-config/src/theme/theme.rs
yazi-plugin/preset/components/header.lua
yazi-plugin/preset/components/root.lua
yazi-plugin/preset/components/tabs.lua
yazi-plugin/src/config/theme.rs
yazi-plugin/src/lua.rs

This PR decouples tabs from the header into an independent tab bar component to enhance UX:
- Standalone single-line component to increase the available space for displaying tabs
- Tab titles are displayed by default to increase recognizability
- Supports switching tabs via mouse for easier navigation
The new tab bar is only shown when there is more than one tab, ensuring no space waste for users who don't use tabs.
Closes https://github.com/sxyazi/yazi/issues/1403
Closes https://github.com/sxyazi/yazi/pull/2702
```toml
[tabs]
active   = { fg = "#24273a", bg = "#8aadf4", bold = true }
inactive = { fg = "#8aadf4", bg = "#363a4f" }
```
https://github.com/user-attachments/assets/5ac79095-9a4a-444e-894a-e6ee0e992815
- `tab_active` and `tab_inactive` have been moved to the new `[tabs]` section …

feat!: redesign tabs

---

Cargo.lock
Cargo.toml
yazi-binding/src/error.rs
yazi-binding/src/url.rs
yazi-fm/src/main.rs
yazi-plugin/Cargo.toml
yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/mime.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/preset/plugins/zoxide.lua
yazi-plugin/src/composer.rs
yazi-plugin/src/lib.rs
yazi-plugin/src/process/command.rs
yazi-plugin/src/utils/text.rs
yazi-plugin/src/utils/utils.rs

Initially, the `args()` method was introduced to be consistent with [Rust's `args()`](https://doc.rust-lang.org/std/process/struct.Command.html#method.args), but in practice it turned out to be not significant, since Lua's method arguments can be of any type and most of the existing APIs work the same task with different parameters passed to a same method.
So, this PR adds support for table parameter types to the existing [`arg()`](https://yazi-rs.github.io/docs/plugins/utils/#Command.arg) method (in addition to the previously supported single string parameter) and serves as a direct replacement for `args()`.
```diff
- Command("ls"):args { "-a", "-l" }
+ Command("ls"):arg { "-a", "-l" }
```

refactor: deprecate the `Command:args()` method

---

yazi-cli/src/args.rs
yazi-cli/src/main.rs

This PR deprecates the `ya pack` subcommand and introduces the new `ya pkg` command as its replacement.
The old `ya pack` uses options to indicate the current action, such as `-a` to add a package:
```sh
ya pack -a owner/my-plugin
```
However, because options are not unique and multiple options can be combined semantically, this leads to ambiguity. For example, specifying both the add (`-a`) and the list (`-l`) options at the same time:
```sh
ya pack -a owner/my-plugin -l
```
This also limits the possibility of adding more options for certain operations. For instance, [adding a new option (`-f`)](https://github.com/sxyazi/yazi/issues/2735) to indicate forced deletion for the delete action (`-d`):
```sh
ya pack -d owner/my-plugin -f
```
But since `-f` is at the same level as `-d`, it's …

feat: new `ya pkg` subcommand

---

.github/pull_request_template.md
yazi-plugin/preset/components/modal.lua
yazi-plugin/preset/components/parent.lua
yazi-plugin/preset/components/progress.lua
yazi-plugin/preset/components/rail.lua
yazi-plugin/preset/components/root.lua
yazi-plugin/preset/components/status.lua
yazi-plugin/preset/components/tab.lua
yazi-plugin/preset/components/tabs.lua
yazi-plugin/src/elements/elements.rs
yazi-plugin/src/elements/utils.rs
yazi-plugin/src/utils/call.rs
yazi-plugin/src/utils/utils.rs

Resolves https://github.com/sxyazi/yazi/discussions/2780
With this PR, you can more easily replace the default tab bar with a custom one.
For example, the following code mimics the old version of Yazi's tab bar, where the tab bar is positioned at the right side of the header instead of on its own line:
```lua
function Tabs.height() return 0 end
Header:children_add(function()
if #cx.tabs == 0 then return "" end
local spans = {}
for i = 1, #cx.tabs do
spans[#spans + 1] = ui.Span(" " .. i .. " ")
end
spans[cx.tabs.idx]:reverse()
return ui.Line(spans)
end, 9000, Header.RIGHT)
```
For the currently active tab, the `reverse()` style is applied, but you can add any style you like, https://yazi-rs.github.io/docs/plugins/layout/#style

feat: make custom tab bar easier

---

Cargo.lock
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/header.lua
yazi-plugin/preset/components/marker.lua
yazi-plugin/preset/components/rail.lua
yazi-plugin/preset/components/status.lua
yazi-plugin/preset/plugins/archive.lua
yazi-plugin/preset/plugins/empty.lua
yazi-plugin/preset/plugins/file.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/image.lua
yazi-plugin/preset/plugins/json.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/svg.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/src/elements/align.rs
yazi-plugin/src/elements/bar.rs
yazi-plugin/src/elements/border.rs
yazi-plugin/src/elements/edge.rs
yazi-plugin/src/elements/elements.rs
yazi-plugin/src/elements/line.rs
yazi-plugin/src/elements/mod.rs
yazi-plugin/src/elements/text.rs
yazi-plugin/src/elements/wrap.rs
yazi-plugin/src/utils/preview.rs
yazi-plugin/src/utils/spot.rs

This PR extracts alignment, border type, and wrapping constants from `ui.Line`, `ui.Text`, `ui.Bar`, and `ui.Border` into the new `ui.Align`, `ui.Wrap`, and `ui.Edge`, respectively. Since these constants are used by multiple UI elements, treating them as separate types makes more sense.
I have recently been working on the [Yazi Lua API type definitions](https://github.com/yazi-rs/plugins/tree/main/types.yazi) project, which has also made it easier to define and restrict their types there.
These constants have been extracted into the new `ui.Align` while retaining their original names, for example:
```diff
- ui.Line.CENTER
+ ui.Align.CENTER
```
These constants have been extracted into the new `ui.Edge` while maintaining their original names, for example:
```diff
- ui.Bar.ALL
+ ui.Edge.ALL …
```

feat: new `ui.Align`, `ui.Wrap`, and `ui.Edge`

---

yazi-fs/src/files.rs
yazi-shared/src/url/urn.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/discussions/2565, https://github.com/sxyazi/yazi/issues/2894
---
The search view flatly shows search results, for example, `a/b/c.txt`, where `a/b` is the prefix and `c.txt` is the file name.
Previously, users could only use the `filter` command to filter for the file name portion (`c.txt`) within the search results. 
With this PR, the full path `a/b/c.txt` can now be filtered, which makes it more intuitive, as users should be able to filter for the path as they see it in the list, rather than only the final part of it.
https://github.com/user-attachments/assets/ed9798af-345b-43bc-9a21-a8762178d053

feat: `filter` by full path (prefix + filename) in search view instead of just filename

---

yazi-config/preset/theme-dark.toml
yazi-config/preset/theme-light.toml
yazi-config/preset/yazi-default.toml
yazi-config/src/popup/confirm.rs
yazi-config/src/popup/options.rs
yazi-config/src/theme/theme.rs
yazi-core/src/confirm/commands/show.rs
yazi-core/src/confirm/confirm.rs
yazi-fm/src/confirm/body.rs
yazi-fm/src/confirm/confirm.rs
yazi-fm/src/confirm/mod.rs
yazi-plugin/src/config/theme.rs
yazi-plugin/src/elements/pos.rs
yazi-plugin/src/macros.rs
yazi-plugin/src/utils/layer.rs

Follow up to https://github.com/yazi-rs/yazi-rs.github.io/commit/5db68d0a8ed9026aba3c51a13e7479ceb2f24e01
---
This PR makes the final changes to `ya.confirm()` and `ui.Pos()` before going public, and these changes are now reflected in the documentation:
- `ya.confirm()`: https://yazi-rs.github.io/docs/plugins/utils#ya.confirm
- `ui.Pos()`: https://yazi-rs.github.io/docs/plugins/layout#pos
A confirmation consists of three parts:
- Top: the title
- Middle: the confirmation prompt text
- Bottom: an additional list shown upon confirmation, such as a file list when deleting files
Previously, the middle part was referred to as `content`, but this was inaccurate because all parts except the title are "content" (i.e. the middle and bottom parts). So, the middle part is now changed to `body` from …

feat!: make `ya.confirm()` and `ui.Pos()` public API

---

.github/workflows/draft.yml
Cargo.lock
scripts/build.sh
yazi-fm/Cargo.toml
yazi-packing/Cargo.toml

Added packaging of already built binary files into a valid deb package.
Tested on Ubuntu 24.04
I haven't had a chance to test on different Ubuntu/Debian versions, but as far as I can tell, resulting deb file doesn't have any distribution and version-specific features. So it should work everywhere.
Besides bin files the package installs completion for bash, README.md, LICENSE all dependencies specified in the documentation
recommended way to install the deb package:
```
sudo apt install ./yazi-fm_<version>.deb
```
list of files:
```
❯ dpkg-query -L yazi-fm
/usr
/usr/share
/usr/share/bash-completion
/usr/share/bash-completion/completions
/usr/share/bash-completion/completions/ya
/usr/share/bash-completion/completions/yazi
/usr/share/doc
/usr/share/doc/yazi-fm
/usr/share/doc/yazi-fm/README …
```

feat: support `.deb` packages

---

yazi-config/preset/yazi-default.toml

All platforms fails to play media file if "mpv" is not installed. There is also no response shown.
The default `open --interactive` menu for Media type is: 
https://github.com/sxyazi/yazi/blob/917e1f54a10445f2e25147c4b81a3c77d8233632/yazi-config/preset/yazi-default.toml#L68-L69
For most platforms, `mpv` is not built in. This PR forces `"play"` to use the default associated application defined in the OS, so that it is always responsive when pressing "Enter" (which triggers [mgr open](https://yazi-rs.github.io/docs/configuration/keymap#mgr.open) and first item in `use` list: "play"`).

fix: respect user's system media opener instead of hardcoding `mpv`

---

yazi-config/preset/yazi-default.toml

For media types, Unix has "Show media info" option from interactive open. Windows doesn't.
Make the feature available for Windows as well.

feat: new "Show media info" for `play` opener on Windows

---

yazi-widgets/src/input/commands/commands.rs

Fixes https://github.com/sxyazi/yazi/issues/2972

fix: `stringify!(r#move)` is `"r#move"` instead of `"move"`

---

README.md

Finally fixed Rio image clearing issues, sorry for the delay

docs: update Rio image support status

---

yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-cli/src/package/delete.rs
yazi-cli/src/package/dependency.rs
yazi-cli/src/package/deploy.rs
yazi-cli/src/package/hash.rs
yazi-dds/src/ember/ember.rs
yazi-parser/src/app/plugin.rs
yazi-plugin/src/isolate/peek.rs
yazi-plugin/src/loader/loader.rs
yazi-plugin/src/loader/require.rs
yazi-plugin/src/utils/utils.rs
yazi-shared/src/bytes.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2781
Closes https://github.com/sxyazi/yazi/issues/2781
---
With this PR, Yazi will support Lua files other than `main.lua` as plugin entry points. To achieve this, a new dot (`.`) syntax has been introduced. For example:
```sh
~/.config/yazi/plugins/demo.yazi/
├── main.lua
├── foo.lua
├── bar.lua
├── README.md
└── LICENSE
```
Now, in the [`plugin` command](https://yazi-rs.github.io/docs/plugins/overview#functional-plugin), and fetchers, spotters, preloaders, and previewers rules, in addition to specifying `demo` (which corresponds to `main.lua`) as the entry point as before:
```toml
[[plugin.prepend_previewers]]
mime = "text/*"
run  = "demo"
```
You can also explicitly specify other Lua scripts as entry …

feat: multi-entry support for plugin system

---

yazi-packing/Cargo.toml

The dependency on `fd-find` causes a removal of `fd` due to a noted conflict and if the user has installed `fd` (i.e. from github or via `deb-get` ) because the renamed `fd-find` in their LTS installation is too old they'll suffer a surprise downgrade or get into a blocked situation.
```
$ apt-cache policy fd-find fd
fd-find:
Installed: (none)
Candidate: 8.3.1-1ubuntu0.1
Version table:
8.3.1-1ubuntu0.1 500
500 http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
500 http://gb.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
8.3.1-1 500
500 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
fd:
Installed: 10.3.0
Candidate: 10.3.0
Version table:
*** 10.3.0 100
100 /var/lib/dpkg/status
```
It might be preferable even to limit the `fd` …

fix: add `fd` as a dependency to the `.deb` packaging workflow

---

yazi-plugin/preset/plugins/extract.lua

Currently, input dialogs use center positioning which breaks visual   
consistency with other UI elements in yazi. This change updates the   
default input positioning to use top-center alignment with a small   
vertical offset, making it more consistent with other popup menus   
and improving the overall user experience.  
Changes:  
- Update default input position from center to top-center with y=2 offset  
- Maintain existing width of 50 characters  
- Ensure consistent visual hierarchy across all popup dialogs  
This addresses the visual inconsistency where input dialogs appeared   
in the center while other menus follow a more structured top-aligned   
layout pattern.

feat: unify the password input visually when extracting archives

---

scripts/build.sh

Fixes https://github.com/sxyazi/yazi/issues/3205
Fixes https://github.com/sxyazi/yazi/pull/3208

fix: wrong architecture label in aarch64 `.deb` packages

---

yazi-core/src/tab/tab.rs
yazi-shared/src/loc/buf.rs
yazi-shared/src/url/buf.rs

Fixes https://github.com/sxyazi/yazi/issues/2104#issuecomment-3364618422
When running the `shell` command in an empty directory, the value of `$0` becomes a `"sh"` string, and `$@` becomes an empty array, even if files are selected in other directories.
With this PR, when in an empty directory (no hovered file), `$0` will be an empty string (`""`), and `$@` will correctly contain the array of selected file paths - to fix this issue, the behavior of `$0` in empty directories has been changed from `"sh"` to `""`. 
The issue was originally introduced in https://github.com/sxyazi/yazi/commit/2efda755f1179c29556fd5c8809247530ef84c00 (`$0` was first supported), since then `$0` has never worked correctly, so this change should not break anything

fix: incorrect `$0` and `$@` parameters in `shell` command under empty directories
