sxyazi/yazi

Cargo.lock
config/yazi.toml
src/config/open/open.rs
src/core/manager/manager.rs
src/core/tasks/tasks.rs
src/misc/mime.rs

Refer to: https://github.com/sxyazi/yazi/pull/8#issuecomment-1650960333

feat: make folder openable

---

README.md

I've uploaded `yazi-bin` package on AUR so this PR updates about it.

docs: add `yazi-bin` AUR package

---

core/src/files/files.rs

This should fix https://github.com/sxyazi/yazi/issues/46

fix: `show_hidden` not working

---

app/src/header/tabs.rs
core/src/manager/tab.rs

Related to https://github.com/sxyazi/yazi/pull/41

fix: tab name width calculating

---

app/src/executor.rs
core/src/external/clipboard.rs
core/src/input/input.rs
core/src/manager/manager.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/70

feat: copy file path, with multi-selection support

---

adaptor/src/adaptor.rs
config/docs/yazi.md
config/preset/yazi.toml
config/src/boot/boot.rs
config/src/lib.rs
config/src/preview/preview.rs
config/src/xdg.rs
core/src/manager/manager.rs
core/src/manager/preview/provider.rs
core/src/tasks/workers/precache.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/92#issuecomment-1697187927
Close https://github.com/sxyazi/yazi/issues/92

feat: new `cache_dir` option

---

app/src/app.rs
config/src/boot/boot.rs
config/src/preview/preview.rs
config/src/theme/theme.rs
config/src/xdg.rs
shared/src/fns.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/94#issuecomment-1700582829
Close https://github.com/sxyazi/yazi/issues/94

feat: new `YAZI_CONFIG_HOME` env variable

---

README.md
config/src/preview/adaptor.rs

Close https://github.com/sxyazi/yazi/issues/98

feat: add Black Box image preview support

---

config/src/boot/boot.rs

feat: deprecate `--cwd` in favor of the positional argument

---

config/src/manager/layout.rs

Fix https://github.com/sxyazi/yazi/issues/136

fix: image position calculation

---

app/src/header/layout.rs
core/src/manager/tab.rs
shared/src/url.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/133
Close https://github.com/sxyazi/yazi/issues/133

feat: show keywords when in search mode

---

config/docs/yazi.md
config/src/pattern.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/146
Close https://github.com/sxyazi/yazi/issues/146

feat: make the glob expr case insensitive by default, and prepend `\s` to make it sensitive

---

core/Cargo.toml
core/src/tasks/workers/file.rs
shared/src/fs.rs

A fix to the issue: https://github.com/sxyazi/yazi/issues/175
Close https://github.com/sxyazi/yazi/issues/175

feat: make `trash` optional

---

app/src/executor.rs
config/docs/keymap.md
core/src/tasks/tasks.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/171
Close https://github.com/sxyazi/yazi/issues/171

feat: new `force` option added for the `remove` command, which does not show the confirmation dialog on trashing/deleting

---

config/src/keymap/key.rs

Close https://github.com/sxyazi/yazi/issues/183

feat: add `BackTab` support

---

core/src/external/shell.rs
core/src/tasks/workers/process.rs

Try to fix https://github.com/sxyazi/yazi/issues/194#issuecomment-1741699511

fix: set stdio to null when orphan is true

---

app/src/executor.rs
core/src/manager/manager.rs

Close https://github.com/sxyazi/yazi/issues/198

feat: new `force` option for creating and renaming

---

core/src/manager/finder.rs
core/src/manager/tab.rs

https://github.com/sxyazi/yazi/assets/33489972/7e143c33-f745-43fb-a70b-edee40d9d386

feat: loop through to find

---

app/src/app.rs
app/src/executor.rs
app/src/signals.rs
config/preset/keymap.toml
core/src/event.rs
core/src/manager/manager.rs

feat: add new options to `quit` command for flexible cwd-file setting

---

core/src/manager/tab.rs

Fix #248 
This PR remove search result from backstack.

avoid adding search to backstack

---

Cargo.lock
core/Cargo.toml
core/src/tasks/workers/file.rs

See https://github.com/Byron/trash-rs/pull/84

feat: support trash for NetBSD

---

adaptor/src/adaptor.rs

Fixes: https://github.com/sxyazi/yazi/issues/274

fix: adapt another `$TERM` value of `foot-extra` for foot

---

yazi-plugin/preset/components/folder.lua

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/297
Close https://github.com/sxyazi/yazi/issues/297

feat: add a new `Folder:icon()` API to make it easier for users to extend icons

---

nix/yazi.nix

Try to fix https://github.com/sxyazi/yazi/issues/303

fix: nix flakes

---

yazi-adaptor/src/adaptor.rs

Docs is here: https://yazi-rs.github.io/usage/faq#why-cant-i-preview-files-on-windows
Close https://github.com/sxyazi/yazi/issues/305

feat: support image preview on WSL

---

yazi-core/src/files/files.rs

Fixes https://github.com/sxyazi/yazi/issues/317

fix: channel blockage caused by fuse permissions under the root user

---

README.md

We can merge this now or wait for https://github.com/yazi-rs/yazi-rs.github.io/pull/16 and update the showcase link as well.

docs: update readme links to website

---

Cargo.lock
yazi-core/Cargo.toml
yazi-core/src/highlighter.rs
yazi-core/src/input/shell.rs
yazi-core/src/preview/preview.rs
yazi-core/src/preview/provider.rs

Close https://github.com/sxyazi/yazi/issues/328

perf: fallback to plain highlighter for long text

---

yazi-core/src/tab/folder.rs
yazi-core/src/tab/tab.rs

Fix https://github.com/sxyazi/yazi/issues/337

fix: the parent does not hover properly on switching the hidden state

---

yazi-core/src/tab/folder.rs
yazi-fm/src/app.rs

Close #348 
- Precache n+1/n-1 page for better experience. (n - 1 also has this problem, run `yazi` and press `G`)
https://github.com/sxyazi/yazi/assets/9482395/f4d1127e-588a-49e7-bc03-2d62c91c2767

fix: precache n-1 and n+1 pages

---

yazi-fm/src/completion/completion.rs

Allow displaying more contents without breaking visualization

feat: make width of completion relative to input

---

yazi-core/src/manager/commands/quit.rs
yazi-core/src/tasks/tasks.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/286
Close https://github.com/sxyazi/yazi/issues/286

feat: display the number of deleted files in the prompt

---

Cargo.lock
yazi-core/src/completion/commands/show.rs
yazi-fm/Cargo.toml
yazi-fm/src/app.rs
yazi-fm/src/main.rs
yazi-fm/src/panic.rs
yazi-shared/src/cha.rs
yazi-shared/src/term/term.rs

Fix https://github.com/sxyazi/yazi/issues/356

fix: Rust panics instead of returning an error when file times are invalid

---

yazi-config/src/boot/boot.rs
yazi-config/src/boot/cli.rs
yazi-core/src/manager/commands/create.rs
yazi-core/src/manager/tabs.rs
yazi-core/src/tab/commands/reveal.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/344
Close https://github.com/sxyazi/yazi/issues/344

feat: add support for opening a file on startup

---

Cargo.toml

Well I just added additional optimizations options for file size.

feat: Add more optimization options

---

Cargo.lock
yazi-core/src/completion/commands/close.rs
yazi-core/src/completion/commands/trigger.rs
yazi-core/src/event.rs
yazi-core/src/input/commands/close.rs
yazi-core/src/input/commands/complete.rs
yazi-core/src/input/commands/escape.rs
yazi-core/src/manager/commands/create.rs
yazi-core/src/manager/commands/hover.rs
yazi-core/src/manager/commands/mod.rs
yazi-core/src/manager/commands/refresh.rs
yazi-core/src/manager/commands/rename.rs
yazi-core/src/manager/manager.rs
yazi-core/src/manager/tabs.rs
yazi-core/src/manager/watcher.rs
yazi-core/src/tab/commands/arrow.rs
yazi-core/src/tab/commands/cd.rs
yazi-core/src/tab/commands/enter.rs
yazi-core/src/tab/commands/jump.rs
yazi-core/src/tab/commands/leave.rs
yazi-core/src/tab/commands/reveal.rs
yazi-core/src/tab/commands/search.rs
yazi-fm/src/app.rs
yazi-fm/src/executor.rs

Try to fix https://github.com/sxyazi/yazi/issues/374
https://github.com/sxyazi/yazi/assets/17523360/3561aa7b-a24c-4fd0-82f0-9089d8d14fcb

fix: directories are recreated after deletion did not update the watcher tracking properly

---

yazi-config/preset/keymap.toml
yazi-config/src/popup/offset.rs
yazi-core/src/help/commands/filter.rs
yazi-core/src/help/help.rs
yazi-core/src/input/commands/backspace.rs
yazi-core/src/input/commands/forward.rs
yazi-core/src/input/commands/kill.rs
yazi-core/src/input/commands/mod.rs
yazi-core/src/input/commands/type_.rs
yazi-fm/src/executor.rs

Prepare for https://github.com/sxyazi/yazi/issues/370

feat: make emacs readline keybindings configurable

---

yazi-core/src/files/sorter.rs
yazi-core/src/manager/commands/rename.rs
yazi-core/src/manager/watcher.rs

Try to fix https://github.com/sxyazi/yazi/issues/390

fix: stepwise renaming causes uncertain sorting order

---

yazi-plugin/preset/components/folder.lua
yazi-plugin/preset/utils.lua

Fix https://github.com/sxyazi/yazi/issues/413

fix: crashes when selection indicator exceeds the visible area while a wrong `folder_offset` specified

---

yazi-config/preset/yazi.toml
yazi-config/src/tasks/tasks.rs
yazi-core/src/files/sorter.rs
yazi-scheduler/src/running.rs
yazi-scheduler/src/scheduler.rs
yazi-scheduler/src/task.rs

this is my attempt at sxyazi/yazi#366, following the description in the issue/on discord
I did some minimal testing and it works but it could do with more testing. let me know if you want me to change something, I haven't written much Rust and I'd like to learn 😊
closes sxyazi/yazi#366

feat: new config option to suppress pre-caching tasks

---

Cargo.lock
yazi-core/src/input/commands/paste.rs
yazi-core/src/input/input.rs
yazi-core/src/tab/commands/copy.rs
yazi-plugin/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-scheduler/src/external/clipboard.rs
yazi-shared/src/env.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/444 - @baitian752
Close https://github.com/sxyazi/yazi/issues/444

feat: copy content over SSH

---

yazi-adaptor/src/adaptor.rs
yazi-fm/Cargo.toml
yazi-fm/src/app/app.rs
yazi-fm/src/app/commands/mod.rs
yazi-fm/src/app/commands/render.rs
yazi-fm/src/app/commands/stop.rs
yazi-fm/src/help/layout.rs
yazi-fm/src/input/input.rs
yazi-fm/src/select/select.rs
yazi-fm/src/tasks/layout.rs
yazi-fm/src/which/layout.rs
yazi-plugin/Cargo.toml
yazi-plugin/src/isolate/peek.rs

Try to fix https://github.com/sxyazi/yazi/issues/456

fix: panic caused by `set_hook`

---

Cargo.lock
yazi-adaptor/Cargo.toml
yazi-adaptor/src/image.rs

feat: image orientation support

---

yazi-config/preset/theme.toml
yazi-config/src/theme/icon.rs
yazi-config/src/theme/style.rs
yazi-config/src/theme/theme.rs
yazi-fm/src/lives/folder.rs
yazi-fm/src/lives/lives.rs
yazi-plugin/preset/components/folder.lua
yazi-plugin/src/bindings/icon.rs
yazi-plugin/src/bindings/mod.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/402 - @dlvhdr, and https://github.com/sxyazi/yazi/issues/458 - @fufexan
- Close #402
- Close #458

feat: icon color and ordered icon rules support

---

yazi-core/src/tab/commands/filter.rs

fix: update paged files after filter done

---

Cargo.lock
yazi-config/preset/keymap.toml
yazi-config/preset/theme.toml
yazi-config/preset/yazi.toml
yazi-config/src/theme/filetype.rs
yazi-fm/src/lives/folder.rs
yazi-plugin/src/bindings/cha.rs
yazi-shared/src/fs/cha.rs
yazi-shared/src/fs/file.rs
yazi-shared/src/fs/fns.rs

Closes #262
This adds support for highlighting executable files and symlinks.

feat: add support for highlighting by file type

---

scripts/publish.sh
yazi-shared/src/term/term.rs

fix: can't clear screen and restore cursor when exit on Windows

---

yazi-plugin/preset/plugins/mime.lua

fix: follow symlinks when detecting mime-type on Windows

---

yazi-config/preset/yazi.toml
yazi-fm/src/which/layout.rs
yazi-plugin/preset/plugins/file.lua
yazi-plugin/src/elements/paragraph.rs
yazi-plugin/src/loader.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/51#issuecomment-1780952363 by @magnetophon

feat: add `file(1)` as the file fallback previewer

---

Cargo.lock
yazi-config/src/keymap/mod.rs
yazi-config/src/plugin/mod.rs
yazi-fm/Cargo.toml
yazi-fm/src/app/commands/mod.rs
yazi-fm/src/app/commands/resume.rs
yazi-fm/src/app/commands/stop.rs
yazi-fm/src/executor.rs
yazi-fm/src/signals.rs
yazi-plugin/src/process/child.rs
yazi-plugin/src/utils/plugin.rs
yazi-scheduler/src/scheduler.rs
yazi-shared/src/event/event.rs

Closes https://github.com/sxyazi/yazi/issues/555

feat: allow the spawned child processes to suspend

---

yazi-config/preset/yazi.toml
yazi-config/src/popup/options.rs
yazi-core/src/tab/commands/search.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/549 by @RioNight
Closes https://github.com/sxyazi/yazi/issues/549

feat: improve search input title

---

yazi-config/preset/keymap.toml
yazi-fm/src/executor.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/542 by @paletochen
Closes https://github.com/sxyazi/yazi/issues/542

feat: support submit completion and input at once by using `<Enter>` key

---

yazi-core/src/folder/folder.rs
yazi-core/src/tab/tab.rs

Fixes https://github.com/sxyazi/yazi/issues/580 - @knodalyte

fix: parent folder not tracking CWD

---

yazi-scheduler/Cargo.toml
yazi-scheduler/src/file/file.rs

Fixes https://github.com/sxyazi/yazi/issues/598

feat: make `trash` crate optional on Android

---

yazi-core/src/folder/folder.rs
yazi-core/src/folder/mod.rs
yazi-core/src/folder/stage.rs
yazi-core/src/tab/preview.rs
yazi-core/src/tab/tab.rs

Fixes https://github.com/sxyazi/yazi/issues/596

perf: use lazy sorting when loading large directories to reduce unnecessary CPU consumption

---

yazi-fm/src/app/commands/plugin.rs
yazi-fm/src/lives/lives.rs
yazi-plugin/preset/ya.lua
yazi-plugin/src/cast.rs
yazi-plugin/src/isolate/entry.rs
yazi-plugin/src/isolate/isolate.rs
yazi-plugin/src/isolate/peek.rs
yazi-plugin/src/isolate/seek.rs
yazi-plugin/src/opt.rs
yazi-plugin/src/utils/plugin.rs
yazi-plugin/src/utils/time.rs

Docs here https://yazi-rs.github.io/docs/plugins/overview#async-context

feat: calling sync functions within the async plugin

---

.github/workflows/check.yml
.github/workflows/no-response.yml
.github/workflows/release.yml
.github/workflows/test.yml

Adds a "check" workflow to run Clippy and rustfmt, also makes the workflows a little more consistent across files.

ci: add clippy/rustfmt workflow

---

yazi-config/preset/yazi.toml
yazi-core/src/lib.rs
yazi-core/src/notify/commands/mod.rs
yazi-core/src/notify/commands/push.rs
yazi-core/src/notify/commands/tick.rs
yazi-core/src/notify/level.rs
yazi-core/src/notify/message.rs
yazi-core/src/notify/mod.rs
yazi-core/src/notify/notify.rs
yazi-fm/src/app/commands/mod.rs
yazi-fm/src/app/commands/notify.rs
yazi-fm/src/app/commands/render.rs
yazi-fm/src/app/commands/update_notify.rs
yazi-fm/src/components/progress.rs
yazi-fm/src/context.rs
yazi-fm/src/executor.rs
yazi-fm/src/main.rs
yazi-fm/src/notify/mod.rs
yazi-fm/src/notify/notify.rs
yazi-fm/src/widgets/clear.rs
yazi-shared/src/fs/fns.rs
yazi-shared/src/term/term.rs

https://github.com/sxyazi/yazi/assets/17523360/397eec4b-b4e8-413f-9b62-9f2b0765f30d

feat: Vim-like notification

---

yazi-core/src/manager/commands/open.rs

feat: add a new option `--hovered` to the `open` command

---

README.md

Why not adding the logo to the README? :D

feat: Yazi must have a duck logo in README

---

yazi-config/preset/theme.toml
yazi-core/src/tab/finder.rs
yazi-fm/src/lives/file.rs
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/file.lua
yazi-plugin/preset/components/folder.lua
yazi-plugin/preset/components/parent.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/src/elements/style.rs
yazi-plugin/src/plugin.rs

Also fixes https://github.com/sxyazi/yazi/issues/709 - @VeeBop

feat: better accessibility

---

yazi-fm/src/lives/file.rs
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/file.lua
yazi-plugin/preset/components/parent.lua
yazi-plugin/preset/plugins/folder.lua

Fixes https://github.com/sxyazi/yazi/pull/719#issuecomment-1962368506

fix: rendering fails when no file type style is matched

---

yazi-plugin/preset/plugins/mime.lua

Fixes https://github.com/sxyazi/yazi/issues/722

fix: skip when the mime-type cannot match due to file permissions

---

nix/yazi.nix

Looks like the current build is failing due to the wrong path to the completion files.

fix: correct the path to the completion files

---

yazi-config/preset/theme.toml
yazi-config/src/theme/theme.rs
yazi-fm/src/notify/layout.rs

I've been searching for a long time but haven't found how to trigger a notification, but I think my implementation should be able to work now.
Closes #717

feat: add a new `[notify]` section to the `theme.toml` to configure the `notify` component's style

---

yazi-config/src/open/open.rs

I hope I've understood correctly what was needed. I'm totally open to any feedback. :)
Closes:  #715

feat: add `prepend_rules` and `append_rules` for `[open]` in `yazi.toml`

---

yazi-config/preset/yazi.toml
yazi-core/src/tab/commands/escape.rs
yazi-core/src/tab/commands/select_all.rs
yazi-core/src/tab/selected.rs

Fixes https://github.com/sxyazi/yazi/issues/768

fix: nested conflict detection exception when performing cross-level searches

---

yazi-plugin/preset/components/header.lua
yazi-plugin/src/utils/text.rs

Closes https://github.com/sxyazi/yazi/issues/743

feat: truncate path for deeply nested directories

---

Cargo.lock
Cargo.toml
yazi-adaptor/Cargo.toml
yazi-adaptor/src/iterm2.rs
yazi-adaptor/src/kitty.rs
yazi-adaptor/src/kitty_old.rs
yazi-adaptor/src/sixel.rs
yazi-boot/Cargo.toml
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-fm/Cargo.toml
yazi-plugin/Cargo.toml
yazi-proxy/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-shared/Cargo.toml
yazi-shared/src/term/cursor.rs

Potentially fix https://github.com/sxyazi/yazi/issues/801

feat: fix all dependencies to specific version numbers to allow non-`--locked` builds

---

yazi-adaptor/src/image.rs
yazi-core/src/manager/commands/bulk_rename.rs
yazi-core/src/manager/commands/open.rs
yazi-core/src/manager/commands/remove.rs
yazi-core/src/manager/commands/yank.rs
yazi-core/src/manager/manager.rs
yazi-core/src/tab/commands/copy.rs
yazi-core/src/tab/commands/select_all.rs
yazi-core/src/tab/commands/visual_mode.rs
yazi-core/src/tab/mode.rs
yazi-core/src/tab/selected.rs
yazi-core/src/tab/tab.rs
yazi-fm/src/lives/file.rs
yazi-fm/src/lives/selected.rs
yazi-fm/src/logs.rs
yazi-shared/src/throttle.rs
yazi-shared/src/time.rs

This PR solves the problem of file name disorder when batch renaming by recording the time of selection and reordering selected items during it.

feat: time-based selection order preservation

---

Cargo.lock
yazi-boot/Cargo.toml
yazi-boot/src/lib.rs
yazi-dds/Cargo.toml
yazi-dds/src/body/body.rs
yazi-dds/src/client.rs
yazi-dds/src/server.rs
yazi-plugin/src/bindings/cha.rs
yazi-plugin/src/lua.rs
yazi-plugin/src/pubsub/pubsub.rs
yazi-plugin/src/utils/user.rs
yazi-plugin/src/utils/utils.rs

Resolves https://github.com/sxyazi/yazi/issues/872

feat: add `is_exec` and `is_sticky` to `Cha` bindings

---

yazi-core/src/manager/commands/bulk_rename.rs
yazi-core/src/manager/commands/open.rs
yazi-core/src/manager/commands/remove.rs
yazi-core/src/manager/commands/yank.rs
yazi-core/src/manager/manager.rs
yazi-core/src/tab/commands/copy.rs
yazi-core/src/tab/commands/shell.rs
yazi-core/src/tab/tab.rs

Fixes https://github.com/sxyazi/yazi/issues/889

fix: file list expansion arguments (`$@`, `$*`) of shell command under opener rules are out of order

---

yazi-config/preset/yazi.toml
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/plugins/folder.lua

Resolves https://github.com/sxyazi/yazi/issues/896

feat: default "Reveal" opener for Linux

---

yazi-core/src/completion/commands/show.rs

Implement smart case for path completion (issue #782)
https://github.com/sxyazi/yazi/assets/33489972/e9c503e1-0eea-4407-b379-b6c5f2882640

feat: Smart case completion

---

.github/workflows/release.yml
Cargo.lock
scripts/build.sh
yazi-boot/Cargo.toml
yazi-boot/src/lib.rs
yazi-cli/Cargo.toml
yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-dds/src/body/body.rs
yazi-dds/src/body/bye.rs
yazi-dds/src/body/mod.rs
yazi-dds/src/client.rs
yazi-dds/src/lib.rs
yazi-dds/src/payload.rs
yazi-dds/src/server.rs
yazi-dds/src/stream.rs
yazi-fm/Cargo.toml
yazi-fm/src/app/commands/accept_payload.rs
yazi-fm/src/main.rs
yazi-plugin/preset/plugins/dds.lua
yazi-plugin/preset/setup.lua
yazi-plugin/src/isolate/entry.rs
yazi-plugin/src/isolate/peek.rs
yazi-plugin/src/isolate/preload.rs
yazi-plugin/src/loader/loader.rs
yazi-plugin/src/utils/user.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/891
Closes https://github.com/sxyazi/yazi/issues/891
---
I'll add the `ya send` command documentation to https://yazi-rs.github.io in the next few days.

feat: add a new `ya send` command to allow standalone client processes to communicate with DDS from the command line

---

Cargo.lock
yazi-adaptor/Cargo.toml
yazi-boot/Cargo.toml
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-dds/Cargo.toml
yazi-fm/Cargo.toml
yazi-plugin/Cargo.toml
yazi-shared/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/921

fix: rollback ratatui to v0.26.1 to avoid panicking

---

yazi-plugin/src/external/highlighter.rs

Resolves https://github.com/sxyazi/yazi/issues/942

feat: support previewing files containing non-UTF-8 characters

---

yazi-config/preset/yazi.toml

close https://github.com/sxyazi/yazi/issues/983

feat: add `--force-window` option to mpv

---

yazi-core/src/notify/message.rs
yazi-fm/src/notify/layout.rs
yazi-proxy/src/options/notify.rs

Fixes https://github.com/sxyazi/yazi/issues/999

fix: notification title width does not include the width of the icon

---

Cargo.lock
yazi-cli/Cargo.toml
yazi-cli/build.rs
yazi-cli/src/args.rs
yazi-cli/src/main.rs

feat: add git commit hash to `ya --version`

---

yazi-core/src/manager/watcher.rs

Fixes https://github.com/sxyazi/yazi/issues/1017

fix: broaden file watcher event types to accommodate permission changes on certain platforms

---

Cargo.lock
yazi-adaptor/src/emulator.rs
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-config/Cargo.toml
yazi-config/preset/theme.toml
yazi-config/preset/yazi.toml
yazi-core/Cargo.toml
yazi-dds/Cargo.toml
yazi-fm/Cargo.toml
yazi-plugin/Cargo.toml
yazi-plugin/preset/plugins/font.lua
yazi-plugin/src/loader/loader.rs
yazi-proxy/Cargo.toml
yazi-shared/Cargo.toml

This requires installing the new [`ImageMagick`](https://imagemagick.org/) dependency, which will be listed as an **optional** dependency in Yazi v0.3.

feat: font preview

---

Cargo.lock
yazi-adaptor/Cargo.toml
yazi-config/Cargo.toml
yazi-config/preset/theme.toml
yazi-config/preset/yazi.toml
yazi-core/Cargo.toml
yazi-fm/Cargo.toml
yazi-plugin/Cargo.toml
yazi-shared/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/1062

fix: ePUB file mime-type matching for the opener rule

---

yazi-plugin/src/external/highlighter.rs

Fixes https://github.com/sxyazi/yazi/issues/1067

fix: inconsistent tab width in unassociated text files

---

README.md
yazi-adaptor/src/chafa.rs
yazi-adaptor/src/emulator.rs
yazi-adaptor/src/iterm2.rs
yazi-adaptor/src/kitty.rs
yazi-adaptor/src/kitty_old.rs
yazi-adaptor/src/sixel.rs
yazi-shared/src/term/cursor.rs

Fixes https://github.com/sxyazi/yazi/issues/1064

fix: cursor gets out of sync occasionally at image previewing through IIP under tmux

---

yazi-core/src/completion/commands/trigger.rs
yazi-core/src/input/commands/complete.rs

Closes https://github.com/sxyazi/yazi/issues/1074

feat: `cd` path auto-completion supports `~` expansion

---

yazi-core/src/folder/filter.rs
yazi-fm/src/lives/filter.rs
yazi-plugin/preset/components/header.lua

Header now shows filter when it is applied, as it did with search.
Closes https://github.com/sxyazi/yazi/issues/1181

feat: include file filter state in the header

---

yazi-config/preset/yazi.toml

Fixes https://github.com/sxyazi/yazi/issues/1183

feat: support `x-ndjson` mime-type for JSON files

---

yazi-adapter/src/ueberzug.rs

Fixes https://github.com/sxyazi/yazi/issues/1197

fix: ueberzug image adapter should respect the user's `max_width` and `max_height` settings

---

yazi-plugin/preset/plugins/magick.lua

Fixes https://github.com/sxyazi/yazi/issues/1209

fix: `magick` plugin not working properly

---

.github/ISSUE_TEMPLATE/bug.yml
.github/workflows/release.yml
scripts/build.sh

Fixes https://github.com/sxyazi/yazi/issues/1269
https://github.com/jemalloc/jemalloc/issues/467#issuecomment-2054282344

fix: build `jemalloc` with 64KB pagesize for `linux/arm64`

---

yazi-fm/src/app/commands/stop.rs

Fixes https://github.com/sxyazi/yazi/issues/1309

fix: destroy term before stopping signals

---

Cargo.lock
yazi-adapter/Cargo.toml
yazi-cli/Cargo.toml
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-fm/Cargo.toml
yazi-plugin/Cargo.toml
yazi-shared/Cargo.toml

fixes https://github.com/sxyazi/yazi/issues/1316

fix: add `use-dev-tty` to fix piping to Yazi on macOS

---

yazi-config/preset/keymap.toml

feat: make F1 also show the help screen

---

nix/yazi-unwrapped.nix

fix(nix): add `outputHashes` for `notify` git dependency

---

yazi-core/src/manager/commands/peek.rs
yazi-core/src/manager/watcher.rs
yazi-core/src/tab/commands/search.rs
yazi-core/src/tab/preview.rs
yazi-fs/src/files.rs
yazi-fs/src/folder.rs
yazi-shared/src/fs/cha.rs
yazi-shared/src/fs/file.rs
yazi-shared/src/fs/op.rs

Fixes https://github.com/sxyazi/yazi/issues/1426

fix: newly created directories with the same name causing a false positive in directory loading optimization due to having the same modification time

---

yazi-core/src/tab/preview.rs
yazi-fm/src/lives/folder.rs
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/plugins/folder.lua

Try to fix https://github.com/sxyazi/yazi/issues/1438

fix: directory loading status

---

yazi-config/src/keymap/key.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1445
Closes https://github.com/sxyazi/yazi/issues/1445

feat: support `F13` - `F19` keys

---

yazi-plugin/preset/plugins/archive.lua

Fixes https://github.com/sxyazi/yazi/issues/1450

fix: 7zip shows different error messages for wrong password

---

yazi-dds/src/sendable.rs

Fixes https://github.com/sxyazi/yazi/issues/1455

fix: loss of order in Lua sequence table for inter-thread data exchange

---

yazi-dds/src/pubsub.rs
yazi-dds/src/server.rs

Fixes https://github.com/sxyazi/yazi/issues/1460

fix: DDS static messages only work when at least two instances are running

---

yazi-config/preset/yazi.toml
yazi-plugin/preset/plugins/empty.lua
yazi-plugin/src/elements/span.rs
yazi-plugin/src/elements/style.rs
yazi-plugin/src/isolate/peek.rs
yazi-plugin/src/loader/loader.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1475
Closes https://github.com/sxyazi/yazi/issues/1475

feat: new `empty` previewer for empty and `/proc` files

---

yazi-config/src/theme/is.rs

Fixes https://github.com/sxyazi/yazi/issues/1481

feat: add `hidden` file type to `is` rule

---

yazi-config/preset/keymap.toml

feat: add keybinding for the `hardlink` command

---

Cargo.lock
Cargo.toml
yazi-adapter/Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-core/src/manager/watcher.rs
yazi-dds/Cargo.toml
yazi-fm/Cargo.toml
yazi-fs/Cargo.toml
yazi-plugin/Cargo.toml
yazi-proxy/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-shared/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/1384

chore: bump version to 0.3.1

---

yazi-plugin/src/external/highlighter.rs

Fixes https://github.com/sxyazi/yazi/issues/1496

fix: overlong single-line text containing escape sequences was not being properly escaped

---

Cargo.lock
Cargo.toml
scripts/build.sh
yazi-adapter/src/chafa.rs
yazi-fs/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/1495

fix: upgrade `ansi-to-tui` to `5.0.0-rc.1` to resolve `ratatui` version conflict

---

Cargo.lock
Cargo.toml
yazi-dds/Cargo.toml
yazi-dds/src/lib.rs
yazi-dds/src/stream.rs
yazi-plugin/Cargo.toml
yazi-plugin/src/utils/user.rs
yazi-shared/Cargo.toml
yazi-shared/src/lib.rs
yazi-shared/src/os.rs
yazi-shared/src/xdg.rs

Fixes https://github.com/sxyazi/yazi/issues/1527

fix: use a different cache directory for each user to avoid permission issues

---

Cargo.lock
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-core/src/manager/commands/peek.rs

Fixes https://github.com/sxyazi/yazi/issues/1537

fix: wait till mimetype is resolved to avoid flickering

---

Cargo.lock
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-config/Cargo.toml
yazi-config/src/keymap/chord.rs
yazi-config/src/keymap/cow.rs
yazi-config/src/keymap/keymap.rs
yazi-config/src/keymap/mod.rs
yazi-config/src/open/open.rs
yazi-config/src/plugin/plugin.rs
yazi-config/src/preset.rs
yazi-config/src/theme/icons.rs
yazi-core/src/help/help.rs
yazi-core/src/which/commands/show.rs
yazi-core/src/which/sorter.rs
yazi-core/src/which/which.rs
yazi-fm/src/router.rs
yazi-fm/src/which/cand.rs
yazi-plugin/src/utils/layer.rs

Fixes https://github.com/sxyazi/yazi/issues/1560

fix: filter out the `which` candidates that overlap with longer key chords

---

yazi-fs/src/folder.rs

fix: adjust `offset` value after resizing window

---

yazi-adapter/src/adapter.rs
yazi-adapter/src/lib.rs
yazi-boot/src/actions/debug.rs
yazi-core/src/manager/watcher.rs
yazi-shared/src/env.rs

Fixes https://github.com/sxyazi/yazi/issues/1559

fix: fallback to `PollWatcher` on WSL

---

yazi-plugin/preset/components/tab.lua

Fixes https://github.com/sxyazi/yazi/issues/1584

fix: `Rail` component should have a higher rendering priority

---

yazi-plugin/src/url/url.rs

Supersedes https://github.com/sxyazi/yazi/pull/1603

feat: add `is_absolute`, `has_root`, `starts_with`, `ends_with`, `strip_prefix` to `Url` Userdata

---

scripts/publish.sh
yazi-config/src/theme/icons.rs

Fixes https://github.com/sxyazi/yazi/issues/1613

fix: match icon by extension case-insensitive

---

yazi-plugin/src/elements/bar.rs
yazi-plugin/src/elements/border.rs
yazi-plugin/src/elements/gauge.rs
yazi-plugin/src/elements/line.rs
yazi-plugin/src/elements/list.rs
yazi-plugin/src/elements/paragraph.rs
yazi-plugin/src/elements/span.rs
yazi-plugin/src/elements/style.rs
yazi-plugin/src/macros.rs

An implementation of the feature request: https://github.com/yazi-rs/plugins/issues/21
Closes https://github.com/yazi-rs/plugins/issues/21

feat: complete and consistent support for the `ui.Style()` API

---

.cargo/config.toml

feat: improve jemalloc memory efficiency

---

yazi-fs/src/files.rs

Fixes https://github.com/sxyazi/yazi/issues/1418#issuecomment-2377716517

fix: increase the revision when there is a change in `Urn` on updating

---

.github/ISSUE_TEMPLATE/feature.yml
yazi-plugin/src/loader/require.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1328
Closes https://github.com/sxyazi/yazi/issues/1328

feat: allow overriding and rewriting the sync methods of builtin plugins

---

yazi-plugin/src/external/highlighter.rs
yazi-shared/src/chars.rs

Fixes https://github.com/sxyazi/yazi/issues/1702

fix: replace control characters to printable characters in plain text preview

---

Cargo.lock
yazi-adapter/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/1717

fix: temporarily disable TIFF decoding

---

yazi-plugin/preset/plugins/code.lua

Fixes https://github.com/sxyazi/yazi/issues/1699

fix: clamp when seeking a non-zero unit between `-1` and `1`

---

yazi-plugin/src/elements/elements.rs
yazi-plugin/src/elements/mod.rs
yazi-plugin/src/elements/paragraph.rs
yazi-plugin/src/isolate/isolate.rs

Follow up to https://github.com/sxyazi/yazi/pull/1776

feat: add a compatibility layer for `ui.Paragraph` to help users transition more smoothly to the new `ui.Text`

---

yazi-cli/src/main.rs
yazi-cli/src/package/parser.rs

Closes https://github.com/sxyazi/yazi/issues/1790

refactor: remove migration code as it's no longer needed and causes errors

---

yazi-plugin/src/process/child.rs

Closes https://github.com/sxyazi/yazi/issues/1814

feat: support reading non-UTF8 data with `Child::read_line` API

---

flake.lock
flake.nix
yazi-fm/src/lives/tab.rs
yazi-shared/src/fs/fns.rs

Try to fix https://github.com/sxyazi/yazi/issues/1775 again

fix: use std copy function in a blocking thread

---

Cargo.lock
Cargo.toml
yazi-codegen/Cargo.toml
yazi-plugin/preset/plugins/zoxide.lua

Closes https://github.com/sxyazi/yazi/issues/1819

feat: allow customizing Zoxide's FZF options with `YAZI_ZOXIDE_OPTS`

---

yazi-core/src/manager/commands/peek.rs

Fixes https://github.com/sxyazi/yazi/issues/1827

fix: reset image rendering and skip peeking if the TUI in the background

---

yazi-core/src/tab/commands/copy.rs
yazi-shared/src/fs/loc.rs

Fixes https://github.com/sxyazi/yazi/issues/1836

fix: copy the CWD path regardless even if the directory is empty

---

yazi-config/src/keymap/chord.rs
yazi-config/src/keymap/keymap.rs
yazi-config/src/open/open.rs
yazi-config/src/plugin/plugin.rs
yazi-config/src/preset.rs
yazi-config/src/theme/icons.rs
yazi-plugin/preset/plugins/zoxide.lua

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1880
Closes https://github.com/sxyazi/yazi/issues/1880
Doc: https://yazi-rs.github.io/docs/configuration/keymap/#manager.noop

feat: allow disabling certain preset keybinds with the new `noop` virtual command

---

yazi-core/src/manager/manager.rs
yazi-core/src/manager/tabs.rs
yazi-fm/src/executor.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1852
Closes https://github.com/sxyazi/yazi/issues/1852

feat: add a new `tab` parameter for all tab-specific commands to specify which one

---

CODE_OF_CONDUCT.MD

Let me know if anything needs fixing or if you want any changes made to the draft :) I followed the Contributor Covenant Code of Conduct while making this one which is why they are credited at the bottom.
Closes https://github.com/sxyazi/yazi/issues/1905

chore: add `CODE_OF_CONDUCT.md`

---

yazi-plugin/preset/plugins/noop.lua

feat: `noop` for spotters

---

yazi-fm/src/notify/notify.rs

This PR aims to minimize the disruption of notifications to the user's focus. 
I think moving it to the bottom is a good approach because I've noticed that most of the time, my attention is focused at the top, where the current directory and copy/cut counters are displayed. 
Also, video and image previews start from the top. Moving the notification to the bottom could also potentially prevent overlapping with images, which would otherwise cause them to re-render and save CPU.
Thanks to @mikavilpas for the inspiration for this idea in https://github.com/mikavilpas/yazi.nvim/issues/594#issuecomment-2512232697!

feat: move notification from top-right to bottom-right corner to avoid covering content as much as possible

---

.github/DISCUSSION_TEMPLATE/1-q-a.yml
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
yazi-core/src/manager/commands/open.rs
yazi-core/src/manager/commands/peek.rs
yazi-core/src/manager/commands/seek.rs
yazi-core/src/manager/commands/spot.rs
yazi-core/src/manager/commands/unyank.rs
yazi-core/src/manager/commands/update_mimes.rs
yazi-core/src/manager/mimetype.rs
yazi-core/src/manager/watcher.rs
yazi-core/src/manager/yanked.rs
yazi-core/src/tasks/preload.rs
yazi-core/src/tasks/process.rs
yazi-fm/src/lives/file.rs
yazi-plugin/src/elements/bar.rs
yazi-plugin/src/elements/border.rs
yazi-plugin/src/elements/cell.rs
yazi-plugin/src/elements/clear.rs
yazi-plugin/src/elements/gauge.rs
yazi-plugin/src/elements/list.rs
yazi-plugin/src/elements/rect.rs
yazi-plugin/src/elements/renderable.rs
yazi-plugin/src/elements/row.rs
yazi-plugin/src/elements/table.rs
yazi-plugin/src/elements/text.rs
yazi-plugin/src/utils/preview.rs
yazi-proxy/src/options/open.rs

Fixes https://github.com/sxyazi/yazi/issues/1848

fix: missing a repeek on unyanking files in the hovered folder

---

yazi-core/src/input/commands/backspace.rs
yazi-core/src/input/commands/complete.rs
yazi-core/src/input/snap.rs

Fixes https://github.com/sxyazi/yazi/issues/2009

fix: `backspace --under` didn't map UTF-8 character code points to byte indices

---

Cargo.lock
Cargo.toml
yazi-adapter/src/drivers/ueberzug.rs
yazi-config/preset/README.md

Fixes https://github.com/sxyazi/yazi/issues/2018
Fixes https://github.com/sxyazi/yazi/issues/2019

fix: failed to parse certain image dimensions for Überzug++ backend

---

yazi-core/src/completion/commands/show.rs
yazi-core/src/completion/commands/trigger.rs
yazi-core/src/completion/completion.rs

Fixes https://github.com/sxyazi/yazi/issues/2024

fix: interactive `cd` autocomplete doesn't follow the latest `CWD` changes

---

yazi-core/src/tab/folder.rs
yazi-fs/src/files.rs

Fixes https://github.com/sxyazi/yazi/issues/2028

fix: offset cursor shift when deleting multiple files in bulk

---

yazi-config/src/open/opener.rs

Resolves https://github.com/termux/termux-packages/issues/18935#issuecomment-2536406490

feat: support for Android platform in the `for` qualifier of opener

---

yazi-config/src/keymap/keymap.rs

Fixes https://github.com/sxyazi/yazi/issues/2063

feat: allow `noop` for single-key chords by removing the mixing length limit

---

yazi-config/preset/theme-dark.toml
yazi-config/preset/theme-light.toml
yazi-config/src/theme/theme.rs
yazi-plugin/src/utils/spot.rs

Allows changing the colors of https://github.com/sxyazi/yazi/pull/1802. Fixes #1986.

feat: theme support for the spotter border and title

---

yazi-plugin/preset/plugins/extract.lua

https://en.wikipedia.org/wiki/Comic_book_archive

feat: add `cbr` and `cbz` as valid archive extensions

---

yazi-adapter/src/brand.rs

A workaround for https://github.com/sxyazi/yazi/issues/2106#issuecomment-2563761498

fix: add Alacritty to the database as a terminal that doesn't support any image protocol

---

README.md

Ghostty is finally up! so I thought the readme link should also be changed!
Thanks

docs: update the links in the README

---

Cargo.lock
Cargo.toml
yazi-codegen/Cargo.toml
yazi-core/src/manager/commands/rename.rs

Fixes https://github.com/sxyazi/yazi/issues/2118

fix: `before_ext` should exclude directories since only files have extensions

---

Cargo.lock
yazi-fs/src/mounts/linux.rs
yazi-shared/Cargo.toml
yazi-shared/src/chars.rs

Fixes https://github.com/yazi-rs/plugins/pull/53#issuecomment-2607093668

fix: unmangle the hexadecimal space strings (`"\x20"`) in Linux partition labels

---

yazi-plugin/src/config/config.rs
yazi-plugin/src/lib.rs
yazi-plugin/src/lua.rs
yazi-plugin/src/utils/json.rs

Fixes https://github.com/yazi-rs/plugins/pull/54#issuecomment-2612718151

fix: JSON value `null` should be deserialized as Lua `nil`, not lightweight userdata `null`

---

yazi-cli/src/package/package.rs
yazi-fs/src/fns.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2195
Closes https://github.com/sxyazi/yazi/issues/2195

feat: support `package.toml` as a symlink

---

Cargo.lock
Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-cli/src/package/deploy.rs
yazi-cli/src/package/package.rs

Allow users to:
- Add multiple packages at once: `ya pack -a A B C D`
- Delete multiple packages at once: `ya pack -d A B C D`
Fixes #2250
Fixes https://github.com/sxyazi/yazi/issues/1763
Closes https://github.com/sxyazi/yazi/pull/2260

feat: `ya pack` supports adding and deleting multiple packages at the same time

---

yazi-shared/src/shell/windows.rs

Fixes https://github.com/sxyazi/yazi/issues/2281

fix: correct shell quotes for Unicode on Windows

---

.github/workflows/draft.yml
Cargo.toml
yazi-fm/build.rs

Try to fix https://github.com/sxyazi/yazi/issues/2272
See https://github.com/mlua-rs/mlua/issues/520

fix: enable unwinding on Windows release builds

---

Cargo.lock
README.md
yazi-adapter/Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-codegen/Cargo.toml
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-dds/Cargo.toml
yazi-ffi/Cargo.toml
yazi-fm/Cargo.toml
yazi-fs/Cargo.toml
yazi-macro/Cargo.toml
yazi-plugin/Cargo.toml
yazi-proxy/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-shared/Cargo.toml

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2251
Closes https://github.com/sxyazi/yazi/issues/2251

feat: switch to Calendar Versioning

---

yazi-plugin/preset/plugins/pdf.lua

Fixes https://github.com/sxyazi/yazi/discussions/2271

feat: respect the user's `max_width` setting for the built-in PDF preloader

---

yazi-plugin/preset/plugins/empty.lua

Fixes https://github.com/sxyazi/yazi/issues/2350

fix: add maximum preview limit under `/proc` virtual file system

---

Cargo.lock
yazi-boot/src/actions/debug.rs
yazi-core/Cargo.toml
yazi-core/src/manager/commands/open.rs
yazi-core/src/manager/tabs.rs
yazi-core/src/tasks/process.rs
yazi-proxy/src/options/open.rs
yazi-shared/src/url/url.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2359
Closes https://github.com/sxyazi/yazi/issues/2359

feat: add a link to the debugging instructions in `yazi --debug`

---

yazi-plugin/src/bindings/cha.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2386
Closes https://github.com/sxyazi/yazi/issues/2386

feat: expose `mode` field in `Cha`

---

yazi-adapter/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/2414

fix: `windows-sys` features for `Win32_Storage_FileSystem` and `Win32_System_Threading`

---

scripts/validate-form/main.js
yazi-plugin/src/loader/loader.rs

fix: incorrect deprecation warning when the plugin doesn't exist

---

yazi-adapter/src/emulator.rs
yazi-adapter/src/stdin.rs

Fixes https://github.com/sxyazi/yazi/issues/2423

fix: `STDIN_FILENO` poll always returns 0 under SSH

---

yazi-adapter/src/brand.rs

Fixes https://github.com/sxyazi/yazi/issues/2440
Run Yazi with:
```
TERM=rxvt-unicode-256color yazi
```

fix: reserve a hack for Zellij to force an image adapter

---

Cargo.lock
yazi-adapter/Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-codegen/Cargo.toml
yazi-config/Cargo.toml
yazi-core/Cargo.toml
yazi-dds/Cargo.toml
yazi-dds/src/sendable.rs
yazi-ffi/Cargo.toml
yazi-fm/Cargo.toml
yazi-fs/Cargo.toml
yazi-macro/Cargo.toml
yazi-plugin/Cargo.toml
yazi-plugin/src/file/file.rs
yazi-plugin/src/fs/fs.rs
yazi-plugin/src/fs/mod.rs
yazi-plugin/src/fs/op.rs
yazi-plugin/src/id.rs
yazi-plugin/src/lib.rs
yazi-plugin/src/url/url.rs
yazi-plugin/src/utils/app.rs
yazi-plugin/src/utils/utils.rs
yazi-proxy/Cargo.toml
yazi-scheduler/Cargo.toml
yazi-shared/Cargo.toml

Demo: [vcs-files.yazi](https://github.com/yazi-rs/plugins/tree/main/vcs-files.yazi) plugin - Show Git changed files in Yazi.

feat: custom search engine Lua API

---

yazi-core/src/mgr/commands/tab_close.rs
yazi-core/src/mgr/commands/tab_swap.rs
yazi-core/src/mgr/commands/tab_switch.rs
yazi-core/src/mgr/tabs.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2455
Closes https://github.com/sxyazi/yazi/issues/2455

feat: allow `tab_swap` to cycle tabs

---

yazi-plugin/preset/plugins/extract.lua

Trying to fix https://github.com/sxyazi/yazi/issues/2445

fix: remove the temporary extraction directory forcefully

---

yazi-config/src/theme/is.rs
yazi-core/src/mgr/watcher.rs
yazi-core/src/tab/commands/search.rs
yazi-core/src/tab/folder.rs
yazi-core/src/tab/preview.rs
yazi-fs/src/cha/cha.rs
yazi-fs/src/cha/kind.rs
yazi-fs/src/cha/mod.rs
yazi-fs/src/file.rs
yazi-fs/src/files.rs
yazi-fs/src/fns.rs
yazi-fs/src/lib.rs
yazi-fs/src/mounts/partitions.rs
yazi-fs/src/op.rs
yazi-plugin/src/bindings/cha.rs
yazi-plugin/src/utils/preview.rs
yazi-plugin/src/utils/spot.rs
yazi-scheduler/src/file/file.rs
yazi-scheduler/src/file/op.rs

Fixes https://github.com/sxyazi/yazi/issues/2460

fix: respect hidden status of directory junctions and symlinks themselves on Windows

---

Cargo.lock
yazi-boot/Cargo.toml
yazi-boot/src/args.rs
yazi-cli/Cargo.toml
yazi-config/src/popup/input.rs
yazi-dds/src/body/body.rs
yazi-dds/src/body/hey.rs
yazi-dds/src/client.rs
yazi-dds/src/lib.rs
yazi-dds/src/payload.rs
yazi-dds/src/pubsub.rs
yazi-dds/src/server.rs
yazi-plugin/src/id.rs
yazi-plugin/src/pubsub/pubsub.rs
yazi-plugin/src/utils/app.rs
yazi-shared/src/id.rs
yazi-widgets/src/input/commands/move_.rs
yazi-widgets/src/input/snap.rs
yazi-widgets/src/input/snaps.rs
yazi-widgets/src/input/widget.rs

Closes https://github.com/sxyazi/yazi/issues/2502
`ya.id("app")` returns an `Id` userdata, you can get an integer representation with its `.value` attribute:
```lua
ya.id("app").value
```

feat: new `ya.id("app")` to get `YAZI_ID` in plugins

---

Cargo.lock
yazi-core/src/mgr/watcher.rs
yazi-core/src/tab/preview.rs
yazi-fm/src/lives/folder.rs
yazi-fs/src/files.rs
yazi-fs/src/op.rs
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/src/error.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/1137
Closes https://github.com/sxyazi/yazi/issues/1137

feat: show error message when directory fails to load

---

yazi-config/preset/yazi-default.toml

An implementation of the feature request: #2424
Closes #2424

feat: clear terminal before displaying EXIF data

---

.cargo/config.toml
Cargo.lock
Cargo.toml
yazi-plugin/preset/plugins/svg.lua

Fixes https://github.com/sxyazi/yazi/issues/2562

fix: remove `-density` option from `magick` command in SVG previewer

---

Cargo.lock
README.md
yazi-adapter/src/brand.rs
yazi-adapter/src/unknown.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2511
Closes https://github.com/sxyazi/yazi/issues/2511

feat: support Warp terminal image preview

---

yazi-adapter/src/adapter.rs
yazi-plugin/src/process/child.rs

Fixes https://github.com/sxyazi/yazi/issues/2585

fix: ignore XQuartz `$DISPLAY` variable

---

Cargo.lock
scripts/build.sh
scripts/bump.sh
scripts/publish.sh
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-config/src/lib.rs
yazi-dds/Cargo.toml

Fixes https://github.com/sxyazi/yazi/issues/2593

fix: reverse the mixing order of theme and flavor configuration

---

yazi-cli/src/package/add.rs
yazi-cli/src/package/delete.rs
yazi-cli/src/package/deploy.rs
yazi-cli/src/package/git.rs
yazi-cli/src/package/hash.rs
yazi-cli/src/package/install.rs
yazi-cli/src/package/package.rs

Fixes https://github.com/sxyazi/yazi/issues/2600

fix: ensure state synchronization even when the package update fails midway

---

.github/workflows/cachix.yml
.github/workflows/check.yml
.github/workflows/draft.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-cli/src/package/add.rs
yazi-cli/src/package/install.rs
yazi-dds/Cargo.toml
yazi-widgets/Cargo.toml
yazi-widgets/src/input/input.rs

Fixes https://github.com/sxyazi/yazi/issues/2600#issuecomment-2799939220

fix: do not change revision when package deployment fails

---

yazi-plugin/preset/plugins/video.lua

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2518
Closes https://github.com/sxyazi/yazi/issues/2518
---
With this PR, Yazi now will check if the video has an embedded cover, and if has one, it will be used as the first image for the scrollable video preview among the rest.

feat: support embedded cover for video preview

---

Cargo.lock
Cargo.toml
yazi-codegen/Cargo.toml
yazi-config/preset/yazi-default.toml
yazi-config/src/preview/preview.rs

See https://github.com/sxyazi/yazi/issues/2677#issuecomment-2833378614

feat: increase the maximum allowed value of `sixel_fraction` to `30`

---

yazi-fs/src/calculator.rs
yazi-plugin/src/bindings/calculator.rs
yazi-plugin/src/bindings/mod.rs
yazi-plugin/src/fs/fs.rs
yazi-scheduler/src/prework/prework.rs

How to use:
```lua
local total = 0
local it = fs.calc_size(Url("/tmp/yazi"))
while true do
local found = it:recv()
if found then
ya.dbg("found: " .. found)
total = total + found
else
break
end
end
ya.dbg("done! total: " .. total)
```
Output:
```
found: 1956532522
found: 911553073
found: 1100032563
found: 1079350830
found: 943483457
found: 1160212602
found: 490316018
found: 821866
found: 104071422
found: 256609193
found: 512100934
found: 473746322
found: 957889320
found: 1439720840
found: 59380140
done! total: 11445821102
```

feat: new `fs.calc_size()` API

---

Cargo.lock
Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-cli/src/args.rs
yazi-dds/src/client.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2680
Closes https://github.com/sxyazi/yazi/issues/2680

feat: checks in `ya pub` and `ya emit` subcommands to verify receiver exists and has necessary abilities

---

yazi-dds/src/client.rs

Issue
=====
In https://github.com/sxyazi/yazi/issues/2680, `ya pub-to` received the ability to check if the target peer is able to receive the message that is being sent. However, if the target peer is `0` (sending to all peers), the implementation failed.
Solution
========
Check if any peer is able to receive the message when the target peer is `0`.

fix: `ya pub-to 0` checks if any peer is able to receive the message

---

Cargo.lock
yazi-core/src/tab/commands/cd.rs
yazi-core/src/tab/commands/sort.rs
yazi-dds/src/client.rs

Closes https://github.com/sxyazi/yazi/issues/2711

fix: missing a `hover` event after `cd`

---

yazi-core/src/tab/commands/back.rs
yazi-core/src/tab/commands/cd.rs
yazi-core/src/tab/commands/enter.rs
yazi-core/src/tab/commands/forward.rs
yazi-core/src/tab/commands/leave.rs
yazi-core/src/tab/commands/reveal.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2687
Closes https://github.com/sxyazi/yazi/issues/2687

feat: increase the granularity of `back`/`forward` history navigation to make its behavior more sensible

---

.github/pull_request_template.md
CONTRIBUTING.md
Cargo.lock
Cargo.toml
yazi-boot/Cargo.toml
yazi-cli/Cargo.toml
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/header.lua
yazi-plugin/preset/components/status.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/svg.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/src/elements/bar.rs
yazi-plugin/src/elements/border.rs
yazi-plugin/src/elements/gauge.rs
yazi-plugin/src/elements/line.rs
yazi-plugin/src/elements/renderable.rs
yazi-plugin/src/elements/text.rs
yazi-plugin/src/macros.rs

Previously, `ui.Line` was not renderable on its own, so it had to be wrapped inside a `ui.Text`:
```lua
ui.Text(ui.Line("Hello World")):area(rect)
```
Now, you can render `ui.Line` directly:
```lua
ui.Line("Hello World"):area(rect)
```

feat: make `ui.Line` renderable

---

yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/parent.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/src/elements/line.rs

An implementation of the feature request: https://github.com/sxyazi/yazi/issues/903
Resolves https://github.com/sxyazi/yazi/issues/903

feat: truncate long items in the file list

---

Cargo.lock
Cargo.toml
yazi-plugin/preset/components/current.lua
yazi-plugin/preset/components/entity.lua
yazi-plugin/preset/components/parent.lua
yazi-plugin/preset/plugins/folder.lua
yazi-plugin/src/elements/line.rs
yazi-plugin/src/elements/span.rs
yazi-plugin/src/utils/layer.rs

Follow up to https://github.com/sxyazi/yazi/pull/2754

feat: show file extension for truncated file list items

---

yazi-plugin/preset/components/entity.lua
yazi-plugin/preset/plugins/archive.lua
yazi-plugin/src/elements/bar.rs
yazi-plugin/src/elements/border.rs
yazi-plugin/src/elements/clear.rs
yazi-plugin/src/elements/constraint.rs
yazi-plugin/src/elements/elements.rs
yazi-plugin/src/elements/gauge.rs
yazi-plugin/src/elements/layout.rs
yazi-plugin/src/elements/line.rs
yazi-plugin/src/elements/list.rs
yazi-plugin/src/elements/mod.rs
yazi-plugin/src/elements/pad.rs
yazi-plugin/src/elements/pos.rs
yazi-plugin/src/elements/rect.rs
yazi-plugin/src/elements/row.rs
yazi-plugin/src/elements/span.rs
yazi-plugin/src/elements/style.rs
yazi-plugin/src/elements/table.rs
yazi-plugin/src/elements/text.rs
yazi-plugin/src/elements/utils.rs
yazi-plugin/src/utils/text.rs

Follow up to https://github.com/sxyazi/yazi/pull/2754, https://github.com/sxyazi/yazi/pull/2759

feat: truncate long paths in archive preview file list

---

Cargo.lock
Cargo.toml
scripts/publish.sh
yazi-plugin/src/elements/elements.rs

Resolves https://github.com/sxyazi/yazi/issues/2809

fix: expose `ui.Wrap`

---

yazi-fs/src/cha/cha.rs

fix: incomplete hidden state check on Windows for `Cha`

---

yazi-cli/src/args.rs
yazi-cli/src/main.rs
yazi-cli/src/package/package.rs

Resolves https://github.com/sxyazi/yazi/issues/2836

feat: allow upgrading only specific packages

---

Cargo.lock
Cargo.toml
yazi-binding/src/error.rs
yazi-cli/src/args.rs
yazi-cli/src/package/package.rs
yazi-config/Cargo.toml
yazi-config/preset/yazi-default.toml
yazi-core/src/mgr/yanked.rs
yazi-plugin/preset/plugins/font.lua
yazi-plugin/preset/plugins/image.lua
yazi-plugin/preset/plugins/magick.lua
yazi-plugin/preset/plugins/pdf.lua
yazi-plugin/preset/plugins/svg.lua
yazi-plugin/preset/plugins/video.lua
yazi-plugin/src/bindings/chan.rs
yazi-plugin/src/elements/text.rs
yazi-plugin/src/utils/image.rs
yazi-shared/src/url/url.rs

Also fixes https://github.com/sxyazi/yazi/issues/2854

feat: search view shares file selection and yank state

---

Cargo.lock
yazi-adapter/src/lib.rs
yazi-adapter/src/mux.rs
yazi-cli/src/args.rs
yazi-config/src/keymap/chord.rs
yazi-core/src/tab/commands/copy.rs
yazi-fm/src/term.rs
yazi-plugin/src/elements/table.rs
yazi-shared/src/shell/mod.rs
yazi-shared/src/shell/unix.rs
yazi-shared/src/shell/windows.rs
yazi-shared/src/translit/traits.rs
yazi-term/src/tty/tty.rs
yazi-widgets/src/input/input.rs

See https://github.com/rust-lang/rust/issues/141787

refactor: satisfy `mismatched-lifetime-syntaxes` lint

---

yazi-core/src/notify/commands/push.rs
yazi-core/src/notify/commands/tick.rs
yazi-proxy/src/app.rs
yazi-proxy/src/cmp.rs
yazi-proxy/src/confirm.rs
yazi-proxy/src/input.rs
yazi-proxy/src/mgr.rs
yazi-proxy/src/options/notify.rs
yazi-proxy/src/pick.rs
yazi-proxy/src/tab.rs
yazi-proxy/src/tasks.rs
yazi-shared/src/event/data.rs

Fixes https://github.com/sxyazi/yazi/issues/2882

fix: interoperability between number, integer, and id

---

yazi-binding/src/url.rs
yazi-core/src/mgr/commands/update_mimes.rs
yazi-core/src/mgr/mimetype.rs
yazi-core/src/tab/commands/search.rs
yazi-core/src/tab/selected.rs
yazi-fm/src/cmp/cmp.rs
yazi-proxy/src/tab.rs
yazi-shared/src/bytes.rs
yazi-shared/src/event/data.rs
yazi-shared/src/lib.rs
yazi-shared/src/osstr.rs
yazi-shared/src/url/mod.rs
yazi-shared/src/url/scheme.rs
yazi-shared/src/url/url.rs

Resolves https://github.com/sxyazi/yazi/issues/2874

feat: allow `Url` to accept invalid UTF-8 characters

---

yazi-binding/src/url.rs
yazi-core/src/mgr/commands/update_mimes.rs
yazi-plugin/src/process/command.rs
yazi-shared/src/event/data.rs

Resolves https://github.com/sxyazi/yazi/issues/2874#issuecomment-2983591064
Closes https://github.com/sxyazi/yazi/pull/2892

feat: invalid UTF-8 support to `Command:arg()` and `Command:env()` APIs

---

Cargo.lock
yazi-adapter/src/adapter.rs
yazi-cli/Cargo.toml
yazi-codegen/Cargo.toml
yazi-config/src/keymap/keymap.rs
yazi-config/src/lib.rs
yazi-config/src/theme/theme.rs
yazi-config/src/yazi.rs
yazi-fm/Cargo.toml
yazi-scheduler/src/hooks.rs

Resolves https://github.com/sxyazi/yazi/issues/2898

fix: Cargo doesn't respect the workspace profile settings

---

Cargo.lock
yazi-adapter/src/brand.rs
yazi-fs/src/file.rs
yazi-plugin/src/lib.rs
yazi-plugin/src/twox.rs
yazi-plugin/src/utils/cache.rs

Fixes https://github.com/sxyazi/yazi/issues/2918

fix: incomplete cache calculation algorithm

---

yazi-core/src/mgr/watcher.rs

Fixes https://github.com/sxyazi/yazi/issues/2940

fix: fallback to `PollWatcher` on NetBSD

---

Cargo.lock
Cargo.toml
yazi-config/src/lib.rs
yazi-core/src/cmp/commands/trigger.rs
yazi-fm/src/executor.rs
yazi-parser/src/cmp/trigger.rs
yazi-widgets/src/input/commands/commands.rs

Resolves #2966 
See the corresponding issue linked above for details.

feat: make `ticket` optional for `cmp:trigger`

---

Cargo.lock
Cargo.toml
yazi-binding/src/elements/bar.rs
yazi-binding/src/elements/border.rs
yazi-binding/src/elements/clear.rs
yazi-binding/src/elements/gauge.rs
yazi-binding/src/elements/layout.rs
yazi-binding/src/elements/line.rs
yazi-binding/src/elements/list.rs
yazi-binding/src/elements/pad.rs
yazi-binding/src/elements/pos.rs
yazi-binding/src/elements/rect.rs
yazi-binding/src/elements/row.rs
yazi-binding/src/elements/span.rs
yazi-binding/src/elements/table.rs
yazi-binding/src/elements/text.rs
yazi-binding/src/style.rs
yazi-plugin/src/isolate/peek.rs
yazi-plugin/src/isolate/preload.rs
yazi-plugin/src/isolate/spot.rs
yazi-plugin/src/loader/chunk.rs
yazi-plugin/src/loader/require.rs
yazi-plugin/src/process/command.rs

refactor: upgrade to `mlua` v0.11.0

---

yazi-binding/src/url.rs
yazi-fs/src/path.rs
yazi-shared/src/url/scheme.rs

Fixes https://github.com/sxyazi/yazi/issues/3027

fix: keep original scheme when expanding URLs

---

yazi-actor/src/mgr/rename.rs
yazi-binding/src/cha.rs
yazi-fs/src/cha/cha.rs
yazi-fs/src/cha/kind.rs
yazi-fs/src/cha/mod.rs
yazi-fs/src/cha/mode.rs
yazi-fs/src/cha/type.rs
yazi-fs/src/file.rs
yazi-fs/src/files.rs
yazi-fs/src/fns.rs
yazi-fs/src/provider/dir_entry.rs
yazi-fs/src/provider/local/dir_entry.rs
yazi-fs/src/provider/sftp/metadata.rs
yazi-fs/src/provider/sftp/mod.rs
yazi-fs/src/provider/sftp/read_dir.rs
yazi-fs/src/provider/sftp/sftp.rs
yazi-fs/src/provider/traits.rs

Prepare for https://github.com/sxyazi/yazi/issues/611

feat: introduce `ChaType` for better cross-filesystem consistency

---

yazi-boot/src/actions/debug.rs

Closes https://github.com/sxyazi/yazi/issues/3196

feat: include `$FZF_DEFAULT_COMMAND` in debug output

---

yazi-fs/src/provider/local/casefold.rs
yazi-fs/src/provider/local/local.rs
yazi-fs/src/provider/provider.rs
yazi-fs/src/provider/providers.rs
yazi-fs/src/provider/sftp/metadata.rs
yazi-fs/src/provider/sftp/read_dir.rs
yazi-fs/src/provider/sftp/sftp.rs
yazi-fs/src/provider/traits.rs
yazi-sftp/src/error.rs
yazi-sftp/src/session.rs
yazi-term/src/tty/handle.rs
yazi-term/src/tty/tty.rs
yazi-watcher/src/watcher.rs

Prepare for https://github.com/sxyazi/yazi/issues/611

feat: casefold support for the SFTP provider

---

yazi-fs/src/cwd.rs

Fixes https://github.com/sxyazi/yazi/issues/3206

fix: only create mapped local working directories for virtual file systems
